### ISSUE TITLE
various win32 fixes and tests

### ISSUE THREAD

**Issue by tmm1** [eventmachine/eventmachine#105]
See http://github.com/raphael/eventmachine/commit/e3fe8d4fb6a25b9e29f84179f57450332c9e405d

The majority of this patch was a change from closesocket -> close, which is already in master. Other highlights include VC6 support, and an IsConnectionPending guard on the select() errors fdset.

**Comment by sodabrew** [comment]
I don't think VC6 is useful / interesting anymore.
The IsConnectionPending guard is not yet in tree. It looks like something we might still want:

``` diff
 		#ifdef OS_WIN32
 		/* 21Sep09: on windows, a non-blocking connect() that fails does not come up as writable.
 		   Instead, it is added to the error set. See http://www.mail-archive.com/openssl-users@openssl.org/msg58500.html
 		*/
-		FD_SET (sd, &(SelectData.fderrors));
+		if (ed->IsConnectionPending())
+			FD_SET (sd, &(SelectData.fderrors));
 		#endif
```

**Comment by tmm1** [comment]
Adding that guard seems reasonable.

**Comment by tmm1** [comment]
committed in 1ea454987464207155bce5233ca305e3ba2420cc

**Comment by sodabrew** [comment]
I'll put together a PR right now.
