### ISSUE TITLE
Opening too many sockets gives wrong error message (in Linux) or hangs (in OSX)

### ISSUE THREAD

**Issue by dubek** [eventmachine/eventmachine#136]
[ First discussed here: http://groups.google.com/group/eventmachine/browse_thread/thread/7eab4e5fa65e808 ]

If I try to open many connections at once, I'd sometime hit the OS limit of number of open files. The defaults are 256 on Mac OS X and 1024 on Linux.

However, I get the following behaviours:

1. On Linux: after I open all the allowed connections, next attempts to open a connection fail with the error `unable to resolve server address`. I'd expect a clearer error like `too many open file descriptors`.
2. On Mac OS X: after I open all the allowed connections, the process is hung. I haven't debugged it to see where (yet). Here I'd expect an error of course and not a hang.

The test program and the outputs on both systems are here: https://gist.github.com/714077

I'm using eventmachine 0.12.10 (I should try on the 1.0 beta, now that I think of it).

Aman: we should throw a more useful error when you hit this limit, and provide some details about how to increase the limit (ulimit, using EM.epoll/kqueue, etc).

**Comment by sodabrew** [comment]
The script doesn't fail for me on OS X, but the error should still be improved!
