### ISSUE TITLE
pending_connect_timeout throws NoMethodError on java reactor

### ISSUE THREAD

**Issue by igrigorik** [eventmachine/eventmachine#155]
Q1: Any plans to add inactivity / pending timeouts to java reactor? Timeout logic on JRuby for em-http is broken otherwise.

Q2: Inactivity timeout throws a warning, pending timeout blows up -- should probably make those consistent.

<pre>
jruby-1.5.5 :002 > EM.run { h = EM::HttpRequest.new('http://www.igvita.com/').get; h.callback { p h.response_header.status; EM.stop}}
SOCKET: SET COMM INACTIVITY UNIMPLEMENTED 10
NoMethodError: undefined method `set_pending_connect_timeout' for EventMachine:Module
</pre>

**Comment by respire** [comment]
hello, anybody know why this issue still exists? thanks!

**Comment by holinov** [comment]
SOCKET: SET COMM INACTIVITY UNIMPLEMENTED 10  is still happening!!!!!!
