### ISSUE TITLE
prefork mode support

### ISSUE THREAD

**Issue by williamwu0220** [eventmachine/eventmachine#178]
Currently EM does not support prefork mode directly, like Tornado framework: http://groups.google.com/group/python-tornado/browse_thread/thread/357e6637f881e9f0 .

It's a killing feature if we have "prefork mode" support.

**Comment by sodabrew** [comment]
Since #465 you can create a new reactor in a child with an existing fd, and since #425 / #455 forking inside a reactor is possible (and you can begin a new reactor in the child).
