### ISSUE TITLE
Using open_keyboard twice fails the second time

### ISSUE THREAD

**Issue by bschelberg** [eventmachine/eventmachine#183]
Running the following script, I expect it to ask me to press Enter twice, then end. It behaves as I expect the first time I press Enter, but then the second time it seems to no longer accept any input from the keyboard.

<pre>
#!/usr/bin/env ruby

require 'eventmachine'

class KeyboardHandler &lt; EventMachine::Connection
  def receive_data data
    EventMachine.stop_event_loop
  end
end

def check
  EventMachine.run do
    EventMachine.open_keyboard KeyboardHandler
    puts "Press Enter key to continue."
  end
end

check
check
</pre>

**Comment by sodabrew** [comment]
Resolved ages ago in 2cd0c19276edde3fb4c0af699fa8caa6b1f3923a
