### ISSUE TITLE
unable to install "eventmachine" both from gem and build

### ISSUE THREAD

**Issue by suryart** [eventmachine/eventmachine#186]
I am trying to install eventmachine by command: gem install eventmachine and it is giving me this error at the end:

make: shared: Command not found
make: [rubyeventmachine.so] Error 127 (ignored)
/usr/bin/install -c -m 0755 rubyeventmachine.so /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib
/usr/bin/install: cannot stat `rubyeventmachine.so': No such file or directory
make: **\* [/usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/rubyeventmachine.so] Error 1

you may review whole log here: http://pastie.org/private/ebiehjoa23klhec6hurmg

And when I tried to grab and build like this:

git clone git://github.com/eventmachine/eventmachine.git
  cd eventmachine
  rake build

at rake build it is prompting following error:

surya@surya-desktop:~/Desktop/Surya/Projects/eventmachine$ rake build
(in /home/surya/Desktop/Surya/Projects/eventmachine)
rake aborted!
Don't know how to build task 'build'

(See full trace by running task with --trace)
surya@surya-desktop:~/Desktop/Surya/Projects/eventmachine$ 

Can you kindly suggest me any possible way to solve this issue?

Thanks
Surya

**Comment by ScarletMcLearn** [comment]
Bump
