### ISSUE TITLE
EM.connect fails under IPv6

### ISSUE THREAD

**Issue by ibc** [eventmachine/eventmachine#189]
The following code:
<pre>
EM.run { EM.connect "2001:0:53aa:64c:38c3:4b25:2b19:d1a6", 5555, Handler }
</pre>
produces in tcpdump:
<pre>
IP6 2001:0:53aa:64c:38c3:4b25:2b19:d1a6.54649 > 2001:0:53aa:64c::.5555: Flags [S], seq 1331266254, win 4880, options [mss 1220,sackOK,TS val 2974426 ecr 0,nop,wscale 7], length 0
</pre>
but it should be (as netcat shows):
<pre>
IP6 2001:0:53aa:64c:38c3:4b25:2b19:d1a6.56315 > 2001:0:53aa:64c:38c3:4b25:2b19:d1a6.5555: Flags [S], seq 1670743798, win 32752, options [mss 16376,sackOK,TS val 2969307 ecr 0,nop,wscale 7], length 0
</pre>

`EM.connect` seems to corrupt the given IPv6 and doesn't connect to it.

**Comment by sodabrew** [comment]
Closing in favor of PR #570

**Comment by sodabrew** [comment]
This is partly resolved by #632 which will ship in EM 1.0.9 soon, and will be fully resolved by #630 to ship with EM 1.2.0.

**Comment by ioquatix** [comment]
nice
