### ISSUE TITLE
EM.open_datagram_socket fails under IPv6 => no datagram socket (RuntimeError)

### ISSUE THREAD

**Issue by ibc** [eventmachine/eventmachine#190]
My computer has IPv6 and I can open a EM server listening into IPv6, but trying to open an UDP socket on top of IPv6 raises an exception:
<pre>
EM.open_datagram_socket("::1", 8000, MyHandler) 

no datagram socket (RuntimeError)
/var/lib/gems/1.9.1/gems/eventmachine-1.0.0.beta.3/lib/eventmachine.rb:864:in
`open_udp_socket'
/var/lib/gems/1.9.1/gems/eventmachine-1.0.0.beta.3/lib/eventmachine.rb:864:in
`open_datagram_socket'
</pre>

Note that the following does work:
<pre>
EM.start_server("::1", 8000, MyHandler) 
</pre>

**Comment by sodabrew** [comment]
Closing in favor of PR #570

**Comment by sodabrew** [comment]
I'm tracking this in #630 now.
