### ISSUE TITLE
ssl_verify_peer() is called three times instead of just once

### ISSUE THREAD

**Issue by ibc** [eventmachine/eventmachine#194]
When the client provides a certificate during TLS negociation, in the EM server the method `ssl_verify_peer(cert)` is called 3
times with same cert as argument (exact the same). I've tested it using EM as client and also different external clients. The clients provided certificate is a single one.

My code in EM server is just:
<pre>
 def post_init
     start_tls({
       :private_key_file => "../test/ssl/key.pem",
       :cert_chain_file => "../test/ssl/cert.pem",
       :verify_peer => true})
   end

   def ssl_verify_peer cert
     log_debug "veryfying client certificate: #{cert.inspect}"
     true  # TODO: Inspect the cert and reply false when invalid.
   end

   def ssl_handshake_completed
     log_debug "ssl completed"
   end
</pre>

I see the log "veryfying client certificate: #{cert.inspect}" called three times (one each other) within the same TCP connection.

Using EM 1.0.0.beta.3.

**Comment by mcr** [comment]
ssl_verify_peer is still called three times.
setting verify_peer to false will cause the SSL library to not ask for the client certificate.
get_peer_cert (EventMachine::get_peer_cert @signature) seems to have broken in version 1.2.7.
