### ISSUE TITLE
failure of BufferedTokenizer when delimiter straddles successive data segments

### ISSUE THREAD

**Issue by christfo** [eventmachine/eventmachine#260]
say I use BufferedTokenizer with a delimiter of '

@buffer =BufferedTokenizer.new( '|MYDELIMITTOKEN|' )

in a recieve_data hook I stuff data into the buffer:

@buffer.extract_data( data ).each do |item| ..... 

It happens that I'm transferring substantial amounts of data around, well above the MTU of the network. Occasionally I'll get a pathological case where my delimiter gets split into two adjacent data buffers on transmit, eg

buffer#@input == [..............   \\u0000___binit__\\u0000___cinit__\\u0000\"],\"json_class\":\"GetFile\"}]|MYDELIMITTO",   "KEN|" ]

This stalls the conversation between my actors since the token is never found and the object never pops out of the input buffer.
I can fix it by doing an extra check in extract, but its kinda messy and does some heavyweight  dup.join.split action which would kill performance. I'm wondering if http://pastie.textmate.org/private/ykjtuipjedrwgzwgggu5w would be a safer stratergy?

**Comment by sodabrew** [comment]
This is resolved by #547 in eventmachine 1.0.6 and above.
