### ISSUE TITLE
Segmentation fault when opening many connections

### ISSUE THREAD

**Issue by noverloop** [eventmachine/eventmachine#268]
I wrote an evented process that pops a bunch of pages of a queue, and visits each of its links in eventmachine.
As I understand it, it should be able to process a large number of pages because it contains mostly non-blocking calls (I still have to switch to em-redis calls)

It uses ruby 1.9.2 and eventmachine-1.0.0.beta.4
The ulimit is set to 100000 and shouldn't be a problem.
It is deployed with rake if that's relevant.

/home/ubuntu/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179: [BUG] Segmentation fault
ruby 1.9.2p290 (2011-07-09 revision 32553) [i686-linux]

-- control frame ----------
c:0028 p:---- s:0093 b:0093 l:000092 d:000092 CFUNC  :run_machine
c:0027 p:0248 s:0090 b:0090 l:000089 d:000089 METHOD /home/ubuntu/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179
c:0026 p:0017 s:0083 b:0083 l:00037c d:00037c METHOD /home/ubuntu/marketfu/lib/redis_crawler/hydra_processor.rb:107
c:0025 p:0045 s:0080 b:0080 l:001c24 d:000079 BLOCK  /home/ubuntu/marketfu/lib/tasks/redis_crawler_launcher.rake:62
c:0024 p:---- s:0077 b:0077 l:000076 d:000076 FINISH
c:0023 p:---- s:0075 b:0075 l:000074 d:000074 CFUNC  :call
c:0022 p:0043 s:0070 b:0070 l:000061 d:000069 BLOCK  /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:634
c:0021 p:---- s:0067 b:0067 l:000066 d:000066 FINISH
c:0020 p:---- s:0065 b:0065 l:000064 d:000064 CFUNC  :each
c:0019 p:0171 s:0062 b:0062 l:000061 d:000061 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:629
c:0018 p:0110 s:0058 b:0058 l:000052 d:000057 BLOCK  /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:595
c:0017 p:0019 s:0056 b:0056 l:000055 d:000055 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201
c:0016 p:0033 s:0053 b:0053 l:000052 d:000052 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:588
c:0015 p:0048 s:0047 b:0047 l:000046 d:000046 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:581
c:0014 p:0045 s:0042 b:0042 l:000041 d:000041 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2041
c:0013 p:0012 s:0035 b:0035 l:000020 d:000034 BLOCK  /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2019
c:0012 p:---- s:0032 b:0032 l:000031 d:000031 FINISH
c:0011 p:---- s:0030 b:0030 l:000029 d:000029 CFUNC  :each
c:0010 p:0069 s:0027 b:0027 l:000020 d:000026 BLOCK  /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2019
c:0009 p:0009 s:0025 b:0025 l:000024 d:000024 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2058
c:0008 p:0011 s:0021 b:0021 l:000020 d:000020 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2013
c:0007 p:0031 s:0018 b:0018 l:000017 d:000017 METHOD /home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:1992
c:0006 p:0036 s:0015 b:0015 l:000014 d:000014 TOP    /home/ubuntu/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.8.7/bin/rake:31
c:0005 p:---- s:0013 b:0013 l:000012 d:000012 FINISH
c:0004 p:---- s:0011 b:0011 l:000010 d:000010 CFUNC  :load
c:0003 p:0127 s:0007 b:0007 l:0006c4 d:0015e8 EVAL   /home/ubuntu/.rvm/gems/ruby-1.9.2-p290/bin/rake:19
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0006c4 d:0006c4 TOP   
---------------------------
-- Ruby level backtrace information ----------------------------------------
/home/ubuntu/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `<main>'
/home/ubuntu/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `load'
/home/ubuntu/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:1992:in `run'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2013:in `top_level'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2019:in `block in top_level'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2019:in `each'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2019:in `block (2 levels) in top_level'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:2041:in `invoke_task'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:581:in `invoke'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:629:in `execute'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:629:in `each'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/rake.rb:634:in `call'
/home/ubuntu/marketfu/lib/tasks/redis_crawler_launcher.rake:62:in `block (2 levels) in <top (required)>'
/home/ubuntu/marketfu/lib/redis_crawler/hydra_processor.rb:107:in `run'
/home/ubuntu/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in `run'
/home/ubuntu/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in `run_machine'

-- C level backtrace information -------------------------------------------
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/libruby.so.1.9(rb_vm_bugreport+0x72) [0xb7788702]
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/libruby.so.1.9(+0x53c57) [0xb7651c57]
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/libruby.so.1.9(rb_bug+0x3a) [0xb76529ba]
/home/ubuntu/.rvm/rubies/ruby-1.9.2-p290/lib/libruby.so.1.9(+0x1142dc) [0xb77122dc]
[0xb77ff40c]

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Aborted

**Comment by sodabrew** [comment]
This is resolved by #502, available in eventmachine 1.0.5 and above.
