### ISSUE TITLE
EM limited to 256 file descriptors in windows (from Trac)

### ISSUE THREAD

**Issue by jakedouglas** [eventmachine/eventmachine#3]
Moved from Trac
=============

10/08/08 12:53:42 changed by rogerdpack 

IOCP overcomes it as well [though apparently it's hard to use IOCP as evented--it is possible--google "libevent IOCP"
12/03/08 09:51:18 changed by rogerdpack

the 256 limit may be caused by the use of msvcrt6 in the back.

Apparently possible to overcome by redefining FD_SETSIZE to be large.

**Comment by sodabrew** [comment]
Closing for housekeeping. This was resolved some time ago.
