### ISSUE TITLE
Deploying gem updates for all platforms on rubygems

### ISSUE THREAD

**Issue by tjoyal** [eventmachine/eventmachine#305]
This is not as much an issue on your side as it is with the general developpement dependency current way to do stuff.

I have a project that I develop on unix and for a particular installation I need to deploy it on windows.

Since 1.0.0.beta.4 dosent seems to work on windows(seg faults) and it seems to be fixed with 1.0.0.beta.4.1, I decided to use the last.

My problem is that 1.0.0.beta.4.1 havent been released as a gem for ruby (or I might simply be doing something wrong). 

I end up with some nasty patching like :

```ruby
# fun fun windows dependency problem
if %w(x86_64-linux).include?(ENV['MY_BUNDLE_ENV'] || RUBY_PLATFORM)
  #linux
  gem 'eventmachine', '1.0.0.beta.4'
else
  #windows
  gem 'eventmachine', '1.0.0.beta.4.1'
end
```

Would it be possible to release gem updates for every platform? Not sure if I'm asking something that I shouldn't, simply seems something that would help me a lot :)

thanks

**Comment by sodabrew** [comment]
Windows build situation be vastly improved by #578.
