### ISSUE TITLE
get_sockname not defined

### ISSUE THREAD

**Issue by danielrjackson** [eventmachine/eventmachine#308]
In eventmachine-1.0.0.beta.4-java a call to EventMachine::Conection.get_sockname produces an undefined method error when it tries to call "EventMachine::get_sockname @signature".  The method does not appear to be defined in the EventMachine module. This error also exists in eventmachine-1.0.0.beta.3-java.

Error output (slightly modified to remove implementation specifics):

undefined method `get_sockname' for EventMachine:Module
["~/.rvm/gems/jruby-1.6.7/gems/eventmachine-1.0.0.beta.4-java/lib/em/connection.rb:553:in`get_sockname'",
 ...
 "~/.rvm/gems/jruby-1.6.7/gems/eventmachine-1.0.0.beta.4-java/lib/eventmachine.rb:1425:in `event_callback'",
 "~/.rvm/gems/jruby-1.6.7/gems/eventmachine-1.0.0.beta.4-java/lib/jeventmachine.rb:92:in`eventCallback'",
 "~/.rvm/gems/jruby-1.6.7/gems/eventmachine-1.0.0.beta.4-java/lib/jeventmachine.rb:111:in `run_machine'",
 "~/.rvm/gems/jruby-1.6.7/gems/eventmachine-1.0.0.beta.4-java/lib/eventmachine.rb:179:in`run'",
 ...]

Environment:
Fedora 14
jruby 1.6.7 (ruby-1.9.2-p312) (2012-02-22 3e82bc8) (OpenJDK 64-Bit Server VM 1.6.0_20) [linux-amd64-java]

**Comment by majioa** [comment]
Also did not find out for me:

    undefined method `get_sockname' for EventMachine:Module
    Did you mean?  get_sock_opt (NoMethodError)

versions are:
* ruby 2.3.0
* eventmachine 1.0.9.1

**Comment by sodabrew** [comment]
I see that this function is missing from the pure Ruby implementation. I will schedule a fix-release for it.

**Comment by majioa** [comment]
@sodabrew yes, thanx, I saw it already too =)
