### ISSUE TITLE
eventmachine-0.12.10 fails to build c++ on solaris 11

### ISSUE THREAD

**Issue by jbcraig** [eventmachine/eventmachine#313]
I'm using ruby 1.9.3p0 as packaged by OpenCSW on a Solaris 11 host using solarisstudio12.3 compiler.  When i run "gem install eventmachine" it blows up with:

make
compiling rubymain.cpp
"rubymain.cpp", line 164: Warning (Anachronism): Formal argument 1 of type extern "C" unsigned long(*)(...) in call to rb_rescue(extern "C" unsigned long(*)(...), unsigned long, extern "C" unsigned long(*)(...), unsigned long) is being passed unsigned long(*)(...).
"rubymain.cpp", line 164: Warning (Anachronism): Formal argument 3 of type extern "C" unsigned long(*)(...) in call to rb_rescue(extern "C" unsigned long(*)(...), unsigned long, extern "C" unsigned long(*)(...), unsigned long) is being passed unsigned long(*)(...).
"rubymain.cpp", line 173: Warning (Anachronism): Formal argument 1 of type extern "C" void(*)(const unsigned long,int,const char*,const unsigned long) in call to evma_initialize_library(extern "C" void(*)(const unsigned long,int,const char*,const unsigned long)) is being passed void(*)(const unsigned long,int,const char*,const unsigned long).
3 Warning(s) detected.
compiling cplusplus.cpp
"cplusplus.cpp", line 37: Warning (Anachronism): Formal argument 1 of type extern "C" void(*)(const unsigned long,int,const char*,const unsigned long) in call to evma_initialize_library(extern "C" void(*)(const unsigned long,int,const char*,const unsigned long)) is being passed void(*)(const unsigned long,int,const char*,const unsigned long).
"cplusplus.cpp", line 82: Error: Could not find a match for std::map<unsigned long,EM::Eventable*>::insert(std::pair<unsigned long, EM::Connection*>) needed in EM::Acceptor::Accept(const unsigned long).
"cplusplus.cpp", line 128: Error: Could not find a match for std::map<unsigned long,EM::Eventable*>::insert(std::pair<unsigned long, EM::Connection*>) needed in EM::Connection::BindConnect(const char*, int, const char*, int).
"cplusplus.cpp", line 151: Error: Could not find a match for std::map<unsigned long,EM::Eventable*>::insert(std::pair<unsigned long, EM::Acceptor*>) needed in EM::Acceptor::Start(const char*, int).
3 Error(s) and 1 Warning(s) detected.
make: *** [cplusplus.o] Error 2

If I rework the Makefile and force the use of g++ the code builds so I'm assuming its a portability issue between g++ and the Sun CC compiler.  I am an administrator have little to no skills in c++ or ruby.  Is this a lost cause and should therefore tell my developer its a no go?

**Comment by sodabrew** [comment]
Can this issue be closed now?

**Comment by sodabrew** [comment]
I set up a Solaris 11.2 VM and eventmachine 1.0.4 compiled without incident. Closing as resolved.
