### ISSUE TITLE
Concurrency issue between CleanupSockets and AttachFD

### ISSUE THREAD

**Issue by franzk** [eventmachine/eventmachine#354]
The issue is about the Descriptors vector. During operation, CleanupSockets may free the memory where a member of Descriptors points to, so the Descriptors vector contains an invalid pointer for a short time period.

Now I am experiencing the situation that during this small window of time, another thread executes AttachFD. In rare cases, as the invalid pointers of Descriptors may point to "random" data, this random data equals to the FD which is going to be attached - and "adding existing descriptor" is being thrown, but it's a false positive.

This sounds a bit theoretically, but I have an application running which attaches and detaches a lot of file descriptors - and it constantly gets into the described situation :-)

**Comment by sodabrew** [comment]
EventMachine 1.2.3 now has a fix for the window of indeterminate descriptors that you're seeing in your `unbind` callback (four and a half years later, but better late than never, right?).
