### ISSUE TITLE
crash on client connect on Win64 ruby 1.9.3 (grape-goliath-example); works fine on OS X

### ISSUE THREAD

**Issue by sensiblearts** [eventmachine/eventmachine#383]
I am running on Windows 7 64bit, ruby 1.9.3-p286, trying to run this code https://github.com/4eek/grape-goliath-example ; it works great on Mac, but fails on Win64. It has this Gemfile:

gem 'pg'
gem 'em-postgresql-adapter', :git => 'git://github.com/leftbee/em-postgresql-adapter.git'
gem 'rack-fiber_pool', :require => 'rack/fiber_pool'
gem 'em-synchrony', :git => 'git://github.com/igrigorik/em-synchrony.git',
:require => ['em-synchrony', 'em-synchrony/activerecord']
gem 'grape'
gem 'goliath'

and I am getting this error from an eventmachine C++ header when an http client connects;

$ ruby server.rb -vs
[2220:INFO] 2012-11-14 08:17:26 :: Starting server on 0.0.0.0:9000 in developmen
t mode. Watch out for stones.
terminate called after throwing an instance of 'std::runtime_error'
what(): cannot close 'watch only' connections

How I should proceed to define it better? Thanks.

**Comment by sodabrew** [comment]
The message `cannot close 'watch only' connections` is still in the codebase; it's not clear if triggering that is due to a bug in EM or in your client code, which unfortunately is no longer posted. Please feel free to reopen if this remains an open issue.
