### ISSUE TITLE
thin server crashes after idle in development mode of RoR

### ISSUE THREAD

**Issue by cpanderson** [eventmachine/eventmachine#386]
Recently, after opening up my macbook from sleep I'll go and try to load my development environment in my web browser and it's not responding. When I got back to the thin server console it shows...

libc++abi.dylib: terminate called throwing an exception

..and has exited the process. 

Running...

Mac OS: 10.8.2
Rails: 3.0.17
Event Machine: 1.0
Thin Server: 1.3.1

I have been running the above for quite some time and only recently have been encountering the error. I'm suspecting either bundle update or perhaps an iOS XCode update has bungled things, but am posting this here to see if anyone has encountered this issue.

Thanks

Here's what it throws in the mac console...

Process:         ruby [35286]
Path:            /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Identifier:      ruby
Version:         83.4
Code Type:       X86-64 (Native)
Parent Process:  bash [4756]
User ID:         501

PlugIn Path:       /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0/lib/rubyeventmachine.bundle
PlugIn Identifier: rubyeventmachine.bundle
PlugIn Version:    ??? (0)

Date/Time:       2012-11-23 11:40:32.456 -0800
OS Version:      Mac OS X 10.8.2 (12C60)
Report Version:  10
Sleep/Wake UUID: AFD8188E-A040-425A-816C-D53CA2704350

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called
terminate called throwing an exception

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8b583212 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff8f3c2af4 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff8f406dce abort + 143
3   libc++abi.dylib               	0x00007fff91df9a17 abort_message + 257
4   libc++abi.dylib               	0x00007fff91df73c6 default_terminate() + 28
5   libobjc.A.dylib               	0x00007fff8b469887 _objc_terminate() + 111
6   libc++abi.dylib               	0x00007fff91df73f5 safe_handler_caller(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff91df7450 std::terminate() + 16
8   libc++abi.dylib               	0x00007fff91df85b7 __cxa_throw + 111
9   rubyeventmachine.bundle       	0x00000001076727a3 EventMachine_t::_RunSelectOnce() + 663
10  rubyeventmachine.bundle       	0x0000000107672143 EventMachine_t::_RunOnce() + 45
11  rubyeventmachine.bundle       	0x0000000107671dec EventMachine_t::Run() + 464
12  rubyeventmachine.bundle       	0x0000000107678a4a t_run_machine_without_threads(unsigned long) + 9
13  libruby.1.dylib               	0x00000001062565f9 0x106231000 + 153081
14  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
15  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
16  libruby.1.dylib               	0x0000000106258a43 0x106231000 + 162371
17  libruby.1.dylib               	0x0000000106256afb 0x106231000 + 154363
18  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
19  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
20  libruby.1.dylib               	0x000000010625b805 0x106231000 + 174085
21  libruby.1.dylib               	0x0000000106259a39 0x106231000 + 166457
22  libruby.1.dylib               	0x0000000106256afb 0x106231000 + 154363
23  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
24  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
25  libruby.1.dylib               	0x0000000106256afb 0x106231000 + 154363
26  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
27  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
28  libruby.1.dylib               	0x0000000106256afb 0x106231000 + 154363
29  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
30  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
31  libruby.1.dylib               	0x0000000106256afb 0x106231000 + 154363
32  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
33  libruby.1.dylib               	0x000000010624b33c rb_call_super + 185
34  libruby.1.dylib               	0x0000000106259732 0x106231000 + 165682
35  libruby.1.dylib               	0x0000000106258a43 0x106231000 + 162371
36  libruby.1.dylib               	0x0000000106256afb 0x106231000 + 154363
37  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
38  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
39  libruby.1.dylib               	0x000000010624a086 0x106231000 + 102534
40  libruby.1.dylib               	0x00000001062793e3 rb_obj_tap + 17
41  libruby.1.dylib               	0x00000001062565f9 0x106231000 + 153081
42  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
43  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
44  libruby.1.dylib               	0x0000000106259c4c 0x106231000 + 166988
45  libruby.1.dylib               	0x000000010624be89 rb_load + 1024
46  libruby.1.dylib               	0x000000010624c665 rb_require_safe + 383
47  libruby.1.dylib               	0x00000001062565f9 0x106231000 + 153081
48  libruby.1.dylib               	0x000000010624af7a 0x106231000 + 106362
49  libruby.1.dylib               	0x00000001062594ad 0x106231000 + 165037
50  libruby.1.dylib               	0x000000010625dc37 0x106231000 + 183351
51  libruby.1.dylib               	0x00000001062479af ruby_run + 34
52  ruby                          	0x000000010622bf1d main + 45
53  libdyld.dylib                 	0x00007fff8f5207e1 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff8b583386 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff8f44b800 nanosleep + 163
2   libruby.1.dylib               	0x00000001062559bb 0x106231000 + 149947
3   libsystem_c.dylib             	0x00007fff8f3c1742 _pthread_start + 327
4   libsystem_c.dylib             	0x00007fff8f3ae181 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff599c9fb8  rdx: 0x0000000000000000
  rdi: 0x0000000000001307  rsi: 0x0000000000000006  rbp: 0x00007fff599c9fe0  rsp: 0x00007fff599c9fb8
   r8: 0x00007fff79ec4278   r9: 0x0000000000000008  r10: 0x0000000020000000  r11: 0x0000000000000206
  r12: 0x00007fff599ca140  r13: 0x0000000000000007  r14: 0x00007fff79ec5180  r15: 0x00007fff599ca020
  rip: 0x00007fff8b583212  rfl: 0x0000000000000206  cr2: 0x00007fff79ebdfe8
Logical CPU: 0

Binary Images:
       0x10622b000 -        0x10622bfff  ruby (83.4) <294ECA8A-C1FA-303D-966F-2AD3D99F3309> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
       0x106231000 -        0x1062f0ff7  libruby.1.dylib (83.4) <AA7BD261-598C-3B22-9644-8389470A2E15> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/libruby.1.dylib
       0x1063b7000 -        0x1063b9fff  thread.bundle (83.4) <C614C177-3A53-341A-A2C6-3CA28D031F17> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/thread.bundle
       0x1063ee000 -        0x1063effff  etc.bundle (83.4) <47FE8A52-342C-33F4-83B7-B79D361FCFDA> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/etc.bundle
       0x10681b000 -        0x10681efff  stringio.bundle (83.4) <22973F08-4708-3AF8-B084-72DD75A877C3> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/stringio.bundle
       0x106823000 -        0x106837fff  syck.bundle (83.4) <33EA60B1-C001-376F-8219-7327C3C77F50> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/syck.bundle
       0x10683f000 -        0x10683ffff  sha1.bundle (83.4) <38252515-8AB2-358A-8D8F-686F33086151> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/digest/sha1.bundle
       0x106843000 -        0x106844ff7  digest.bundle (83.4) <EFA9A989-C6F1-3EB8-96C9-0F11BE2B935E> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/digest.bundle
       0x106c4b000 -        0x106c51fff  zlib.bundle (83.4) <18E9FD2D-CF76-328A-9742-E09C067AE87A> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/zlib.bundle
       0x106c56000 -        0x106c87ff7  openssl.bundle (83.4) <029B33EA-1DC1-36F2-A4E9-FD4217AED016> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/openssl.bundle
       0x106c9d000 -        0x106c9dfff  fcntl.bundle (83.4) <0A2407EF-06AE-386E-8638-489BDB8CD037> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/fcntl.bundle
       0x106ca1000 -        0x106caafff  socket.bundle (83.4) <846AF72A-284C-385B-AA4B-FD9A2C0F1897> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/socket.bundle
       0x106cb0000 -        0x106cb0fff  md5.bundle (83.4) <050ECB44-0965-3163-88F6-BBD5DCF5C063> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/digest/md5.bundle
       0x106cb4000 -        0x106cb6fff  strscan.bundle (83.4) <91191351-4FAD-35B7-9E12-518FF35F0285> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/strscan.bundle
       0x106cbb000 -        0x106cc3fff  bigdecimal.bundle (83.4) <C0BFAA42-5EB6-36BA-8CB4-67FA42EE2EBE> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/bigdecimal.bundle
       0x1073fe000 -        0x107402fff +mysql2.bundle (0) <CF95A7DB-6AC0-333B-9D12-76D501D267A1> /Library/Ruby/Gems/1.8/gems/mysql2-0.2.18/lib/mysql2/mysql2.bundle
       0x107408000 -        0x107580ff7 +libmysqlclient_r.16.dylib (17) <76213546-B1AE-BEF7-E9A2-E9D6AE0B304B> /usr/local/mysql/lib/libmysqlclient_r.16.dylib
       0x10766b000 -        0x107684fff +rubyeventmachine.bundle (0) <B0428308-1C10-326F-B729-9576AF91753A> /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0/lib/rubyeventmachine.bundle
       0x1076a7000 -        0x1076aafff +thin_parser.bundle (???) <F5635605-5235-3A26-9950-065C163B54A6> /Users/USER/*/thin_parser.bundle
       0x1076af000 -        0x1076ccfff +libxml_ruby.bundle (0) <990CBB0E-89E0-3EB4-BD15-B3D0E8714847> /Library/Ruby/Gems/1.8/gems/libxml-ruby-1.1.4/lib/libxml_ruby.bundle
       0x1076e4000 -        0x1076e6fff  iconv.bundle (83.4) <B42D0DFC-116A-33F9-87B9-F77D4AE6958F> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/iconv.bundle
       0x1076eb000 -        0x107717fff  nkf.bundle (83.4) <4B370671-11E1-3EBD-9131-068151098AC6> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/nkf.bundle
       0x108421000 -        0x108424fff +parser.bundle (0) <9CF0B2B1-ED6A-3DA0-AB79-3C44DF7471CA> /Library/Ruby/Gems/1.8/gems/json-1.7.5/lib/json/ext/parser.bundle
       0x108428000 -        0x10842eff7 +generator.bundle (0) <9A8ABE73-408B-31C6-8230-0907F85EF605> /Library/Ruby/Gems/1.8/gems/json-1.7.5/lib/json/ext/generator.bundle
       0x109b8f000 -        0x109b91fff  cparse.bundle (83.4) <E72BB5CA-6070-31F5-816C-B2DC139731AC> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0/racc/cparse.bundle
    0x7fff65e2b000 -     0x7fff65e5f93f  dyld (210.2.3) <A40597AA-5529-3337-8C09-D8A014EB1578> /usr/lib/dyld
    0x7fff893f3000 -     0x7fff89429fff  libsystem_info.dylib (406.17) <4FFCA242-7F04-365F-87A6-D4EFB89503C1> /usr/lib/system/libsystem_info.dylib
    0x7fff89458000 -     0x7fff89459ff7  libdnsinfo.dylib (453.18) <E7595861-ECF9-336E-9901-BED2620FAA80> /usr/lib/system/libdnsinfo.dylib
    0x7fff89470000 -     0x7fff89472fff  libquarantine.dylib (52) <4BE2E642-A14F-340A-B482-5BD2AEFD9C24> /usr/lib/system/libquarantine.dylib
    0x7fff89473000 -     0x7fff89485ff7  libz.1.dylib (43) <2A1551E8-A272-3DE5-B692-955974FE1416> /usr/lib/libz.1.dylib
    0x7fff894c9000 -     0x7fff894cbff7  libunc.dylib (25) <92805328-CD36-34FF-9436-571AB0485072> /usr/lib/system/libunc.dylib
    0x7fff89750000 -     0x7fff89751ff7  libSystem.B.dylib (169.3) <365477AB-D641-389D-B8F4-A1FAE9657EEE> /usr/lib/libSystem.B.dylib
    0x7fff8ab1f000 -     0x7fff8ad1ffff  libicucore.A.dylib (491.11.1) <CC318A27-878A-38CE-9292-1B98353FA9C7> /usr/lib/libicucore.A.dylib
    0x7fff8b458000 -     0x7fff8b57092f  libobjc.A.dylib (532.2) <90D31928-F48D-3E37-874F-220A51FD9E37> /usr/lib/libobjc.A.dylib
    0x7fff8b571000 -     0x7fff8b58cff7  libsystem_kernel.dylib (2050.18.24) <C0535565-35D1-31A7-A744-63D9F10F12A4> /usr/lib/system/libsystem_kernel.dylib
    0x7fff8be8b000 -     0x7fff8bf8dfff  libcrypto.0.9.8.dylib (47) <74F165AD-4572-3B26-B0E2-A97477FE59D0> /usr/lib/libcrypto.0.9.8.dylib
    0x7fff8d168000 -     0x7fff8d170fff  liblaunch.dylib (442.26.2) <2F71CAF8-6524-329E-AC56-C506658B4C0C> /usr/lib/system/liblaunch.dylib
    0x7fff8d64a000 -     0x7fff8d64bff7  libsystem_sandbox.dylib (220) <3C3B03CF-C525-3CB3-8557-62E91B93AC95> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8e4d4000 -     0x7fff8e4dbfff  libcopyfile.dylib (89) <876573D0-E907-3566-A108-577EAD1B6182> /usr/lib/system/libcopyfile.dylib
    0x7fff8e4e2000 -     0x7fff8e4e3fff  libsystem_blocks.dylib (59) <D92DCBC3-541C-37BD-AADE-ACC75A0C59C8> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8e523000 -     0x7fff8e525fff  com.apple.TrustEvaluationAgent (2.0 - 23) <A97D348B-32BF-3E52-8DF2-59BFAD21E1A3> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff8e84d000 -     0x7fff8e86fff7  libxpc.dylib (140.41) <FAC04D8B-680E-325F-8F0C-DD69859D0E01> /usr/lib/system/libxpc.dylib
    0x7fff8e8e0000 -     0x7fff8e917ff7  libssl.0.9.8.dylib (47) <923945E6-C489-3406-903B-A362410753F8> /usr/lib/libssl.0.9.8.dylib
    0x7fff8f3ad000 -     0x7fff8f479fe7  libsystem_c.dylib (825.25) <8CBCF9B9-EBB7-365E-A3FF-2F3850763C6B> /usr/lib/system/libsystem_c.dylib
    0x7fff8f4b5000 -     0x7fff8f504ff7  libcorecrypto.dylib (106.2) <CE0C29A3-C420-339B-ADAA-52F4683233CC> /usr/lib/system/libcorecrypto.dylib
    0x7fff8f51e000 -     0x7fff8f521ff7  libdyld.dylib (210.2.3) <F59367C9-C110-382B-A695-9035A6DD387E> /usr/lib/system/libdyld.dylib
    0x7fff9031c000 -     0x7fff9032afff  libcommonCrypto.dylib (60026) <2D6537F5-1B5E-305C-A1CF-D1FA80CA3939> /usr/lib/system/libcommonCrypto.dylib
    0x7fff91294000 -     0x7fff9129ffff  libsystem_notify.dylib (98.5) <C49275CC-835A-3207-AFBA-8C01374927B6> /usr/lib/system/libsystem_notify.dylib
    0x7fff913e8000 -     0x7fff913fdff7  libdispatch.dylib (228.23) <D26996BF-FC57-39EB-8829-F63585561E09> /usr/lib/system/libdispatch.dylib
    0x7fff919b4000 -     0x7fff919b9fff  libcompiler_rt.dylib (30) <08F8731D-5961-39F1-AD00-4590321D24A9> /usr/lib/system/libcompiler_rt.dylib
    0x7fff91df6000 -     0x7fff91e1bff7  libc++abi.dylib (24.4) <E7BD9363-1D25-3551-A68A-2E2FF6ABECD7> /usr/lib/libc++abi.dylib
    0x7fff91ed9000 -     0x7fff91f07ff7  libsystem_m.dylib (3022.6) <B434BE5C-25AB-3EBD-BAA7-5304B34E3441> /usr/lib/system/libsystem_m.dylib
    0x7fff922ef000 -     0x7fff922fdff7  libsystem_network.dylib (77.10) <0D99F24E-56FE-380F-B81B-4A4C630EE587> /usr/lib/system/libsystem_network.dylib
    0x7fff92308000 -     0x7fff923fdfff  libiconv.2.dylib (34) <FEE8B996-EB44-37FA-B96E-D379664DEFE1> /usr/lib/libiconv.2.dylib
    0x7fff93f84000 -     0x7fff93f8aff7  libunwind.dylib (35.1) <21703D36-2DAB-3D8B-8442-EAAB23C060D3> /usr/lib/system/libunwind.dylib
    0x7fff93fcb000 -     0x7fff93fcbfff  libkeymgr.dylib (25) <CC9E3394-BE16-397F-926B-E579B60EE429> /usr/lib/system/libkeymgr.dylib
    0x7fff93fcc000 -     0x7fff93fd2fff  libmacho.dylib (829) <BF332AD9-E89F-387E-92A4-6E1AB74BD4D9> /usr/lib/system/libmacho.dylib
    0x7fff942d0000 -     0x7fff942d1ff7  libremovefile.dylib (23.1) <DBBFAF35-AC78-3856-92F6-6E4FD9DF14A2> /usr/lib/system/libremovefile.dylib
    0x7fff94ca3000 -     0x7fff94ca8fff  libcache.dylib (57) <65187C6E-3FBF-3EB8-A1AA-389445E2984D> /usr/lib/system/libcache.dylib
    0x7fff94ce7000 -     0x7fff94de4ff7  libxml2.2.dylib (22.3) <47B09CB2-C636-3024-8B55-6040F7829B4C> /usr/lib/libxml2.2.dylib
    0x7fff95b08000 -     0x7fff95b70ff7  libc++.1.dylib (65.1) <20E31B90-19B9-3C2A-A9EB-474E08F9FE05> /usr/lib/libc++.1.dylib
    0x7fff95bc2000 -     0x7fff95bcaff7  libsystem_dnssd.dylib (379.32.1) <62AA0B84-188A-348B-8F9E-3E2DB08DB93C> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff95c5d000 -     0x7fff95ca9ff7  libauto.dylib (185.1) <73CDC482-16E3-3FC7-9BB4-FBA2DA44DBC2> /usr/lib/libauto.dylib
    0x7fff95fff000 -     0x7fff96068fff  libstdc++.6.dylib (56) <EAA2B53E-EADE-39CF-A0EF-FB9D4940672A> /usr/lib/libstdc++.6.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 26895
    thread_create: 1
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=67.7M resident=27.5M(41%) swapped_out_or_unallocated=40.3M(59%)
Writable regions: Total=216.5M written=176.1M(81%) resident=189.4M(87%) swapped_out=0K(0%) unallocated=27.1M(13%)
 
REGION TYPE                      VIRTUAL
===========                      =======
MALLOC                            207.5M
MALLOC guard page                    32K
STACK GUARD                        56.0M
Stack                              8712K
VM_ALLOCATE                           4K
__DATA                             1472K
__LINKEDIT                         54.4M
__TEXT                             13.3M
shared memory                        12K
===========                      =======
TOTAL                             341.3M

**Comment by sodabrew** [comment]
Closing for lack of updates.
