### ISSUE TITLE
TLS not working properly

### ISSUE THREAD

**Issue by gucki** [eventmachine/eventmachine#388]
I'm trying to build a ftps server and so far everything works, except encryption of the data channel (encryption of the control channel works fine). I'm using filezilla as ftp client and it always complains about a gnutls error. Here's the trace:

    Trace:  CTransferSocket::OnAccept(0)
    Trace:  CTransferSocket::OnConnect
    Trace:  CTlsSocket::Handshake()
    Trace:  gnutls_session_get_data on primary socket failed: -51
    Trace:  CTlsSocket::ContinueHandshake()
    Trace:  CTlsSocket::OnSend()
    Trace:  CTlsSocket::OnRead()
    Trace:  CTlsSocket::ContinueHandshake()
    Trace:  CTlsSocket::Failure(-19, 103)
    Error:  GnuTLS error -19: An unexpected TLS-Handshake-Paket was received.
    Trace:  CTransferSocket::OnClose(103)
    Error:  Transfer connection interrupted: ECONNABORTED - Connection aborted
    Trace:  CTransferSocket::TransferEnd(3)
    Trace:  CFtpControlSocket::TransferEnd()
    Error:  Connection timed out
    Trace:  CControlSocket::DoClose(2050)
    Trace:  CFtpControlSocket::ResetOperation(2114)
    Trace:  CControlSocket::ResetOperation(2114)
    Trace:  CFtpControlSocket::ResetOperation(2114)
    Trace:  CControlSocket::ResetOperation(2114)
    Error:  Failed to retrieve directory listing
    Trace:  CFileZillaEnginePrivate::ResetOperation(2114)

This is how I try to connect to the data channel (active mode, so the client is listening for an incomming connection):

    EventMachine::run do
      c = EventMachine.connect("127.0.0.1", 52478)
      c.start_tls
    end

When removing the call to `start_tls` the output in filezilla is only:

    Trace:  CTransferSocket::OnAccept(0)
    Trace:  CTransferSocket::OnConnect
    Trace:  CTlsSocket::Handshake()
    Trace:  gnutls_session_get_data on primary socket failed: -51
    Trace:  CTlsSocket::ContinueHandshake()
    Trace:  CTlsSocket::OnSend()
    Trace:  CTlsSocket::OnSend()

I doubt that filezilla is buggy as I tried the version from ubuntu 12.10 and the official latest one for windows. Both fail with exactly the same error.

**Comment by sodabrew** [comment]
This should be working since EventMachine 1.2, which has merged back the major work from EventMachine-LE. Please feel free to reopen if needed though.
