### ISSUE TITLE
amqp gem not working with eventmachine-java

### ISSUE THREAD

**Issue by muskelbiber** [eventmachine/eventmachine#400]
AMQP messages are not correctly sent if the amqp gem is used under jRuby.
The problem was already reported here: 
https://github.com/tmm1/amqp/issues/16

It can be tested with the following code:

``` ruby
require "rubygems"
require "amqp"

@exchange
@connected=false
@connection
@queue

t = Thread.new{
  EventMachine.run do
    @connection = AMQP.connect(:host => '127.0.0.1')
    channel = AMQP::Channel.new(@connection)
    @queue = channel.queue("test.amqp", :exclusive => false)
    @exchange = channel.direct("")

    @queue.subscribe do |payload|
      puts "Received a message."
    end
    @connected=true
  end
}

while(!@connected)
end

@exchange.publish "foo", :routing_key => @queue.name
a = gets
@exchange.publish "bar", :routing_key => @queue.name
a = gets
@connection.close { EventMachine.stop }
```

The first message is sent fine, but not the second. The problem is, that the EmReactor blocks in mySelector.select(timeout) in the checkIO method after the first send.

In version 0.12.6 of eventmachine-java timeout is set to timerQuantum. With that version the code is executed as desired.

**Comment by sodabrew** [comment]
https://github.com/ruby-amqp/amqp is significantly updated since this bug was filed.
