### ISSUE TITLE
EM::DNS::Resolver.socket() fails if /etc/hosts contains "invalid byte sequence in US-ASCII"

### ISSUE THREAD

**Issue by ibc** [eventmachine/eventmachine#404]
In my /etc/hosts there is a comment (#) which contains a "ñ" symbol, so `EM::DNS::Resolver.socket()` fails in:

```
IO.readlines('/etc/hosts').each do |line|
  next if line =~ /^#/
```

A regular expression cannot contain multibyte symbols.

**Comment by sodabrew** [comment]
Closing, as I cannot reproduce this on my system (Mac OS X, Ruby 2.0).
