### ISSUE TITLE
pid_t redefined in project.h

### ISSUE THREAD

**Issue by sroller** [eventmachine/eventmachine#408]
project.h:90:
the
```C
typedef int pid_t;
```
causes a compiler error.
the type is already defined in sys/types.h
```
typedef _pid_t pid_t;
```
I commented the line out. Compile went through with a ton of warnings.
Unit tests caused a segfault.

platform: Windows 64bit, Ruby 2.0.0p0, gcc 4.7.2 (rubyinstaller/devkit)

**Comment by sodabrew** [comment]
This was fixed in Eventmachine 1.0.4.
