### ISSUE TITLE
How to stop timer when request is cancelled?

### ISSUE THREAD

**Issue by Zhomart** [eventmachine/eventmachine#417]
I want to get next unprocessed document and return it to client.
if not found wait until it appears.

But timer works forever if unprocessed document not found and client cancelled request.

``` ruby
    timer = EventMachine::PeriodicTimer.new(1) do
      p "tick: #{Time.now}"

      @document = GoodDocument.next_unprocessed

      if @document
        @document.make_processed!

        body { @document.to_json }

        timer.cancel
      end
    end
```

I am using `Mongoid 3.0 (with Moped)`, `sinatra` and `async_sinatra`

**Comment by sodabrew** [comment]
Closing.
