### ISSUE TITLE
eventmachine not initialized: evma_install_oneshot_timer

### ISSUE THREAD

**Issue by paddor** [eventmachine/eventmachine#430]
Sometimes, I guess under heavier load on the system, the following things happen:

    eventmachine not initialized: evma_install_oneshot_timer
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:323:in `add_oneshot_timer'
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:323:in `add_timer'
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/em/timers.rb:50:in `schedule'
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/em/timers.rb:37:in `initialize'
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:350:in `new'
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:350:in `add_periodic_timer'

And:

    eventmachine not initialized: evma_connect_to_server
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:664:in `connect_server'
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:664:in `bind_connect'
    /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:640:in `connect'

EventMachine's reactor IS running at this point (or at least should be). Maybe there's a race condition somewhere?

Thanks for your help.

**Comment by u007** [comment]
im having the same issue on 50% of the time

eventmachine not initialized: evma_install_oneshot_timer
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:323:in `add_oneshot_timer'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:323:in `add_timer'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/em/timers.rb:12:in `initialize'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:173:in `new'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:173:in `timeout'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/envelope.rb:11:in `initialize'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/client.rb:357:in `new'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/client.rb:357:in `transport_send'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/client.rb:346:in `block in send'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/extensible.rb:23:in `call'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/extensible.rb:23:in `pipe_through_extensions'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/client.rb:343:in `send'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/client.rb:92:in `handshake'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/client.rb:131:in `connect'
/home/usern/rails/user/vendor/bundle/ruby/2.1.0/gems/faye-1.0.3/lib/faye/protocol/client.rb:270:in `publish'
/home/usern/rails/user/app/models/user_notification.rb:24:in `after_save'

**Comment by u007** [comment]
btw, im running unicorn as server, will this effect faye?

**Comment by sodabrew** [comment]
Could you try event machine 1.0.7 and see if the issue persists?

**Comment by u007** [comment]
hi,
faced the same issue
eventmachine not initialized: evma_install_oneshot_timer
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:323:in `add_oneshot_timer'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:323:in `add_timer'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/dispatcher.rb:116:in `send_envelope'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/dispatcher.rb:100:in `send_message'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:294:in `block in send_message'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/extensible.rb:23:in `call'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/extensible.rb:23:in `pipe_through_extensions'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:291:in `send_message'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:75:in `handshake'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:114:in `connect'
/home/user/rails/myapp/vendor/bundle/ruby/2.1.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:263:in `publish'
/home/user/rails/myapp/app/models/user_notification.rb:24:in `after_save'

**Comment by sodabrew** [comment]
This is almost certainly a thread race. The EM reactor needs to start up before other threads try to use it. It looks like Faye is starting up the reactor, so I recommend filing a bug with them to see if they can take measures to start the reactor in their gem load sequence. They may already be doing this, I'm not sure.

Meanwhile, in your application, the timer is getting added from deep in a model (`myapp/app/models/user_notification:24:in after_save`) - please make sure that you are initializing the Faye gem globally from your initializers, so that when the code reaches that model, it isn't trying to start up Faye for the first time and racing other threads that may also think they have to start up Faye for the first time.

**Comment by u007** [comment]
okay i will give it a try to initialise faye in initializer

**Comment by skunkworker** [comment]
@sodabrew Thanks for the recommendation on the gem load sequence. I had eventmachine above websocket-rails and I was getting this error. Once I put websocket-rails above it then the error went away. Its kind of annoying that a condition like this exists in the first place.

**Comment by sodabrew** [comment]
Good to hear! I'm going to close this issue based on your feedback.
