### ISSUE TITLE
Cannot install on Solaris 10

### ISSUE THREAD

**Issue by wimvandijck** [eventmachine/eventmachine#443]
Hi,

I'm using ruby and rubygems from Opencsw on Solaris 10.

gem 1.8.21
ruby 1.8.7
#gem install eventmachine
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
        ERROR: Failed to build gem native extension.

        /opt/csw/bin/ruby18 extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_wait_for_single_fd()... no
checking for rb_enable_interrupt()... no
checking for rb_time_new()... no
checking for sys/event.h... no
checking for main() in -lnsl... no
could not find library: nsl
*** extconf.rb failed ***

I have /lib/libnsl.so. Is this what it needs?
How can I make the gem command find this?...

Kind regards,
Wim

**Comment by sodabrew** [comment]
I set up a Solaris 11.2 VM and eventmachine 1.0.4 compiled without incident. Closing as resolved.
