### ISSUE TITLE
Unable to install Eventmachine Ruby 2.0 windows 7

### ISSUE THREAD

**Issue by raji789** [eventmachine/eventmachine#451]
eventmachine installation is failing with the following error. Please Help in fixing this.

Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
        ERROR: Failed to build gem native extension.

**Comment by sodabrew** [comment]
This is resolved by eventmachine 1.0.4. Please give it a try and close the issue or comment with follow-up issues. Thanks!

**Comment by ccoenen** [comment]
I can confirm that 1.0.4 installs just fine on Ruby 2.1.5 (32 bit from RubyInstaller) / RubyDevKit-4.7.2-32 / Windows 7 64bit! Thanks.

**Comment by ccoenen** [comment]
Also confirmed with Ruby 2.1.3 (32 bit from RubyInstaller) / RubyDevKit-4.7.2-32 on Win 8.1 64bit.
