### ISSUE TITLE
Mysterious Error while using EM.defer with Ruby 2.0.0

### ISSUE THREAD

**Issue by balwantk** [eventmachine/eventmachine#457]
```
Attempt to unlock a mutex which is not locked (ThreadError)
/Users/balwant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:188:in `synchronize'
/Users/balwant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:188:in `block in pop'
/Users/balwant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:187:in `handle_interrupt'
/Users/balwant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:187:in `pop'
/Users/balwant/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/eventmachine.rb:1036:in `block in spawn_threadpool'
```

**Comment by sodabrew** [comment]
A workaround has landed in eventmachine 1.0.5 from #551.

**Comment by bapu-labade** [comment]
I too facing same issue with ruby 2.1.2p95 (2014-05-08 revision 45877).

Any solution please..

**Comment by sodabrew** [comment]
What version of eventmachine are you using?

**Comment by sodabrew** [comment]
@bapu-labade What version of eventmachine are you using? As noted in this issue, it should be resolved from eventmachine 1.0.5 and higher.

**Comment by bapu-labade** [comment]
@sodabrew - Thanks for the reply. 
I am trying **gem list | grep eventmachine** command but not able to find eventmachine.
I got this issue for ruby on rails application with local WEBrick server.

**Comment by sodabrew** [comment]
Perhaps your application is running with Bundler? `bundle exec gem list` ... ?
