### ISSUE TITLE
tests hang forever (windows)

### ISSUE THREAD

**Issue by ghazel** [eventmachine/eventmachine#46]
Tried both 0.12.8 and 0.12.10

<pre>
C:\Ruby\lib\ruby\gems\1.8\gems\eventmachine-0.12.8-x86-mswin32-60>rake test
... builds ...
C:/Ruby/bin/ruby.exe -Ilib -Iext -Iext/fastfilereader -Ijava tests/testem.rb
Loaded suite tests/testem
Started
..
</pre>

<pre>
C:\Ruby\lib\ruby\gems\1.8\gems\eventmachine-0.12.10-x86-mswin32-60>rake test
(in C:/Ruby/lib/ruby/gems/1.8/gems/eventmachine-0.12.10-x86-mswin32-60)
fatal: Not a git repository (or any of the parent directories): .git
Loaded suite C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
.
</pre>

**Comment by sodabrew** [comment]
This is not a problem in 1.0.x, I can run tests on Windows all the way through (there are failures, but nothing hangs).
