### ISSUE TITLE
1.0.3: Fails compilation on Solaris using Studio 12.3 compiler

### ISSUE THREAD

**Issue by marksolaris** [eventmachine/eventmachine#462]
Following on from this issue https://github.com/eventmachine/eventmachine/issues/313 the 1.0.3 eventmachine won't compile out of the box on Solaris 10 or 11 using the Solaris Studio 12.3 compiler.

The extconf.rb file(s) have obsolete arguments and also need a few tweaks and libraries to get over the line. These are provided below. Note I haven't done extensive testing, just completed the compilation.

In the example below I'm using the Apache stdcxx library as it is much more conforming to the C++ standards than the aging Cstd library that ships in Solaris Studio. The stdcxx.4.2.1 packages can be found on my Solaris Package Archive site:

    http://www.ibiblio.org/pub/packages/solaris/sparc/

Here is a recipe to mod the shipped eventmachine-1.0.3.gem so that it will compile:

    cd /var/tmp
    rm -rf eventmachine
    mkdir -p eventmachine/data
    cd eventmachine
    tar -xf /ul/src/ruby/orig/eventmachine-1.0.3.gem
    cd data
    gunzip -c ../data.tar.gz | tar -xf
    patch -p0 < /usr/local/src/ruby/eventmachine-1.0.3.gem.diff
    tar -cf - `find .gitignore .yardopts .travis.yml * -type f -print` | gzip -9c > ../data.tar.gz
    cd /var/tmp/eventmachine
    tar -cf /usr/local/src/ruby/eventmachine-1.0.3.fixed.gem data.tar.gz metadata.gz

The eventmachine-1.0.3.fixed.gem will now install normally

    host:/ root# gem install ${GEM_PATH}/eventmachine-1.0.3.fixed.gem --ignore-dependencies
    Building native extensions.  This could take a while...
    Successfully installed eventmachine-1.0.3
    Parsing documentation for eventmachine-1.0.3
    unable to convert "\x9B" from ASCII-8BIT to UTF-8 for lib/fastfilereaderext.so, skipping
    unable to convert "\xFD" from ASCII-8BIT to UTF-8 for lib/rubyeventmachine.so, skipping
    Installing ri documentation for eventmachine-1.0.3
    1 gem installed

Here is the diff to apply the the shipped code to allow it to compile on Solaris.

    --- ext/project.h.orig    Tue Sep  3 14:30:42 2013
    +++ ext/project.h    Tue Sep  3 14:30:57 2013
    @@ -97,7 +97,7 @@
     typedef int pid_t;
     #endif
     
    -#if !defined(_MSC_VER) || _MSC_VER > 1500
    +#if !defined(_MSC_VER) || _MSC_VER > 1500 || defined(__sun)
     #include <stdint.h>
     #endif
     
    --- ext/extconf.rb.orig    Fri Sep  6 21:11:05 2013
    +++ ext/extconf.rb    Fri Sep  6 21:12:08 2013
    @@ -64,6 +64,8 @@
       add_define "WITHOUT_SSL"
     end
     
    +add_define 'V=1'
    +add_define '_MATH_H'
     add_define 'BUILD_FOR_RUBY'
     add_define 'HAVE_RBTRAP' if have_var('rb_trap_immediate', ['ruby.h', 'rubysig.h'])
     add_define "HAVE_TBR" if have_func('rb_thread_blocking_region')# and have_macro('RUBY_UBF_IO', 'ruby.h')
    @@ -116,13 +118,15 @@
       add_define 'OS_SOLARIS8'
       check_libs(%w[nsl socket], true)
     
    -  if CONFIG['CC'] == 'cc' and `cc -flags 2>&1` =~ /Sun/ # detect SUNWspro compiler
    +  if CONFIG['CC'] =~ /^cc/ and ((`cc -V 2>&1` =~ /Sun/) || (`cc -flags 2>&1` =~ /Sun/)) # detect SUNWspro compiler
         # SUN CHAIN
         add_define 'CC_SUNWspro'
    -    $preload = ["\nCXX = CC"] # hack a CXX= line into the makefile
    -    $CFLAGS = CONFIG['CFLAGS'] = "-KPIC"
    -    CONFIG['CCDLFLAGS'] = "-KPIC"
    -    CONFIG['LDSHARED'] = "$(CXX) -G -KPIC -lCstd"
    +    # $preload = ["\nCXX = $(CXX)"] # hack a CXX= line into the makefile
    +    $CXXFLAGS = CONFIG['CXXFLAGS'] = "-KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4"
    +    $cxxflags = "$(CXXFLAGS)"
    +    RbConfig::MAKEFILE_CONFIG['CXXFLAGS'] = "-KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4"
    +    $CCDLFLAGS = "-KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4"
    +    $LDSHARED = "$(CXX) -G -KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4"
       else
         # GNU CHAIN
         # on Unix we need a g++ link, not gcc.
    @@ -167,7 +171,7 @@
     
     # solaris c++ compiler doesn't have make_pair()
     TRY_LINK.sub!('$(CC)', '$(CXX)')
    -add_define 'HAVE_MAKE_PAIR' if try_link(<<SRC, '-lstdc++')
    +add_define 'HAVE_MAKE_PAIR' if try_link(<<SRC, '-lCstd')
       #include <utility>
       using namespace std;
       int main(){ pair<int,int> tuple = make_pair(1,2); }
    --- ext/fastfilereader/extconf.rb.orig    Fri Sep  6 23:28:49 2013
    +++ ext/fastfilereader/extconf.rb    Fri Sep  6 23:29:24 2013
    @@ -12,6 +12,8 @@
       $defs.push("-D#{name}")
     end
     
    +add_define 'V=1'
    +add_define '_MATH_H'
     add_define 'BUILD_FOR_RUBY'
     
     # Minor platform details between *nix and Windows:
    @@ -53,13 +55,16 @@
       add_define 'OS_SOLARIS8'
       check_libs(%w[nsl socket], true)
     
    -  if CONFIG['CC'] == 'cc' and `cc -flags 2>&1` =~ /Sun/ # detect SUNWspro compiler
    +  if CONFIG['CC'] =~ /^cc/ and ((`cc -V 2>&1` =~ /Sun/) || (`cc -flags 2>&1` =~ /Sun/)) # detect SUNWspro compiler
         # SUN CHAIN
         add_define 'CC_SUNWspro'
    -    $preload = ["\nCXX = CC"] # hack a CXX= line into the makefile
    +    # $preload = ["\nCXX = $(CXX)"] # hack a CXX= line into the makefile
         $CFLAGS = CONFIG['CFLAGS'] = "-KPIC"
    -    CONFIG['CCDLFLAGS'] = "-KPIC"
    -    CONFIG['LDSHARED'] = "$(CXX) -G -KPIC -lCstd"
    +    $CXXFLAGS = CONFIG['CXXFLAGS'] = "-KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4"
    +    $cxxflags = "$(CXXFLAGS)"
    +    RbConfig::MAKEFILE_CONFIG['CXXFLAGS'] = "-KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4"
    +    $CCDLFLAGS = "-KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4"
    +    $LDSHARED = "$(CXX) -G -KPIC -I/usr/local/include -mt -library=no%Cstd -L/usr/local/lib -lstdcxx4" 
       else
         # GNU CHAIN
         # on Unix we need a g++ link, not gcc.

**Comment by sodabrew** [comment]
This may be resolved by eventmachine 1.0.4. Please give it a try and close the issue or comment with follow-up issues. Thanks!

**Comment by marksolaris** [comment]
My access to those machines isn't available any more, so I won't be able to
assist with the 1.0.4 test sorry.

**Comment by sodabrew** [comment]
@mariochavez Could you give eventmachine 1.0.4 a try on SmartOS?

**Comment by mariochavez** [comment]
@sodabrew my access to SmartOS is not available also. Sorry.

**Comment by sodabrew** [comment]
I set up a Solaris 11.2 VM and eventmachine 1.0.4 compiled without incident. Closing as resolved.
