### ISSUE TITLE
EventMachine with JRuby, running reactor inside a thread problem

### ISSUE THREAD

**Issue by bbozo** [eventmachine/eventmachine#477]
See https://gist.github.com/bbozo/7570484

When running EM reactor in a thread the EM actions aren't running in this simple case (I first observed it using AMQP gem, works same for periodic timer)

However, if I add a next_tick action like

``` ruby
require 'eventmachine'

Thread.new{ EM.run }
until EM.reactor_running?; sleep 0.1; end

EM.add_periodic_timer(1){ puts "tick" }
EM.next_tick{puts "."}

sleep 5
```

then the ticks get executed:

```
bbozo@uhurajr-ubuntu:~/dev$ ruby em_jruby_problem.rb
.
tick
tick
tick
tick
tick

```

**Comment by sodabrew** [comment]
@bbozo Are you using EM with C extensions, or pure ruby?

I'm having a lot of trouble with JRuby in my PR #551 and it's not clear to me if JRuby and EM get along at all, let alone run unit tests successfully.

**Comment by tmm1** [comment]
Neither. There is a separate Java reactor implementation for jruby.

**Comment by sodabrew** [comment]
Ack. Ok, then I'm seeing the same problems in PR #551 in Java mode.

**Comment by awood** [comment]
I'm hitting this problem as well.  I created a reproducer [here](https://github.com/awood/em-example) using eventmachine-1.2.0.1

**Comment by sodabrew** [comment]
@awood Thanks for the repro case!
