### ISSUE TITLE
ERROR: Failed to build gem native extension on production server

### ISSUE THREAD

**Issue by medyo** [eventmachine/eventmachine#483]
Hi, 

It seems that EventMachine would not be installed on production server.
I still get this error everytime i try to deploy the app (capistrano).

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
/home/deployer/.rvm/rubies/ruby-2.0.0-p353/bin/ruby extconf.rb
Gem files will remain installed in 
/home/deployer/apps/Myapp/shared/bundle/ruby/2.0.0/gems/eventmachine-1.0.3
Results logged to /home/deployer/apps/Myapp/shared/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/ext/gem_make.out
Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling. 

I tried to install the gem from server, it succeeds while from local it fails.

**Comment by sodabrew** [comment]
The gem is generally known to build. A recent fix in v1.0.6 may apply to this specific case, see #574. Please reopen if this remains a problem.
