### ISSUE TITLE
`run_machine': unknown connection: \d (EventMachine::ConnectionNotBound)

### ISSUE THREAD

**Issue by davidhq** [eventmachine/eventmachine#485]
I get this on Ruby 2.0+

```
/var/www/linkrecover/vendor/bundle/ruby/2.1.0/bundler/gems/eventmachine-cfb1f71a35b1/lib/eventmachine.rb:187:in `run_machine': unknown connection: 35 (EventMachine::ConnectionNotBound)
    from /var/www/linkrecover/vendor/bundle/ruby/2.1.0/bundler/gems/eventmachine-cfb1f71a35b1/lib/eventmachine.rb:187:in `run'
    from /var/www/linkrecover/vendor/bundle/ruby/2.1.0/gems/thin-1.6.1/lib/thin/backends/base.rb:73:in `start'
    from /var/www/linkrecover/vendor/bundle/ruby/2.1.0/gems/thin-1.6.1/lib/thin/server.rb:162:in `start'
    from /var/www/linkrecover/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
    from /var/www/linkrecover/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
    from /var/www/linkrecover/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
    from /var/www/linkrecover/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.0/bin/rackup:23:in `load'
    from /usr/local/rvm/gems/ruby-2.1.0/bin/rackup:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

I saw something similar discussed here:
https://github.com/igrigorik/em-http-request/issues/190

but with no real solution that applies to eventmachine in general.

I tried it on the latest commit...

SOLUTION: I had to use Ruby 1.9.3(p484) - no such problems there.

thank you for helping
david

**Comment by sodabrew** [comment]
@davidhq Per igrigorik/em-http-request#190 the solution appears to be
https://github.com/godfat/rest-core/commit/50bc6a1e891eac928bfcfaa9e520895e80e5d09e
Use EM.schedule or EM.next_tick to create the new tasks on the main reactor thread only.

**Comment by davidhq** [comment]
thank you.... I started using next_tick but I think I haven't tested it on
Ruby 2 afterwards... I'll try soon then.

**Comment by jronallo** [comment]
I'm still getting this error with latest gems (thin, eventmachine, faye) and Ruby 2.1.5. The application works for a while and then just dies all of a sudden with this error. Anyone have a potential fix for this? I'm not following other fixes.

**Comment by davidhq** [comment]
Fix is to use node.js server and socket.io on frontend :) worked for me
perfectly

**Comment by genki** [comment]
It seemed that @conn in EM module is accessed from ensure_conn(...) of rubymain.cpp before the connection object is stored by t_connect_server.
It may be fixed by using mutex for @conn.
