### ISSUE TITLE
Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE

### ISSUE THREAD

**Issue by dwt** [eventmachine/eventmachine#487]
After installing version 1.0.3 of event machine, I'm getting this error:

% ruby --version
ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-darwin12.3.0]
% irb
irb(main):001:0> require 'eventmachine'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
LoadError: dlopen(/Users/dwt/Library/Ruby/Gems/1.9/gems/eventmachine-1.0.3/lib/rubyeventmachine.bundle, 9): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/dwt/Library/Ruby/Gems/1.9/gems/eventmachine-1.0.3/lib/rubyeventmachine.bundle
  Expected in: flat namespace
 in /Users/dwt/Library/Ruby/Gems/1.9/gems/eventmachine-1.0.3/lib/rubyeventmachine.bundle - /Users/dwt/Library/Ruby/Gems/1.9/gems/eventmachine-1.0.3/lib/rubyeventmachine.bundle
	from /Users/dwt/Library/Homebrew/Cellar/ruby/1.9.3-p374/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/dwt/Library/Homebrew/Cellar/ruby/1.9.3-p374/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/dwt/Library/Ruby/Gems/1.9/gems/eventmachine-1.0.3/lib/eventmachine.rb:8:in `<top (required)>'
	from /Users/dwt/Library/Homebrew/Cellar/ruby/1.9.3-p374/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
	from /Users/dwt/Library/Homebrew/Cellar/ruby/1.9.3-p374/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
	from /Users/dwt/Library/Homebrew/Cellar/ruby/1.9.3-p374/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from (irb):1
	from /Users/dwt/Library/Homebrew/bin/irb:12:in `<main>'
irb(main):002:0> 

I'm not entirely sure what to make of this, some googling seems to suggest that maybe the std lib wasn't linke correctly to the egg when building it - but that's not something I'm familiar with.

The suggested workaround, i.e. prefixing the import with "require 'em/pure_ruby'" seems to work for now but is a pain to get into all the tools that are using event machine under the hood.

**Comment by rbu** [comment]
@sodabrew (how) Is this fixed?

**Comment by sodabrew** [comment]
The original issue was caused by conflicting Ruby versions and the OP resolved it per  https://github.com/eventmachine/eventmachine/issues/487#issuecomment-32246506

The second issue, failing tests, has been fixed in tree.
