### ISSUE TITLE
Failed to build gem native extension EM on Mac with Ruby 1.9.3-p484

### ISSUE THREAD

**Issue by jackfengibm** [eventmachine/eventmachine#493]
command "gem install eventmachine -v '1.0.3' " worked on the same machine with Ruby 1.9.3-p448.  But with Ruby 1.9.3-p484, the same command yielded the following error:

Jacks-MacBook-Pro:dea_ng jackfeng$ gem install eventmachine -v '1.0.3'
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/jackfeng/.rvm/rubies/ruby-1.9.3-p484/bin/ruby extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... yes
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make  clean

make
compiling binder.cpp
make: /usr/bin/: Permission denied
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3 for inspection.
Results logged to /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484/extensions/x86_64-darwin-13/1.9.1/eventmachine-1.0.3/gem_make.out

Here is my gem env:

Jacks-MacBook-Pro:dea_ng jackfeng$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [x86_64-darwin13.0.2]
  - INSTALLATION DIRECTORY: /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484
  - RUBY EXECUTABLE: /Users/jackfeng/.rvm/rubies/ruby-1.9.3-p484/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484/bin
  - SPEC CACHE DIRECTORY: /Users/jackfeng/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484
     - /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/", "http://gems.github.com/"]
  - REMOTE SOURCES:
     - https://rubygems.org/
     - http://gems.github.com/
  - SHELL PATH:
     - /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484/bin
     - /Users/jackfeng/.rvm/gems/ruby-1.9.3-p484@global/bin
     - /Users/jackfeng/.rvm/rubies/ruby-1.9.3-p484/bin
     - /Users/jackfeng/.rvm/bin
     - /Users/jackfeng/perl5/bin
     - /Users/jackfeng/go/bin
     - .
     - /Users/jackfeng/perl5/bin
     - /Users/jackfeng/go/bin
     - .
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/jackfeng/.gvm/vertx/current/bin
     - /Users/jackfeng/.gvm/springboot/current/bin
     - /Users/jackfeng/.gvm/lazybones/current/bin
     - /Users/jackfeng/.gvm/groovyserv/current/bin
     - /Users/jackfeng/.gvm/groovy/current/bin
     - /Users/jackfeng/.gvm/griffon/current/bin
     - /Users/jackfeng/.gvm/grails/current/bin
     - /Users/jackfeng/.gvm/gradle/current/bin
     - /Users/jackfeng/.gvm/gaiden/current/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/local/git/bin
     - /usr/local/go/bin
     - /usr/local/go/bin
     - /Applications/p4merge.app/Contents/MacOS/p4merge
     - /Users/jackfeng/Applications
     - /usr/local/go/bin
     - /Applications/p4merge.app/Contents/MacOS/p4merge
     - /Applications/p4merge.app/Contents/MacOS
     - /Users/jackfeng/Applications

==========================
Here is my gcc info:
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.0.2
Thread model: posix

==========================
And my OS version:
Jacks-MacBook-Pro:dea_ng jackfeng$ uname -a
Darwin Jacks-MacBook-Pro.local 13.0.2 Darwin Kernel Version 13.0.2: Sun Sep 29 19:38:57 PDT 2013; root:xnu-2422.75.4~1/RELEASE_X86_64 x86_64

**Comment by sodabrew** [comment]
Hi, it's been a few months - is this still an open issue for you?

**Comment by jackfengibm** [comment]
thanks.  Please close it.  After cleaning older versions of ruby installed
on my laptop, the built finally behaved.   Thanks again for getting back to
me.

Jack
