### ISSUE TITLE
Deprecated use of 'rb_thread_select'?

### ISSUE THREAD

**Issue by dvdplm** [eventmachine/eventmachine#495]
EM seems to be using `rb_thread_select` in em.h: `#define EmSelect rb_thread_select`. That is deprecated (since a good while I believe) and as of https://bugs.ruby-lang.org/issues/9502#change-45212 it's been removed, meaning EM doesn't build on current ruby trunk.

Unfortunately it doesn't seem like the replacement, `rb_thread_fd_select` takes the same argument types, and rooting out usage of `fd_set` with `rb_fdset_t` is beyond my weak C++ chops.

**Comment by maxmeyer** [comment]
Any progress on this?

**Comment by maxmeyer** [comment]
see  #553 as well. This might help.

**Comment by tmm1** [comment]
eventmachine 1.0.4 was released with ruby 2.2 compatibility
