### ISSUE TITLE
Periodic Timer misfire or false fire

### ISSUE THREAD

**Issue by senthil-chinnaiyan** [eventmachine/eventmachine#496]
We use eventmachine in an embedded linux platform (cross compiled). Some of the key features of network, timers, socket, file/directory watch and differ are used heavily. We have few issues related to the system time change and they are:

1. When the System Time is set to back date, the periodic timer misfires.
2. Ehen the System time is advanced, then periodic timer false fires.
3. Sometimes the CPU is touching very high percentage and after some time the ruby process is put into zombie state. (There is a fix for this: https://github.com/eventmachine/eventmachine/issues/428), but this doesn’t solve the above 2 issues.

To re-produce:
1. Set the time of the linux system using date command: date +%T -s "16:36:30"
2. Run this code:

require "eventmachine"

EM.run {
    EventMachine::PeriodicTimer.new(2) do
        puts "Timer Fired: #{Time.now}"
    end
}
3. Generates output like this:
Timer Fired: 2014-10-21 16:36:35 -0500
Timer Fired: 2014-10-21 16:36:37 -0500
Timer Fired: 2014-10-21 16:36:39 -0500
Timer Fired: 2014-10-21 16:36:41 -0500
4. Change the time to backward (10 seconds) in another console: date +%T -s "16:36:20"
5. No output for 10 seconds and the timer fires after the system time is greater than next fire_at time.
 
After investigation, we have found that the _GetTimers() function skips the fire because the MyCurrentLoopTime  is lesser than the i->first. Reason being the MyCurrentLoopTime is associated with the system clock.

Solution (Tested in Linux):
To resolve this, the gettimeofday should be avoided and clock_gettime(CLOCK_MONOTONIC, &ts_spec); can be used instead. This will ensure that the MyCurrentLoopTime won’t be affected if the system time is changed.

Tested on Linux and works as expected.

uint64_t EventMachine_t::GetRealTime()
{
	uint64_t current_time;

	#if defined(OS_UNIX)
                /*struct timeval tv;*/
                /*gettimeofday (&tv, NULL);*/
                /*current_time = (((uint64_t)(tv.tv_sec)) * 1000000LL) + ((uint64_t)(tv.tv_usec));*/

                struct timespec tv;
                clock_gettime(CLOCK_MONOTONIC, &tv);
                current_time = (((uint64_t)(tv.tv_sec)) * 1000000LL) + ((uint64_t)((tv.tv_nsec)/1000));

	#elif defined(OS_WIN32)
	unsigned tick = GetTickCount();
	if (tick < LastTickCount)
		TickCountTickover += 1;
	LastTickCount = tick;
	current_time = ((uint64_t)TickCountTickover << 32) + (uint64_t)tick;
	current_time *= 1000; // convert to microseconds

	#else
	current_time = (uint64_t)time(NULL) * 1000000LL;
	#endif

	return current_time;
}

NOTE: The bug fix #428 is "NOT" required if "CLOCK_MONOTONIC" is used.

**Comment by sodabrew** [comment]
Unfortunately, `clock_gettime` is not available on OS X. There are some alternatives, it'd be another case in the ifdef block.

**Comment by sodabrew** [comment]
Resolved by #563
