### ISSUE TITLE
LoadError with Ruby 2.1.0 and Rails 4.1.0rc1

### ISSUE THREAD

**Issue by xpopov** [eventmachine/eventmachine#504]
I've installed eventmachine 1.0.3 (tried using "gem install", and also built locally latest sources from git).

But built .so file cannot be loaded by Rails, but .so file actually created during compilation: G:/Work/Ruby2.1/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/eventmachine-1.0.3/rubyeventmachine.so

$ rails g devise:install

Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
G:/Work/Ruby2.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require': 126: The specified module could not be found.   - G:/Work/Ruby2.1/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/eventmachine-1.0.3/rubyeventmachine.so (LoadError)
        from G:/Work/Ruby2.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in
`block in require'

**Comment by sodabrew** [comment]
This may be resolved by eventmachine 1.0.4. Please give it a try and close the issue or comment with follow-up issues. Thanks!

**Comment by sodabrew** [comment]
Closing, presumed to be resolved.
