### ISSUE TITLE
Using kqueue could cause assertion failed

### ISSUE THREAD

**Issue by libc** [eventmachine/eventmachine#51]
Script: http://gist.github.com/257629
Output: http://gist.github.com/257628#file_output

Basically it nails down to this: it has 2 socket descriptors, kevent returns both. While processing first EM arms kqueue for writing, then sends all the data. And in the next kevent tick it fails assertion.

Reproducible with 0.12.10 on both freebsd and mac os x.

I come up with this patch: https://gist.github.com/bced7e3402d8aa482681

I add bKqueueArmWrite, and do actual arming in _ModifyDescriptors, so all data are sent to sockets at this point.

**Comment by tmm1** [comment]
:+1: getting this in for the next release
