### ISSUE TITLE
EM crashes on Linux systems when calling stop_watching if there have been multiple .watch_file calls to the same file

### ISSUE THREAD

**Issue by rb2k** [eventmachine/eventmachine#512]
This works (given that /tmp/foo exists):

``` ruby
require 'rubygems'
require 'eventmachine'
EM.kqueue=true
EventMachine.run {
  w1 = EventMachine.watch_file("/tmp/foo")
  w2 = EventMachine.watch_file("/tmp/foo")
  w2.stop_watching
}
```

This fails:

``` ruby
require 'rubygems'
require 'eventmachine'
EventMachine.run {
  w1 = EventMachine.watch_file("/tmp/foo")
  w2 = EventMachine.watch_file("/tmp/foo")
  w2.stop_watching
}


#  ruby emtest.rb
terminate called after throwing an instance of 'std::runtime_error'
  what():  attempted to remove invalid watch signature
Aborted
```

Notice that the return value from inotify_add_watch is the same (1):

```
stat("/tmp/foo", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
inotify_init()                          = 6
fcntl(6, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(6, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
inotify_add_watch(6, "/tmp/foo", IN_MODIFY|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF) = 1
stat("/tmp/foo", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
inotify_add_watch(6, "/tmp/foo", IN_MODIFY|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF) = 1
```

EM uses a c++ std::map to map the inotify watch descriptor (wd) to the "bindable" object.
std::map has unique keys and Eventmachine [uses std::map::insert()](https://github.com/eventmachine/eventmachine/blob/2ed44025e35518898c8589a610515e54a7b40c44/ext/em.cpp#L2176-L2177)

Looking for this map insert function leads to:
"Because element keys in a map are unique, the insertion operation checks whether each inserted element has a key equivalent to the one of an element already in the container, and if so, the element is not inserted."

This is why unwatching the _second_ open watcher always fails.
em.cpp [loops through the std::map looking for the signature](https://github.com/eventmachine/eventmachine/blob/2ed44025e35518898c8589a610515e54a7b40c44/ext/em.cpp#L2211-L2218) and doesn't find it, because map::insert() did not overwrite the first value inserted for that key.

**Comment by surenm** [comment]
I faced the same issue as well which was impacting my work, so ended up submitting a patch.

PS: Thanks a ton for EM 👍
