### ISSUE TITLE
Eventmachine install failing on fedora

### ISSUE THREAD

**Issue by rabdureh** [eventmachine/eventmachine#517]
I'm running a 64-bit fedora version of Linux with Ruby 1.9.3 and having trouble installing eventmachine. Reading around from googling hasn't provided much help as most people were on OS X or Windows.. Here is the entire output of when I run the command "gem install eventmachine -v '1.0.3'" - 

    Building native extensions.  This could take a while...
    ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-1.9.3-p547/bin/ruby extconf.rb
    checking for rb_trap_immediate in ruby.h,rubysig.h... no
    checking for rb_thread_blocking_region()... yes
    checking for inotify_init() in sys/inotify.h... yes
    checking for writev() in sys/uio.h... yes
    checking for rb_wait_for_single_fd()... yes
    checking for rb_enable_interrupt()... yes
    checking for rb_time_new()... yes
    checking for sys/event.h... no
    checking for epoll_create() in sys/epoll.h... yes
    creating Makefile

    make  clean

    make
    compiling binder.cpp
    make: g++: Command not found
    make: *** [binder.o] Error 127

    make failed, exit code 2

    Gem files will remain installed in /usr/local/rvm/gems/ruby-1.9.3-p547/gems/eventmachine-1.0.3 for inspection.
    Results logged to /usr/local/rvm/gems/ruby-1.9.3-p547/extensions/x86_64-linux/1.9.1/eventmachine-1.0.3/gem_make.out

Any advice would be appreciated

**Comment by sodabrew** [comment]
@rabdureh If installing the development tools has resolved this problem for you please close the issue.
