### ISSUE TITLE
eventmachine fails on Solaris 11.1

### ISSUE THREAD

**Issue by CirrusThink** [eventmachine/eventmachine#527]
Not sure what the issue. Do I need to install a different compiler ?

gem install eventmachine -v 1.0.3
Fetching: eventmachine-1.0.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
        ERROR: Failed to build gem native extension.

        ~/xxx/.rvm/rubies/ruby-1.9.3-p392/bin/ruby extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... yes
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for main() in -lnsl... yes
checking for main() in -lsocket... yes
creating Makefile

make
compiling kb.cpp
cc1plus: warning: command line option "-Wdeclaration-after-statement" is valid for C/ObjC but not for C++
cc1plus: warning: command line option "-Wimplicit-function-declaration" is valid for C/ObjC but not for C++
In file included from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/ostream:40:0,
                 from /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/iostream:40,
                 from project.h:29,
                 from kb.cpp:20:
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/../../../../include/c++/4.5.2/ios:44:22: fatal error: streambuf: No such file or directory
compilation terminated.
make: *** [kb.o] Error 1

Gem files will remain installed in ~/xxx/.rvm/gems/ruby-1.9.3-p392@revo/gems/eventmachine-1.0.3 for inspection.
Results logged to ~/xxx/.rvm/gems/ruby-1.9.3-p392@revo/gems/eventmachine-1.0.3/ext/gem_make.out

**Comment by sodabrew** [comment]
Please try the recently-released eventmachine 1.0.4 and comment back to say if it works or not.

**Comment by sodabrew** [comment]
@CirrusThink Any luck? There are several Solaris bug reports, but nobody seems to have their Solaris (or illumos or smartos) installations available anymore to verify if 1.0.4 has resolved the issues or not.

**Comment by sodabrew** [comment]
I set up a Solaris 11.2 VM and eventmachine 1.0.4 compiled without incident. Closing as resolved.
