### ISSUE TITLE
Keepalive and eventmachine, How can I do this more correctly?

### ISSUE THREAD

**Issue by egenial** [eventmachine/eventmachine#537]
what is the best way to create a keepalive with eventmachine?

I have a client in ruby ​​that is "listening" to customers connecting or disconnecting them at a greater period of time, example, if the person I hope to leave 30 seconds before finalizing it in the database/redis.

I'm using an instance of Rufus :: Scheduler for each client, i am "listening" them alone.

But I realized that to put a little more 20-50 connections, the process of my cliente.rb is 100% CPU hangs there and does not go down more. getting a dead application.

How can I do this more correctly? Eventmachine loop? 

Plan to have 5000 active customers, with keep-alive.

Thanks!

**Comment by sodabrew** [comment]
This is a pretty late reply, but try using `EM.add_periodic_timer` for this purpose.
