### ISSUE TITLE
Is pure_ruby.rb obsolete?

### ISSUE THREAD

**Issue by ingobecker** [eventmachine/eventmachine#541]
I tried to write a server that involes serial communication and stumbled upon the [serialport example](https://github.com/eventmachine/eventmachine/wiki/Code-Snippets#em-over-a-serial-port) under the Code Snippets section in the wiki. This example is clearly out of date but it kind of worked for me. I then recognized that the `pure_ruby.rb` which it depends on also is completly out of date. By looking at the code, to me it seems to be incompatible with newer versions of Ruby. Are there any plans about further development of `pure_ruby.rb` or should it be treated as being obsolete?
It would be nice to have some remarks about the state of `pure_ruby.rb` somewhere in the wiki or documentation.

**Comment by sodabrew** [comment]
@garbagecat I am trying to figure out if JRuby is a supported platform. I cannot get unit tests to pass in #551 in either C extension mode or pure ruby mode. Could you advise whether pure ruby mode is what should be tested for JRuby?

**Comment by sodabrew** [comment]
@ingobecker pure_ruby generally works, however it includes a lot of <= 1.8.6 workarounds. Those could be removed at this point and 1.8.7 or higher assumed. Is there a particular concern that you'd like to see resolved here?

**Comment by sodabrew** [comment]
The pure_ruby implementation may have some incompleteness vs. the C++ implementation, but it is considered a fully supported part of this package. If you do encounter any bugs, please file them!
