### ISSUE TITLE
double time for comm_inactivity_timeout

### ISSUE THREAD

**Issue by zak** [eventmachine/eventmachine#554]
For some reason comm_inactivity_timeout doubles specified time

https://gist.github.com/zak/7920e312aa43881d190b

Sometimes get this

https://gist.github.com/zak/2a284761737cb4fee8ae

EM 1.0.3, 1.0.4
ruby 2.1.4, 2.1.3

**Comment by sodabrew** [comment]
I think this may have the same root cause / resolution as #496?

**Comment by sodabrew** [comment]
Resolved by #563
