### ISSUE TITLE
why tcp server use a backlog parameter of 50, why not SOMAXCONN?

### ISSUE THREAD

**Issue by Nxbtch** [eventmachine/eventmachine#557]
# TODO, refactor and unify with EvmaUNIXServer.

    class << self
      # Versions of ruby 1.8.4 later than May 26 2006 will work properly
      # with an object of type TCPServer. Prior versions won't so we
      # play it safe and just build a socket.
      #
      def start_server host, port
        sd = Socket.new( Socket::AF_INET, Socket::SOCK_STREAM, 0 )
        sd.setsockopt( Socket::SOL_SOCKET, Socket::SO_REUSEADDR, true )
        sd.bind( Socket.pack_sockaddr_in( port, host ))
        sd.listen( 50 ) # 5 is what you see in all the books. Ain't enough.
        EvmaTCPServer.new sd
      end
    end

**Comment by sodabrew** [comment]
If anything this should be configurable, IMHO.

One reason for adjusting a listen backlog is balance between keeping clients queued until the service is ready vs. fast-fail clients if the service is running behind on accepting connections.

**Comment by wyhaines** [comment]
I could swear that I had a patch some years ago that made this a
configurable parameter. I will check my archives. I may have it stashed.

Kirk Haines

**Comment by Nxbtch** [comment]
@wyhaines @sodabrew code copy from master branch. 

https://github.com/eventmachine/eventmachine/blob/master/lib/em/pure_ruby.rb#L785
