### ISSUE TITLE
Daemonising inside an event loop causes hangs

### ISSUE THREAD

**Issue by sj26** [eventmachine/eventmachine#569]
Unfortunately the latest eventmachine release has broken [mailcatcher](https://github.com/sj26/mailcatcher).

With eventmachine 1.0.4, if you install the latest mailcatcher with `gem install mailcatcher -v "0.5.9"` then start it with `mailcatcher _0.5.9_` then `nc localhost 1025` you won't get a welcome message, and the process won't respond to SIGTERM. (There's a workaround in 0.6.0.)

Mailcatcher starts an eventmachine loop and binds to a couple of ports before daemonising so we can display messages back to the user if anything fails. Previously this worked fine, and if you run without daemonisation it still works fine, but when daemonising the smtp server stops working. (Thin continues working fine, however).

Some bisecting revealed 10deb49b9b0ac2f3a1a372cc25916d2b6710b079 to be the guilty commit. Not sure exactly how it's interacting to cause SMTP to fail but not Thin.

I assume this is because daemonising will fork, twice, and that is tripping up the pid change handling.

**Comment by sodabrew** [comment]
Interesting that the fix is simply to restore the original reactor_running? behavior. I will take a look at this.
https://github.com/sj26/mailcatcher/commit/757eafe33782257a3000bc49b4c04292a4da19c6

**Comment by sodabrew** [comment]
Oh - SMTP fails but not Thin. Are you using the EventMachine SMTP module?

**Comment by sj26** [comment]
Yeah, it's using the built in `EventMachine::Protocols::SmtpServer` in [`MailCatcher::Smtp`](https://github.com/sj26/mailcatcher/blob/master/lib/mail_catcher/smtp.rb). I figured it might be doing something inside using `reactor_running?` but wasn't sure how far down the rabbit hole it might be.

Thanks for looking into it!

**Comment by tmm1** [comment]
forking off while the reactor is running is not recommended. But if you must, you should use the EM.fork_reactor method. I would recommend copying the daemonization implementation from Thin.

**Comment by sj26** [comment]
Daemonization for thin use the daemons gem, which seems at core equivalent to `Process.daemon`, and doesn't seem to do anything special to the eventmachine reactor? I'm not sure what it would be doing specially. The old processes die immediately after forking so using the same fds should be fine?

**Comment by sodabrew** [comment]
I think this is pretty unconventional: https://github.com/sj26/mailcatcher/blob/5b3781b44cd3ad82c18fe38f7d15add4a5cf0ef8/lib/mail_catcher.rb#L155-190

Normally, I would do all of my setup (gather resources, open files, open ports) and then daemonize and then begin my run loop.

Forking in the middle of the event loop appears to be something that wasn't supposed to work, but by lucky bug it did allow you to do it. I'm not sure what the consequences of this are, e.g. was something secretly broken but it didn't materialize as a bug for you.

**Comment by sodabrew** [comment]
Ping -  is still a problem for MailCatcher with latest eventmachine (looks like you're on 1.0.9.1 now)?
