### ISSUE TITLE
Eventmachine >= 1.0.5 with Thin on Windows with Ruby 2.x leaking memory

### ISSUE THREAD

**Issue by neongrau** [eventmachine/eventmachine#585]
Observed with 1.0.6: as soon as the ruby process is started it'll leak 16KB chunks of memory pretty much every second. This happens without serving any Requests (load balancer in front was disabled).

After downgrading to 1.0.4 this does not happen anymore. Quick test with Eventmachine 1.0.5 also had the memory leak.

**Comment by virtualfunction** [comment]
Interesting, I noticed a similar issue, but tried rolling back and found the issue still persisted. I'm using EM with the Sinatra SSE gem which happens to add timers for each connection to send keep alive data. This seemed to be the source of the leak. I ditched the SSE gem and used a static app level timer instead of a connection level one to remove the mem leaks.

**Comment by tmm1** [comment]
@neongrau Are you using SSL? Or any of the other features that were changed in the 1.0.5 release: https://github.com/eventmachine/eventmachine/blob/master/CHANGELOG.md#105-february-2-2015 ?

**Comment by neongrau** [comment]
Not using SSL on that side. When i use SSL it happens on an Apache Load Balancer.
It's quite easy to reproduce. Create a fresh Rails app "rails new testapp" add "gem 'thin'" to Gemfile and do "bundle install".
With "thin start" you will immediatly see the memory ticking up.

I'm not sure if that usage scenario corresponds to any of the changes in 1.0.5

**Comment by tmm1** [comment]
@neongrau I think I found the leak. Can you confirm which version of ruby, platform (linux/mac/windows) and whether you are using kqueue or epoll?

**Comment by neongrau** [comment]
Most of my testing was with Ruby 2.0.0p598 x64-mingw32. But also with 2.1.5 which made no difference except even higher memory usage. Can't really answer the kqueue/epoll question. Just using Thin 1.6.0 - 1.6.3 which is the part that relies on Eventmachine.

**Comment by tmm1** [comment]
@neongrau Can you try v1.0.7, it should fix this issue.

**Comment by neongrau** [comment]
Yes, 1.0.7 seems to have fixed the leak. Now starting a longer running test as i had another issue with the Thin server stop responding to requests after a couple of hours.

**Comment by le0pard** [comment]
Confirmed. 

Memory leak was in v1.0.6 and it disappear after update to v1.0.7. 

http://monosnap.com/image/z6UbbSozx7xwnSv1cqU4GWVeMtwsci
