### ISSUE TITLE
Failed to build gem native extension. eventmachine 1.0.7, ruby 2.2.2 x64. Ubuntu 14.10.

### ISSUE THREAD

**Issue by Antiarchitect** [eventmachine/eventmachine#592]
/home/andrey/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150423-14286-abxsn8.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/andrey/.rvm/rubies/ruby-2.2.2/bin/$(RUBY_BASE_NAME)
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
/home/andrey/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/andrey/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /home/andrey/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /home/andrey/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /home/andrey/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:64:in `<main>'

extconf failed, exit code 1

**Comment by sodabrew** [comment]
As the output says, please check the `mkmf.log` to see where the failure occurred. Most likely you are missing a libfoo-dev package for some libfoo that Ruby is looking for. Hopefully the `mkmf.log` will provide a clue to the foo!

**Comment by Antiarchitect** [comment]
"gcc -o conftest -I/home/andrey/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/x86_64-linux -I/home/andrey/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0/ruby/backward -I/home/andrey/.rvm/rubies/ruby-2.2.2/include/ruby-2.2.0 -I.    -march=native -O2 -pipe -fomit-frame-pointer -fPIC conftest.c  -L. -L/home/andrey/.rvm/rubies/ruby-2.2.2/lib -Wl,-R/home/andrey/.rvm/rubies/ruby-2.2.2/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-R/home/andrey/.rvm/rubies/ruby-2.2.2/lib -L/home/andrey/.rvm/rubies/ruby-2.2.2/lib -lruby  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

**Comment by Antiarchitect** [comment]
Installing of `libgmp-dev` did the trick.

**Comment by tompave** [comment]
Same issue on `Ubuntu 14.04.03`, with `MRI 2.2.3` and `eventmachine 1.0.8`.  
On the same machine, the installation completed successfully with `MRI 2.0.0-p645`.

Installing `libgmp-dev` solved the problem for `MRI 2.2.3` too.
