### ISSUE TITLE
undefined method `installOneshotTimer' for nil:NilClass

### ISSUE THREAD

**Issue by lumrandir** [eventmachine/eventmachine#597]
Hello.

I'm using eventmachine 1.0.7 with jruby 1.7.19. When I'm trying to create a PeriodicTimer as in example [here](http://eventmachine.rubyforge.org/EventMachine/PeriodicTimer.html), I get the following error:

    NoMethodError: undefined method `installOneshotTimer' for nil:NilClass
	from ~/.rvm/gems/jruby-1.7.19/gems/eventmachine-1.0.7-java/lib/jeventmachine.rb:108:in `add_oneshot_timer'
	from ~/.rvm/gems/jruby-1.7.19/gems/eventmachine-1.0.7-java/lib/eventmachine.rb:323:in `add_timer'
	from ~/.rvm/gems/jruby-1.7.19/gems/eventmachine-1.0.7-java/lib/em/timers.rb:50:in `schedule'
	from ~/.rvm/gems/jruby-1.7.19/gems/eventmachine-1.0.7-java/lib/em/timers.rb:37:in `initialize'
	from (irb):2:in `evaluate'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from ~/.rvm/rubies/jruby-1.7.19/bin/irb:13:in `(root)'

Is there something I'm doing wrong?

**Comment by sodabrew** [comment]
Have you called for a timer before starting the EM? Please post your code snippet from your irb session.

**Comment by lumrandir** [comment]
Sorry, I have completely forgotten about this. There is no single snippet already, so I just close this issue.
