### ISSUE TITLE
Interrupts and Signals do not work on rbx 2.5.3+

### ISSUE THREAD

**Issue by kayakyakr** [eventmachine/eventmachine#598]
There is some sort of collision with rubinius's new forking code that causes the rails server to ignore all interrupts. This means you cannot ctrl-c to quit or use USR2 or QUIT to stop or restart a server in production.

Example project:
https://github.com/kayakyakr/rbxtest

Issue under rubinius:
https://github.com/rubinius/rubinius/issues/3418

**Comment by sodabrew** [comment]
This appears to be resolved upstream; can you confirm is Rubinius 2.5.7 works for you?

**Comment by kayakyakr** [comment]
Yeah, not an event machine issue, thanks.
