### ISSUE TITLE
Can't reinstall on OS X with openssl 1.0.2a-1

### ISSUE THREAD

**Issue by firedev** [eventmachine/eventmachine#602]
Just installed El Capitan and can't install gem `eventmachine` `1.0.7`. Any suggestions are really appreciated. Thanks.
```
$ ls /usr/local/Cellar/openssl/1.0.2a-1/include/openssl/ssl.h
/usr/local/Cellar/openssl/1.0.2a-1/include/openssl/ssl.h

$ gem install eventmachine -v '1.0.7' -- --with-ssl-dir=/usr/local/Cellar/openssl/1.0.2a-1/include
/Users/pain/.rbenv/versions/2.1.2/bin/ruby -r ./siteconf20150612-56154-1hsjz2n.rb extconf.rb --with-ssl-dir=/usr/local/Cellar/openssl/1.0.2a-1/include
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue... yes
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
./project.h:116:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

```

**Comment by ariperez** [comment]
This seems to have worked for me:
```
gem install eventmachine -v '1.0.3' -- --with-cppflags=-I/usr/local/opt/openssl/include
```

Not really sure what is happening but I saw this when installing openssl:
![image](https://cloud.githubusercontent.com/assets/2553469/8151071/ba98171c-12d0-11e5-9fb5-2ca78ba59052.png)

and then stumbled upon this method for declaring the flag:
http://serverfault.com/questions/577944/gem-install-append-cppflags-ldflags

Would be interested in knowing the actual fix.

**Comment by firedev** [comment]
Amazing, thanks. They probably forgot to add this information to the current `brew info` for `openssl`:
```
$ gem install eventmachine -v '1.0.7' -- --with-cppflags=-I/usr/local/opt/openssl/include                                                                                                             
Building native extensions with: '--with-cppflags=-I/usr/local/opt/openssl/include'
This could take a while...
Successfully installed eventmachine-1.0.7
1 gem installed
```
```
$ brew info openssl
Warning: Although Homebrew has added initial recognition of 10.11, it is unsupported.
You may encounter breakage or other failure and there is no guarantee
Homebrew can resolve those issues until El Capitan is stable.

openssl: stable 1.0.2c
OpenSSL SSL/TLS cryptography library
https://openssl.org

This formula is keg-only.
Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

/usr/local/Cellar/openssl/1.0.2a-1 (463 files, 17M)
  Built from source
/usr/local/Cellar/openssl/1.0.2c (463 files, 17M)
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/openssl.rb
==> Dependencies
Build: makedepend ✔
==> Options
--universal
	Build a universal binary
--without-check
	Skip build-time tests (not recommended)
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash
```

**Comment by sodabrew** [comment]
Did Apple actually remove OpenSSL libraries from El Capitan?

**Comment by routelastresort** [comment]
@sodabrew [Re: OpenSSL -> Secure Transport for libevent2](http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html)

1.0.7 working for me, per @firedev's reminder, thanks!

**Comment by RipTheJacker** [comment]
@sodabrew Yes. The current openssl message states "This formula is keg-only. Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries".

**Comment by nacengineer** [comment]
For those that are using bundler this page may help

http://railsguides.net/passing-build-options-to-bundler/

**Comment by vassilevsky** [comment]
Another way of letting the compiler know about the non-standard OpenSSL include directory is running:

```
bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include
```

Then the next `bundle install` works fine.

**Comment by matthewbarram** [comment]
`gem install eventmachine -v '1.0.4' -- --with-cppflags=-I/usr/local/opt/openssl/include` worked for me too.

**Comment by bobintornado** [comment]
Love this quick solution. 
`gem install eventmachine -v '1.0.7' -- --with-cppflags=-I/usr/local/opt/openssl/include` 
worked for me too.

**Comment by jwg2s** [comment]
`gem install eventmachine -v '1.0.8' -- --with-cppflags=-I/usr/local/opt/openssl/include` worked for me as well with El Capitan

**Comment by KehindeAyanleye** [comment]
`gem install eventmachine -v '1.0.5' -- --with-cppflags=-I/usr/local/opt/openssl/include` worked for me with El Captain :dash:

**Comment by orien** [comment]
Should we also link to the homebrew installed library?
```
--with-cppflags="-I$(brew --prefix openssl)/include" --with-ldflags="-L$(brew --prefix openssl)/lib"
```

**Comment by bobintornado** [comment]
@orien yes I believed that's a good idea. Considering the fact that Apple has already deprecated OpenSSL.

**Comment by va3093** [comment]
`gem install eventmachine -v '1.0.4' -- --with-cppflags=-I/usr/local/opt/openssl/include` worked for me as well.

**Comment by romeroabelleira** [comment]
With openssl installed using Homebrew you can `brew link openssl --force` and then gem install will find the libs.

**Comment by sodabrew** [comment]
@orlen You are correct to also _link_ against the openssl that matches the header files.

I don't think we're doing anything unusual with data data structures or constants that might change between versions of OpenSSL, but header files do change sometimes and using mis-matching headers and libraries has a potential to be a problem.

**Comment by tinogomes** [comment]
<3

**Comment by itsNikolay** [comment]
@KehindeAyanleye 
I approve it works on El Captain. Tthanks. :+1:

**Comment by cjjuice** [comment]
:+1:

**Comment by mattleonard** [comment]
@vassilevsky - You the real MVP. Fixed my install issue with bundle!

**Comment by skunkworker** [comment]
`brew link openssl --force` fixed my issue completely. I'm on 10.11.1 with ruby 2.2.3.

**Comment by sirajudheenam** [comment]
gem install eventmachine -v '1.0.8' -- --with-cppflags=-I/usr/local/opt/openssl/include
worked for me. Thanks.

**Comment by mattheworiordan** [comment]
> brew link openssl --force fixed my issue completely. I'm on 10.11.1 with ruby 2.2.3.

Worked for me too, thanks :+1:

**Comment by sj26** [comment]
Since El Capitan removed openssl headers but left pkgconfig in place a nice way to do this now with openssl installed with homebrew is:

```
$ PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" gem install eventmachine
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.0.8
1 gem installed
```

**Comment by parkerl** [comment]
:+1: Thank you!

**Comment by sodabrew** [comment]
@sj26 That's a nice approach. Let's discuss in #661. I am going to lock this issue now.

**Comment by sodabrew** [comment]
Please try eventmachine-1.0.9, it should compile and install without error on El Capitan.
