### ISSUE TITLE
BuildError on Windows

### ISSUE THREAD

**Issue by Arcovion** [eventmachine/eventmachine#612]
I've been using eventmachine 1.0.7 successfully for months now, can't remember any problems installing initially.
Today I ran `bundle install --path vendor` and eventmachine wouldn't install. This seems to have now broken eventmachine on my whole system, as I just get this message: `Could not find eventmachine-1.0.7 in any of the sources`

I don't see how this can happen, my DevKit has never changed, I tried deleting the gem folder and the `Gemfile.lock`/`.bundle`/`vendor` dirs in the project but it makes no difference.

This is the error I get now when I run `gem install eventmachine` or `bundle`: http://pastebin.com/wqxBPhaB

**Comment by Arcovion** [comment]
Thanks, I pointed my `Gemfile` at `github: 'eventmachine'`, ran `bundle update` and now get this error:
http://pastebin.com/8H0t0UzZ

It's complaining that the forward declarations are out of date, see [new definition](https://github.com/eventmachine/eventmachine/commit/d2fb76a897781727f531671923e18840698bd80b#diff-7a2234b94ba3e902720efd3ff3ab7f65R137) vs [old definition](
https://github.com/eventmachine/eventmachine/blob/98b0d480091fd12a4a1f9294f75a5903d9215e06/ext/eventmachine.h#L51).

**Comment by sodabrew** [comment]
Thanks, you're absolutely right, I missed that header. I'll update later today or tomorrow.

**Comment by sodabrew** [comment]
I've updated the master branch, please try again today.

**Comment by sodabrew** [comment]
Ping for your testing please.

**Comment by Arcovion** [comment]
Installs fine now :+1:

**Comment by sodabrew** [comment]
Great feedback, thank you!
