### ISSUE TITLE
Release engineering for 1.0.8

### ISSUE THREAD

**Issue by sodabrew** [eventmachine/eventmachine#623]
Along with the Release notes, do a few regression tests. So far I've benched against thin, and memory usage stays flat. I'd like to wrap up and release this week.

/cc @tmm1

**Comment by tmm1** [comment]
:+1:

**Comment by sodabrew** [comment]
Overnight ab runs on Windows, OS X, Linux: memory and response times stable!
https://github.com/eventmachine/eventmachine/commit/1b27732855fa35b70cb9353cd332447c18b85e8e

**Comment by sodabrew** [comment]
And it's published! https://rubygems.org/gems/eventmachine/versions/1.0.8
