### ISSUE TITLE
ActiveRecord::ConnectionTimeoutError on rails model callbacks

### ISSUE THREAD

**Issue by alenteria** [eventmachine/eventmachine#626]
I am using EM.def in some of my rails Model callbacks and sometimes it throws error
ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds))

**Comment by sodabrew** [comment]
Please provide enough information for this bug report.

**Comment by alenteria** [comment]
My model Photo, has an attached file used with paperclip.
Theres a callback 'generate_watermarked_preview' on after_commit
I enclosed the watermark generation logic with Event Machine. 
It looks something like this
EM.run do
      non_blocking = proc do
        .. some codes here
      end
     EM.defer non_blocking
end
But if I uploaded many photos and this callback was being called many times, it throws this error
ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds))

**Comment by sodabrew** [comment]
Some related discussion: https://www.ruby-forum.com/topic/195010
I think the idea is that you may be creating / checking out new connections from the shared pool faster then you're checking them back in. Which database adapter are you using, btw?

**Comment by alenteria** [comment]
I am using postgresql.
Ok thanks @sodabrew. I'll read that forum.

**Comment by alenteria** [comment]
I solve it by making sure the connection pool has been released.
ActiveRecord::Base.connection_pool.release_connection

```ruby
EM.run do
      non_blocking = proc do
        begin
          .. some codes here
        ensure
           ActiveRecord::Base.connection_pool.release_connection
        end
     end
     EM.defer non_blocking
end
```

**Comment by sodabrew** [comment]
Good to hear! Do you think there's some documentation improvements you could suggest to help this situation?

**Comment by alenteria** [comment]
Yes, maybe you can provide more examples in more scenarios.
