### ISSUE TITLE
race condition of network io 

### ISSUE THREAD

**Issue by Gtar69** [eventmachine/eventmachine#631]
I'm trying to implement a TCP server by using event-machine but find some kinda like race condition between tcp connections with timer mechanism. My code is below: 

    require "eventmachine"
  
    class MyTCPServer < EM::Connection

      def post_init
        @timers = Timers::Group.new
        @timers.every(Setting::TIMER) do
          p "#{Time.now} on post init: ready to disconnect"
          self.unbind
        end
        Thread.new { @timers.wait }
      end

     def receive_data data
        if data.contains("register")
          p "registration success"
        elsif data.contains("heartbeat")
          @timers.pause
          @timers = Timers::Group.new
          @timers.every(Setting::TIMER) do
           p "#{Time.now} disconnection because of heartbeat timeout"
           self.unbind
          end
         Thread.new { @timers.wait }
          send_data("heartbeat")
       end
     end

      def unbind
         p "our connection is lost!"
         close_connection
      end
    end

    EventMachine.run do
      EventMachine.start_server "0.0.0.0", 10000, MyTCPServer
    end

For code above: if a client connect to server then disconnect and connect again ...etc console will show

register
our connection is lost 
register

However, sometimes if client trigger timeout => disconnect from server => then re-connect to server console will show =>

register  (1st connection registration)
register  (2nd connection registration)
our connection is lost (trigger 1st connection timer in tcp server by @timers) 

=> kinda of race condition
=> any sync mechanism for this ? Thanks a lot !

**Comment by tmm1** [comment]
EM is not thread-safe so you should not be using threads here.

Calling `unbind` is not allowed either, since `unbind` is a callback invoked by the reactor. You should be calling `close_connection` which will then cause `unbind` to get called, not the other way around.
