### ISSUE TITLE
Eventmachine throwing warnings when calling EM.epoll; EM.kqueue instead of no-op

### ISSUE THREAD

**Issue by wallyqs** [eventmachine/eventmachine#638]
It looks like it used to be the case that calling `EM.epoll` or `EM.kqueue` would be treated as a no-op when calling on a platform which didn't have the support for it (https://github.com/eventmachine/eventmachine/blob/master/docs/old/EPOLL#L42)
It seems that EM 1.0.8 changed this behavior (in this commit? https://github.com/eventmachine/eventmachine/commit/9af94064e1f05b373145ba0c3cac41daa9daf369) and now making those calls when support is not available throw warnings like this:

```
EM.epoll
# on OS X: warning: epoll is not supported on this platform

EM.queue
# Ubuntu: warning: kqueue is not supported on this platform
```

Does this change mean that libraries using EM should be checking for support first? e.g.

```ruby
      if EM.epoll?
        EM.epoll
      elsif EM.kqueue?
        EM.kqueue
      else
        Kernel.warn('Neither epoll nor kqueue are supported.')
      end  
```

Thanks.

**Comment by sodabrew** [comment]
I did this to align the code between `EM.epoll` and `EM.epoll = true`. The former would silently fail, the latter would warn. I could go back to the older behavior, and just document the difference, or maybe add a new variant like `EM.epoll!` that raises an exception if it cannot enable epoll.

**Comment by tmm1** [comment]
>       if EM.epoll?
>        EM.epoll

Unfortunately I think `EM.epoll?` means "is epoll enabled" not "is epoll available"

**Comment by tmm1** [comment]
> Unfortunately I think EM.epoll? means "is epoll enabled" not "is epoll available"

Never mind, I lied.

**Comment by livecube** [comment]
I'm seeing this warning "/Users/justinschier/.rvm/gems/ruby-2.2.2@livecube_r4/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:34: warning: epoll is not supported on this platform" when I run my rspec tests.

I'm definitely not calling EM.epoll anywhere directly. It must be happening through a gem, but I have no idea where. It would be great if I could at least see a stack trace where the call is happening. As it is right now, I have no idea what to do next to eliminate this message.

**Comment by sodabrew** [comment]
Sounds like I should revert from a warning back to being silent.

**Comment by sodabrew** [comment]
Will be deployed in 1.0.9

**Comment by wallyqs** [comment]
Thanks!
