### ISSUE TITLE
JRuby >= 9.0.0.0 no longer has getDescriptorByFileno method

### ISSUE THREAD

**Issue by gellaho** [eventmachine/eventmachine#642]
It looks like `JRuby.runtime.getDescriptorByFileno` is being used for something in the `attach_io` method.

This method was deprecated in JRuby 1.7..20 (http://jruby.org/apidocs/org/jruby/RubyIO.html#getDescriptorByFileno%28int%29) and it looks like it has been removed entirely from JRuby 9.0.0.0 and above.
![screen shot 2015-09-29 at 4 30 05 pm](https://cloud.githubusercontent.com/assets/3290267/10404524/3ee127c6-6ea1-11e5-8a03-7a9b06e99d89.png)
The problematic code is shown below:
```ruby
# lib/eventmachine.rb
# @private
  def EventMachine::attach_io io, watch_mode, handler=nil, *args
    klass = klass_from_handler(Connection, handler, *args)

    if !watch_mode and klass.public_instance_methods.any?{|m| [:notify_readable, :notify_writable].include? m.to_sym }
      raise ArgumentError, "notify_readable/writable with EM.attach is not supported. Use EM.watch(io){ |c| c.notify_readable = true }"
    end

    if io.respond_to?(:fileno)
      fd = defined?(JRuby) ? JRuby.runtime.getDescriptorByFileno(io.fileno).getChannel : io.fileno
    else
      fd = io
    end
...
```
I would offer a solution, but I'm not entirely sure what this method does.

**Comment by mattclar** [comment]
Hi I am also running into this problem with JRuby 9000, would appreciate some kind of workaround :)

**Comment by mattclar** [comment]
So I think I was able to get past this error by manually editing the gemfiles so as to remove the reference to getDescriptorByFileno()
so this:
    if io.respond_to?(:fileno)
      fd = defined?(JRuby) ? JRuby.runtime.getDescriptorByFileno(io.fileno).getChannel : io.fileno
    else

is now this:
    if io.respond_to?(:fileno)
      fd = io.fileno
    else

**Comment by sodabrew** [comment]
Thanks very much for hacking on this! It sounds like JRuby 9000 has implemented more wrappers than JRuby 1.x used to have. I'll see about a portable way to write this code for both version families.

**Comment by mattclar** [comment]
No idea what I did to be honest just followed my nose around, without any real understanding of the code. I am presuming it will break in some situations but as you said its a good hack until then :)
