### ISSUE TITLE
Installation failed with error

### ISSUE THREAD

**Issue by anantasur** [eventmachine/eventmachine#652]
<pre><code>Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/ananthu/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151029-92132-1ndxkd6.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for pipe2() in unistd.h... no
checking for accept4() in sys/socket.h... no
checking for SOCK_CLOEXEC in sys/socket.h... no
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
CFLAGS=-O3 -I/Users/haven/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe  -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
CPPFLAGS=-D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT $(DEFS) $(cppflags) -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
./project.h:116:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/ananthu/.rvm/gems/ruby-2.2.3@step_management/gems/eventmachine-1.0.8 for inspection.
Results logged to /Users/ananthu/.rvm/gems/ruby-2.2.3@step_management/extensions/x86_64-darwin-14/2.2.0-static/eventmachine-1.0.8/gem_make.out</code></pre>

**Comment by sodabrew** [comment]
With OS X El Capitan, Apple no longer provides OpenSSL headers. You can install OpenSSL using either HomeBrew or MacPorts.

**Comment by anantasur** [comment]
i already have open ssl installed on my machine

which openssl   
/usr/bin/openssl

**Comment by zhimin** [comment]
I experience the same issue ('openssl/ssl.h' file not found), had openssl installed with HomeBrew.  Another gem passenger had the same issue with OS X El Capitan, fixed in 5.0.21.

**Comment by sodabrew** [comment]
@anantasur With OS X El Capitan, Apple no longer provides OpenSSL headers. You can install your own OpenSSL using either HomeBrew or MacPorts.

**Comment by sodabrew** [comment]
Thanks for the tip about Passenger! The commit is here https://github.com/phusion/passenger/commit/c843757fd80347bc84e2a89d16af8c83e63d3943 and the actual OpenSSL detection code is pretty straightforward.

**Comment by jcanales** [comment]
Hi there im on "El Capitan" using macports and getting the same error

**Comment by wa0x6e** [comment]
For macport, try with 

    gem install eventmachine -v '1.0.8' -- --with-cppflags=-I/opt/local/include

Works for me

```
Building native extensions with: '--with-cppflags=-I/opt/local/include'
This could take a while...
Successfully installed eventmachine-1.0.8
1 gem installed
```

**Comment by jcanales** [comment]
Tnx @wa0x6e  it worked like a charm.

**Comment by sodabrew** [comment]
Please try eventmachine-1.0.9, it should compile and install without error on El Capitan.
