### ISSUE TITLE
Tests require Internet access

### ISSUE THREAD

**Issue by davexunit** [eventmachine/eventmachine#656]
The test suite tries to connect to google.com for some of the tests, causing the test suite to fail if there is no Internet connection or there is a transient networking issue, which is rather brittle.  It would be good if such tests were skipped in the event that google.com does not resolve, and even better if the tests didn't require network access at all, assuming only the local loopback device.  Thoughts?

**Comment by sodabrew** [comment]
Significant progress on removing third-party sites from tests in #749.
