### ISSUE TITLE
error of dk.rb installing

### ISSUE THREAD

**Issue by rajitha23** [eventmachine/eventmachine#657]
please help me for this error..

C:\DevKit>dk.rb install
[INFO] Skipping existing gem override for 'C:/Ruby200'
[WARN] Skipping existing DevKit helper library for 'C:/Ruby200'

C:\DevKit>

**Comment by sodabrew** [comment]
That's a warning, not an error, and it looks like you don't have a problem in the first place.

Perhaps you can seek help on the RubyInstaller mailing list if you need further assistance? https://groups.google.com/forum/#!forum/rubyinstaller
