### ISSUE TITLE
Tests not very reliable

### ISSUE THREAD

**Issue by verxx** [eventmachine/eventmachine#666]
Jobs fail randomly on travis-ci. Have to resubmit multiple times to get tests to pass. Example failures:
https://travis-ci.org/eventmachine/eventmachine/jobs/97323621
https://travis-ci.org/eventmachine/eventmachine/jobs/97299923
https://travis-ci.org/eventmachine/eventmachine/jobs/97323630
https://travis-ci.org/eventmachine/eventmachine/jobs/97323623

**Comment by sodabrew** [comment]
Thank you for the nudge on this, I have improved the situation over the past few months.
