### ISSUE TITLE
Can not install with ruby compiled on OS X 10.10

### ISSUE THREAD

**Issue by dwfait** [eventmachine/eventmachine#667]
./configure --with-openssl-dir=`brew --prefix openssl` && make && make install && gem install eventmachine gives output of https://gist.github.com/dwfait/9af1d6dbadac07da057a and a mkmf.log of https://gist.github.com/dwfait/8e2a7309550bbc93cbda

pkg-config seems to be returning nothing (wrong pkg-config or pkg-config is pointing to the wrong openssl?)

Am I doing something wrong? Or is this an issue in how eventmachine's extconf configures itself?

**Comment by sodabrew** [comment]
This is the best way to compile right now: https://github.com/eventmachine/eventmachine/issues/661#issuecomment-165227146

```
$ PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2d_1/lib/pkgconfig gem install eventmachine
```

**Comment by dwfait** [comment]
Sorry, should have mentioned that I had found that post and have tried. My path is a little different, but 

`PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2e/lib/pkgconfig gem install eventmachine` results in the same issue.

**Comment by dwfait** [comment]
Running with `--without-pkg-config` gets me a bit further: https://gist.github.com/dwfait/864e211c0e9c01493eeb

Compile errors because it appears the `#define`s think I'm running on ruby < 1.9.

**Comment by sodabrew** [comment]
Yes, this is very odd. Do you have two sets of Ruby headers in your include path?
```
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
em.cpp:1057:6: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
                                        EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^~~~~~~~
                                        rb_thread_fd_select
./em.h:29:22: note: expanded from macro 'EmSelect'
    #define EmSelect rb_thread_select
                     ^
/usr/local/include/ruby-2.4.0/ruby/intern.h:459:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
```

**Comment by sodabrew** [comment]
Oh, are you compiling against ruby-head? `/usr/local/include/ruby-2.4.0/ruby/intern.h` -- there is no ruby 2.4 release yet -- maybe there was a bug at the time you pulled from head, or breaking change coming up?

**Comment by sodabrew** [comment]
Are you still seeing this problem, or can the ticket be closed now?
