### ISSUE TITLE
compile issue openssl AIX 7.1

### ISSUE THREAD

**Issue by ddaka** [eventmachine/eventmachine#678]
I'm having issues installing  eventmachine on AIX 7.1 ruby 2.3 , openssl is  installed also compiled ruby with openssl

[root@test]/opt/ruby/bin# ./gem install /home/ddaka/eventmachine-1.0.9.1.gem
Building native extensions.  This could take a while...
ERROR:  Error installing /home/ddaka/eventmachine-1.0.9.1.gem:
        ERROR: Failed to build gem native extension.

    current directory: /opt/ruby/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/ext
/opt/ruby/bin/ruby -r ./siteconf20160118-39059958-1qh0xub.rb extconf.rb
checking for main() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/ruby/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/opt/ruby/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /opt/ruby/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `each'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/ruby/lib/ruby/gems/2.3.0/extensions/powerpc-aix-7/2.3.0-static/eventmachine-1.0.9.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/ruby/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /opt/ruby/lib/ruby/gems/2.3.0/extensions/powerpc-aix-7/2.3.0-static/eventmachine-1.0.9.1/gem_make.out

[root@test]/opt/ruby/bin# cat /opt/ruby/lib/ruby/gems/2.3.0/extensions/powerpc-aix-7/2.3.0-static/eventmachine-1.0.9.1/mkmf.log
....
package configuration for openssl is not found

################

[root@test]/opt/ruby/bin# ./ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [powerpc-aix7.1.3.0]

[root@test]/opt/ruby/bin# ls  /usr/include/openssl/ 
aes.h          cmac.h         dso.h          hmac.h         objects.h      pqueue.h       srtp.h         ts.h
asn1.h         cms.h          dtls1.h        krb5_asn.h     ocsp.h         rand.h         ssl.h          txt_db.h
asn1_mac.h     comp.h         e_os2.h        kssl.h         opensslconf.h  rc2.h          ssl2.h         ui.h
asn1t.h        conf.h         ebcdic.h       lhash.h        opensslv.h     rc4.h          ssl23.h        ui_compat.h
bio.h          conf_api.h     ec.h           md2.h          ossl_typ.h     ripemd.h       ssl3.h         whrlpool.h
blowfish.h     crypto.h       ecdh.h         md4.h          pem.h          rsa.h          stack.h        x509.h
bn.h           des.h          ecdsa.h        md5.h          pem2.h         safestack.h    store.h        x509_vfy.h
buffer.h       des_old.h      engine.h       mdc2.h         pkcs12.h       seed.h         symhacks.h     x509v3.h
camellia.h     dh.h           err.h          modes.h        pkcs7.h        sha.h          tls1.h
cast.h         dsa.h          evp.h          obj_mac.h      pq_compat.h    srp.h          tmdiff.h

**Comment by sodabrew** [comment]
Could you try installing eventmachine 1.2.0.dev.2 and see if it builds out of the box?

**Comment by portertech** [comment]
I just spent an afternoon trying to build Sensu AIX packages, we ran into this https://github.com/eventmachine/eventmachine/pull/693

**Comment by sodabrew** [comment]
Aha, sold.
