### ISSUE TITLE
start_tls method not obeying specified cipher list

### ISSUE THREAD

**Issue by tubsandcans** [eventmachine/eventmachine#679]
I'm using EventMachine 1.0.9.1, which claims to have support for the :cipher_list option in start_tls.
start_tls(:cipher_list => 'ALL:!ECDHE:@STRENGTH') is how I'm calling it.
I can verify this is a correct openssl cipher list string by running `openssl ciphers -v 'ALL:!ECDHE:@STRENGTH'` and verifying that no ECDHE ciphers are present. 
Using wireshark I still see ECDHE ciphers in the client hello, and the same total number of ciphers that get sent without any specification of cipher_list.

**Comment by sodabrew** [comment]
EventMachine 1.0.9.1 does not have this feature, it will be in the upcoming EM 1.2 release.

**Comment by tubsandcans** [comment]
Thanks for the clarification. If it is not supported in any current EM release then why is it documented in http://www.rubydoc.info/github/eventmachine/eventmachine/EventMachine/Connection:start_tls ?

**Comment by sodabrew** [comment]
The docs site appears to be pulling from the master branch, and this new feature is in the master branch.
