### ISSUE TITLE
Unable to install event machine (as dependency of AMQP) thru bundler

### ISSUE THREAD

**Issue by mohitjagga** [eventmachine/eventmachine#680]
Linux Version: Linux 3.10.0-327.3.1.el7.x86_64 x86_64

Here is the full error trace:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

 current directory: /home/ab2-user/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/ext

/home/ab2-user/.rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160125-16950-1610icm.rb extconf.rb

checking for main() in -lcrypto... yes

checking for main() in -lssl... yes

checking for openssl/ssl.h... yes

checking for openssl/err.h... yes

checking for rb_trap_immediate in ruby.h,rubysig.h... no

checking for rb_thread_blocking_region()... no

checking for ruby/thread.h... yes

checking for rb_thread_call_without_gvl() in ruby/thread.h... yes

checking for inotify_init() in sys/inotify.h... yes

checking for writev() in sys/uio.h... yes

checking for rb_thread_fd_select()... yes

checking for rb_fdset_t in ruby/intern.h... yes

checking for pipe2() in unistd.h... yes

checking for accept4() in sys/socket.h... yes

checking for SOCK_CLOEXEC in sys/socket.h... yes

checking for rb_wait_for_single_fd()... yes

checking for rb_enable_interrupt()... no

checking for rb_time_new()... yes

checking for sys/event.h... no

checking for epoll_create() in sys/epoll.h... yes

checking for clock_gettime()... yes

checking for CLOCK_MONOTONIC_RAW in time.h... yes

checking for CLOCK_MONOTONIC in time.h... yes

CXXFLAGS=$(cxxflags)

creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ab2-user/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/eventmachine-1.0.9.1/mkmf.log

current directory: /home/ab2-user/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/ext

make "DESTDIR=" clean

current directory: /home/ab2-user/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/ext

make "DESTDIR="

compiling binder.cpp

make: g++: Command not found

make: *** [binder.o] Error 127

make failed, exit code 2

Gem files will remain installed in /home/ab2-user/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1 for inspection.

Results logged to /home/ab2-user/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/eventmachine-1.0.9.1/gem_make.out

An error occurred while installing eventmachine (1.0.9.1), and Bundler cannot continue.

Make sure that `gem install eventmachine -v '1.0.9.1'` succeeds before bundling.

**Comment by mohitjagga** [comment]
Also I tried to install eventmachine standalone and it failed

**Comment by sodabrew** [comment]
`make: g++: Command not found` -- you'll need a C++ compiler installed.

**Comment by constantlearner** [comment]
thanks thats solves!

**Comment by mohitjagga** [comment]
Thanks a lot! Issue has been resolved.
