### ISSUE TITLE
Release 1.2.0.dev.1 as a gem

### ISSUE THREAD

**Issue by rwz** [eventmachine/eventmachine#682]
Hi,

I've been building a tool that is using EventMachine as a dependency and my tool needs SNI SSL support. This support has been added in 1.2.0 branch and I've verified that it seems to be working fine on 1.2.0.dev.1. Now, the problem is that 1.2.0.dev.1 is not released as a gem and I have to manually specify github path/tag in my Gemfile to make it work.

Could you please release 1.2.0.dev.1 to rubygems? It'll be marked as unstable release and won't be pulled in by default by bundler or by running `gem update` unless you manually specify it, so I assume it should be safe.

**Comment by sodabrew** [comment]
Yes, this is the plan to release a dev gem.

**Comment by sodabrew** [comment]
EventMachine 1.2.0.dev.2 was posted a few weeks ago, and now EventMachine 1.2.0 final has been posted!
