### ISSUE TITLE
cannot install on yosemite with ruby 2.2.3

### ISSUE THREAD

**Issue by maysam** [eventmachine/eventmachine#686]
with ruby 2.2.3 on yosemite

MacBook-Air:BHP maysam$ gem install eventmachine
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/maysam/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20160213-72982-1fu9hur.rb extconf.rb
checking for main() in -lcrypto... yes
checking for main() in -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for pipe2() in unistd.h... no
checking for accept4() in sys/socket.h... no
checking for SOCK_CLOEXEC in sys/socket.h... no
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
checking for clock_gettime()... no
checking for gethrtime()... no
CXXFLAGS=$(cxxflags) -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result -Wno-address
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
compiling kb.cpp
compiling page.cpp
compiling pipe.cpp
compiling rubymain.cpp
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1238:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1239:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1258:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1259:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1298:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1299:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1318:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:1319:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:3695:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:3696:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:3804:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:3805:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:3823:suffix or operands invalid for `movq'
/var/folders/96/prf6_dl55pjb37__39yv6p3h0000gp/T//ccpatxtn.s:3824:suffix or operands invalid for `movq'
Makefile:229: recipe for target 'rubymain.o' failed
make: *** [rubymain.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/maysam/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /Users/maysam/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/eventmachine-1.0.9.1/gem_make.out

**Comment by sodabrew** [comment]
This looks related: https://github.com/libressl-portable/portable/issues/121
Could be a mismatch of the compiler vs. the binutils linker?
Are you still seeing this problem?

**Comment by sodabrew** [comment]
Close due to lack of updates.
