### ISSUE TITLE
Cannot install on El Capital with ruby-2.3.0

### ISSUE THREAD

**Issue by bangn** [eventmachine/eventmachine#688]
Got following error when install `eventmachine` on El Capitan with `ruby-2.3.0`

```
An error occurred while installing eventmachine-le (1.1.7.2), and Bundler cannot continue.│
Make sure that `gem install eventmachine-le -v '1.1.7.2'` succeeds before bundling.
```
NOTE: 
* I already run `brew link openssl --force`
* It can be installed using `ruby-2.1.2`

**Comment by sodabrew** [comment]
The EventMachine-LE fork is known not to work on El Capitan. If you rely on the additional SSL or IPv6 features in EventMachine-LE, you'll be blocked on me to finish up and release EventMachine 1.2.0, which merges back the work from the LE fork. If you don't need EventMachine-LE specifically, then you can switch back to mainline EventMachine 1.0.x, which does work on El Capitan.

**Comment by bangn** [comment]
Thank you for your answer. However, I can installed that with ruby-2.1.2.

**Comment by sodabrew** [comment]
Would you be able to try moving from EventMachine-LE to EventMachine version 1.2.0.dev.2 (which is likely to become the final 1.2.0 release, despite the .dev. naming) and let me know if you see any problems? The next version of EventMachine, 1.2.0, will incorporate most of the work from EventMachine-LE 1.1.x.

**Comment by bangn** [comment]
Thanks @sodabrew. I will use it with `ruby 2.1.2` at this time and wait for the release of new version

**Comment by sodabrew** [comment]
I've just posted EventMachine 1.2.0, please give it a try!

**Comment by bangn** [comment]
It works. Thank you very much @sodabrew. Much appreciate it
