### ISSUE TITLE
Add required_ruby_version item in the .gemspec file

### ISSUE THREAD

**Issue by flowmemo** [eventmachine/eventmachine#691]
The .gemspec file don't contain "required_ruby_version" item. 
The gem page of eventmachine shows "Required Ruby Version: >= 0", which is very misleading. 
When I tried to install  eventmachine in a  unsupported ruby version, it just showed compiler errors.

Thx.

**Comment by sodabrew** [comment]
What version of Ruby is throwing errors?

I have the eventmachine tests on Travis running on every Ruby from 1.8.7 to 2.3.0.

**Comment by flowmemo** [comment]
Sorry, it was my mistake...The real cause was my wrong rbenv and gem settings in ruby 2.2.4.

When I met the compilation error in ruby 2.2.4, I found the README.md said "EventMachine supports Ruby >= 1.8.7 and <= 2.2 REE". Then I installed EM in ruby 2.1.8 successfully. So I mistakenly thought it was a compatibility issue.

Thx.

**Comment by sodabrew** [comment]
Glad to hear the resolution!

I will update the readme :)
