### ISSUE TITLE
Infinite loop on AIX 6.1

### ISSUE THREAD

**Issue by amdprophet** [eventmachine/eventmachine#695]
I seem to be running into an infinite loop with EventMachine on AIX 6.1. I've tracked the issue down to this line: https://github.com/eventmachine/eventmachine/blob/master/ext/binder.cpp#L35. I'm not strong with C++ but won't this always produce an infinite loop on any platform?

**Comment by portertech** [comment]
Confirmed that `Bindable_t::CreateBinding()` is called on other platforms. Looks like a max num?

**Comment by amdprophet** [comment]
I came across this: https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000014628469

I think it may be an issue with the implementation of map on AIX.

**Comment by sodabrew** [comment]
Could you give EventMachine 1.2.0 a try? I don't think there's been any change that would have fixed this issue, but I'd like to confirm that it is still a bug. What version of EM were you using originally, by the  way?

**Comment by sodabrew** [comment]
@portertech Should we keep this open to debug on AIX, or is your work on the pure-ruby reactor sufficient to get Sensu up and running on AIX? I will prioritize the next 1.2.1 release for your pure-ruby reactor work if that's the case.

**Comment by amdprophet** [comment]
I had meant to update this issue awhile ago but I seem to have forgotten. EventMachine 1.2.0 did not resolve the issue. The pure-ruby SSL/TLS changes were a workaround to this issue and pure-ruby has been working well. I don't have any plans to revisit the use of native EM on AIX and there's a chance the issue we found was environmental.
