### ISSUE TITLE
100% CPU usage, seems to be stuck in RunOnce loop

### ISSUE THREAD

**Issue by UberMouse** [eventmachine/eventmachine#696]
Hi,

We run our production API (a Rails application) through Thin. Starting last October we've seen much-increased CPU usage from our servers and it seems to be because the API thins slowly climb to 100% CPU usage over a period of a few hours (it varies for each running server, usually one or two happen quickly and then after a few hours 10+ of the 16 are at 100%). If we stop sending traffic to them the CPU usage on the ones at 100% stays at 100% but the ones at a more reasonable level (around 10%) drop down to 0%, as they should be since they aren't serving traffic. 

The problem seems to be inside event-machine but I'm not sure if it's thins usage of EM or EM itself so I've raised this issue both here and on the Thin github (see macournoyer/thin#299).

Anything I can do to try and resolve this problem/find out more about it? I've tried looking at the process with strace and gdb and it seems to be stuck in a busy-loop in the eventmachine em.cpp RunOnce loop.

**Comment by sodabrew** [comment]
Could you specify the exact version of thin, eventmachine, ruby, and platform you are on?

**Comment by UberMouse** [comment]
Thin: 1.6.4
Eventmachine: 1.0.9.1
Ruby: 1.9.3-p484
Platform: CentOS 6.5

**Comment by sodabrew** [comment]
_hmm_ :8ball:

**Comment by sodabrew** [comment]
When this happens to a process, could you run `strace -p` on this pid to see if it is stuck in a loop of calling any system calls?

**Comment by UberMouse** [comment]
In the 5-10 seconds I had strace attached to one of the thin processes it logged 423,000 lines of systemcalls. I've trimmed that to 10,000 https://gist.github.com/UberMouse/ac430b93af7dc85927d4

**Comment by sodabrew** [comment]
Could you test the just-released EventMachine 1.2.0 to see if the issue still triggers?

**Comment by sodabrew** [comment]
Any luck with EventMachine 1.2.0?

**Comment by UberMouse** [comment]
Doesn't seem to have helped. I only did the production deploy with the updated 1.2.0 version of eventmachine about an hour ago but we already have 2 thin servers stuck at 100% CPU.

**Comment by sodabrew** [comment]
Would you be willing to deploy older versions, specifically EM 1.0.7 and 1.0.8, to try and narrow down the timeframe when this bug may have been introduced?

**Comment by UberMouse** [comment]
My bad, I did the deploy incorrectly and it was actually still running 1.0.9.1 before. I noticed and changed it to 1.2.0 and there were no thins at 100% CPU when I left for the day, so I'm thinking it may actually have fixed it. I'll see if this stays true tomorrow and close the issue if it's resolved.

Thanks!

**Comment by UberMouse** [comment]
Fix is looking great! https://i.imgur.com/XsI2wbx.png

**Comment by sodabrew** [comment]
Fantastic!! Thanks for confirming!

**Comment by xxlee** [comment]
@sodabrew, seems we met similar issue as @UberMouse and we're using the 1.0.8; could you help briefly explain the root cause of this issue?
The interest thing is that we run several process on the machine (each process on different CPU core) and only some of the process met the issue.
We will upgrade to 1.2.0 to have a try, and if you can help briefly explain the root cause of the issue will be appreciated.
Thanks.
