### ISSUE TITLE
SmtpServer rejects valid MAIL FROM command (from Trac)

### ISSUE THREAD

**Issue by jakedouglas** [eventmachine/eventmachine#7]
Moved from Trac
=============

Quoting rfc 2821:

   The MAIL command (or the obsolete SEND, SOML, or SAML commands)
   begins a mail transaction.  Once started, a mail transaction consists
   of a transaction beginning command, one or more RCPT commands, and a
   DATA command, in that order.  A mail transaction may be aborted by
   the RSET (or a new EHLO) command.  There may be zero or more
   transactions in a session.  MAIL (or SEND, SOML, or SAML) MUST NOT be
   sent if a mail transaction is already open, i.e., it should be sent
   only if no mail transaction had been started in the session, or it
   the previous one successfully concluded with a successful DATA
   command, or if the previous one was aborted with a RSET.

SmtpServer#process_mail_from? currently violates the last paragraph, rejecting a second MAIL FROM command even after DATA succeded.

**Comment by sodabrew** [comment]
This was fixed by #351.
