### ISSUE TITLE
Cannot install v1.2.0.1 on CentOS 5.5

### ISSUE THREAD

**Issue by gremz** [eventmachine/eventmachine#709]
Hello,

I am attempting to install eventmachine v1.2.0.1 but continue to get the error below. Is a minimal OpenSSL version required? 

I am trying to get this working on a rather dated CentOS release 5.5 server with OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008.

Thanks,
Greg

> -bash-3.2$ gem install eventmachine -v '1.2.0.1'                                                                                                                                                                                              
> Building native extensions.  This could take a while...
> ERROR:  Error installing eventmachine:
>         ERROR: Failed to build gem native extension.
> 
> /usr/local/rbenv/versions/2.1.2/bin/ruby extconf.rb
> \-----
> Using OpenSSL from pkg-config -I/usr/kerberos/include && -L/usr/kerberos/lib64 && -lssl -lcrypto -ldl -lz
> \-----
> checking for main() in -lcrypto... yes
> checking for main() in -lssl... yes
> checking for openssl/ssl.h... yes
> checking for openssl/err.h... yes
> checking for rb_trap_immediate in ruby.h,rubysig.h... no
> checking for rb_thread_blocking_region()... yes
> checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
> checking for rb_thread_fd_select()... yes
> checking for rb_fdset_t in ruby/intern.h... yes
> checking for rb_wait_for_single_fd()... yes
> checking for rb_enable_interrupt()... no
> checking for rb_time_new()... yes
> checking for inotify_init() in sys/inotify.h... yes
> checking for writev() in sys/uio.h... yes
> checking for pipe2() in unistd.h... no
> checking for accept4() in sys/socket.h... no
> checking for SOCK_CLOEXEC in sys/socket.h... no
> checking for sys/event.h... no
> checking for epoll_create() in sys/epoll.h... yes
> checking for clock_gettime()... yes
> checking for CLOCK_MONOTONIC_RAW in time.h... no
> checking for CLOCK_MONOTONIC in time.h... yes
> CXXFLAGS=$(cxxflags) -Wall -Wextra -Wno-deprecated-declarations
> creating Makefile
> 
> make "DESTDIR=" clean
> 
> make "DESTDIR="
> compiling cmain.cpp
> compiling kb.cpp
> compiling em.cpp
> compiling ed.cpp
> compiling rubymain.cpp
> compiling ssl.cpp
> ssl.cpp: In constructor ‘SslBox_t::SslBox_t(bool, const std::string&, const std::string&, bool, bool, const std::string&, const std::string&, const std::string&, const std::string&, int, uintptr_t)’:
> ssl.cpp:333: error: ‘SSL_set_tlsext_host_name’ was not declared in this scope
> make: *** [ssl.o] Error 1
> 
> make failed, exit code 2
> 
> Gem files will remain installed in /usr/local/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/eventmachine-1.2.0.1 for inspection.
> Results logged to /usr/local/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/eventmachine-1.2.0.1/gem_make.out
>

**Comment by gorttman** [comment]
I have the exact same issue. Installing later ssl causes too many dependency issues so far.

**Comment by gorttman** [comment]
As a further note, We are on 5.11. Any form of upgrade / update would have to be by hand. No possibility to do a major version uplift

**Comment by sodabrew** [comment]
You could pin to EventMachine < 1.2. This function has been present in OpenSSL since 0.9.8f (just a micro past the version that's locked into RHEL 5, ugh!)

**Comment by sodabrew** [comment]
Hi, is it sufficient for you to pin your application to `gem 'eventmachine', '< 1.2'`?

**Comment by bcg62** [comment]
Also, having this issue on 5.9. Installing version 1.0.9.1 works but its not ideal.

**Comment by kyoshidajp** [comment]
If you haven't installed openssl-devel package yet,  you should install it.

```
sudo yum -y install openssl-devel
```
