### ISSUE TITLE
Building EventMachine on Alpine

### ISSUE THREAD

**Issue by vrinek** [eventmachine/eventmachine#710]
I've been using Docker recently and just migrated a small Sinatra app (served by Thin) from the Ubuntu base image to the Alpine one.

I had to add the following packages to get it to compile the native extensions: `apk add g++ musl-dev make`.

I assume this may come in handy for someone else who wants to use the same base image but I'm not sure where to put this info.

The [wiki page](https://github.com/eventmachine/eventmachine/wiki/Building-EventMachine) is pretty generic. Should I add it there?

**Comment by sodabrew** [comment]
Yes, please feel free to add these recommended packages for Alpine Linux items to the wiki page.

**Comment by vrinek** [comment]
Added: https://github.com/eventmachine/eventmachine/wiki/Building-EventMachine#docker-rubyalpine

**Comment by sodabrew** [comment]
Thanks!

**Comment by tomav** [comment]
Thank you @vrinek

**Comment by Gimi** [comment]
Glad found this when I encountered the same issue. However, it should use the "--no-cache" option, so we get "apk add --no-cache g++ musl-dev make".

**Comment by soylent** [comment]
You can also reduce your Docker image size by 150 MiB by removing build dependencies.

```
RUN apk --no-cache add --virtual .eventmachine-builddeps g++ make \
  && bundle install --deployment --without test development \
  && apk del .eventmachine-builddeps
```

**Comment by svenagnew** [comment]
@epergo - surely that would make them runtime dependencies and not build dependencies then? Are you certain eventmachine requires those packages to be present during execution?

**Comment by chulkilee** [comment]
`libstdc++` is required for runtime. I updated https://github.com/eventmachine/eventmachine/wiki/Building-EventMachine
