### ISSUE TITLE
Using watch_file for code reloading.

### ISSUE THREAD

**Issue by abonec** [eventmachine/eventmachine#714]
It's possible to use this method for dynamic code reloading when it's changed during development?

I use code snippet like this:

```
    Dir[Bundler.root.join('**/*.rb').to_s].each do |file|
      EM.watch_file file, CodeReloader
    end
```

And my idea was load every *.rb file that changed. But every file edited by editor looks like this:

```
/home/abonec/sandbox/url_checker/start_server.rb moved
/home/abonec/sandbox/url_checker/start_server.rb deleted
/home/abonec/sandbox/url_checker/start_server.rb monitoring ceased
```

**Comment by sodabrew** [comment]
What editor are you using? It looks like it is doing an atomic-rename operation from a temp file onto the original source file for each save (rename/move is one of the few atomic operations in POSIX file system semantics). The file watcher code is tied to the "inode" of the file, which means it keeps track of the original file, even as it gets moved away and deleted.

You could use a moved/deleted event to trigger a look to see if there is a new file at the same location as the file that was just deleted, and then add the new file into your watch list and reload its contents.

**Comment by abonec** [comment]
I use vim and intellij idea and effect the same.
