### ISSUE TITLE
eventmachine-1.2.0.1 Encryption not available on this event-machine osx

### ISSUE THREAD

**Issue by aadams22** [eventmachine/eventmachine#716]
Operating System: Mac OS X
Running: Ruby 2.2.3

`Successfully installed eventmachine-1.2.0.1`

I am using this together with the faye-websocket and am continuously receiving this error:

`$ bundle exec ruby shield.rb
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Encryption not available on this event-machine
Abort trap: 6`

I'm a bit stumped on how to fix this at this point

**Comment by sodabrew** [comment]
You're probably on OS X 10.11 El Capitan. This no longer provides user-accessible headers for the system OpenSSL library. If you install OpenSSL with either HomeBrew or MacPorts, and then reinstall eventmachine, it will use the library from /usr/local (HomeBrew) or /opt/local (MacPorts).

**Comment by sodabrew** [comment]
Ping to close issue or follow-up?

**Comment by aadams22** [comment]
Thank you. You were absolutely correct. 
I installed OpenSSL using homebrew  ```/usr/local/Cellar/openssl```

and successfully installed eventmachine into my local gems:

```$ KG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" sudo gem install  eventmachine

Building native extensions.  This could take a while...
Successfully installed eventmachine-1.2.0.1
1 gem installed```

I run a successful bundle install into my application:

```$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using addressable 2.4.0
Using unf_ext 0.0.7.2
Using eventmachine 1.2.0.1
Using websocket-extensions 0.1.2
Using http-form_data 1.0.1
Using http_parser.rb 0.6.0
Using json 1.8.3
Using bundler 1.11.2
Using unf 0.1.4
Installing websocket-driver 0.6.4 with native extensions
Using domain_name 
Installing faye-websocket 0.10.4
Using http-cookie 1.0.2
Using http 2.0.1
Bundle complete! 3 Gemfile dependencies, 14 gems now installed.```

However I am still receiving the same error when attempting to run my application:

```$ bundle exec ruby shield.rb
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Encryption not available on this event-machine
Abort trap: 6```

**Comment by sodabrew** [comment]
The line `Using eventmachine 1.2.0.1` means it did not recompile. Blow away your bundle directory and re-install.

**Comment by sodabrew** [comment]
Did my bundle suggestion resolve the issue?

**Comment by ashleyyy** [comment]
I am having the same issue and no, sodabrew's suggestion did not work.

`Using eventmachine 1.0.8 with native extensions`

**Comment by sodabrew** [comment]
@ashleyyy Please describe your full situation, I don't want to make any assumptions about how closely your scenario matches the OP. The single line you've posted is enough information to say that you _haven't_ recompiled eventmachine in that particular run of `bundle install` but no more.

**Comment by ashleyyy** [comment]
I ran bundle install and it installed `eventmachine 1.2.0.1`
Then I installed openssl using homebrew, removed eventmachine and ran bundle install again, which installed `eventmachine 1.0.8`

```[...]
Using thor 0.19.1
Using concurrent-ruby 1.0.0
Using connection_pool 2.2.0
Using diff-lcs 1.2.5
Installing eventmachine 1.0.8 with native extensions
Using multipart-post 2.0.0
Using oj 2.14.3
Using websocket-extensions 0.1.2
Using gli 2.13.4
Using tilt 2.0.2
[...]```

The error message I am getting is `terminating with uncaught exception of type std::runtime_error: Encryption not available on this event-machine
Abort trap: 6`

**Comment by sodabrew** [comment]
Ok, so you appear to have a system-wide eventmachine 1.0.8. If you run `gem list` do you see eventmachine 1.0.8 in the output?

If you do, try adding this option to bundle install:
```
bundle install --path vendor/bundle
```

This will prevent system gems from being used in the local bundle.

**Comment by ashleyyy** [comment]
which version should I be trying to get in the local bundle?

I do have 1.0.8 globally, ran bundle install with that option, and...same error message.

Thanks for your help so far!

**Comment by sodabrew** [comment]
Your eventmachine 1.0.8 globally is built without SSL. Do you want a global eventmachine gem? Either rebuild it with SSL, or remove it.

**Comment by sb8244** [comment]
@aadams22 Is it due to the typo of PKG? Running all of your commands, except with the following, worked for me.

```
PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" gem install eventmachine
```

**Comment by sFrenkie** [comment]
I get this error message after upgrade eventmachine to 1.2.5 ( previous 1.2.3 is ok)

**Comment by ccurtisj** [comment]
I'm hitting this error now after upgrading to a Macbook Pro running the M1 chip on Big Sur. @sFrenkie's tip worked for me, thank you!
