### ISSUE TITLE
Kqueue support in JRuby

### ISSUE THREAD

**Issue by nickcarenza** [eventmachine/eventmachine#724]
I don't know if this is an issue in eventmachine, JRuby or something else. I am trying to make a logstash output plugin and require a lib that uses eventmachine.

```
% jirb                                               
irb(main):001:0> require "eventmachine"
=> true
irb(main):002:0> EM.epoll
=> nil
irb(main):003:0> EM.kqueue
=> nil
irb(main):004:0> EM.kqueue?
=> false
irb(main):005:0> EM.epoll?
=> false
```

**Comment by sodabrew** [comment]
There is a separate implementation in Java for JRuby that uses Java IO rather than epoll or kqueue.

**Comment by nickcarenza** [comment]
@sodabrew So would I likely have to fork the lib that requires eventmachine to use this java specific version?

**Comment by sodabrew** [comment]
No, it just works. Are you actually having a problem?

**Comment by nickcarenza** [comment]
Well I was seeing an[ error that neither epoll nor kqueue was supported](https://github.com/nats-io/ruby-nats/blob/v0.7.0/lib/nats/client.rb#L177) so i _thought_ that was why it wasn't working. But you're saying that they don't have to be and the eventmachine will use NIO instead. The warning might just be in the lib for debugging purposes and didn't have JRuby in mind.

**Comment by sodabrew** [comment]
That's just a warning. If the code is working in JRuby then it's working with Java NIO.

I'll submit a change to remove the warning under JRuby.

**Comment by nickcarenza** [comment]
thanks for the clarification and even the pr to the client @sodabrew
