### ISSUE TITLE
About gem native extension error

### ISSUE THREAD

**Issue by mayank8995** [eventmachine/eventmachine#726]
![untitled1](https://cloud.githubusercontent.com/assets/15875200/17070180/2f09b566-5078-11e6-96c2-b493c413ac0d.png)

**Comment by sodabrew** [comment]
Please post text, not screenshots. If I wanted to Google that for you, I'd have to retype it.

I don't know why it's looking for python. Python is not part of the build process.

**Comment by sodabrew** [comment]
Wait, that's installing libv8. Python might be part of the libv8 installation process.

This is not related to eventmachine.

Maybe you have `therubyracer` in your Gemfile? At any rate, if you need python to compile libv8 then you need python.

**Comment by sodabrew** [comment]
Confirmed that Python is required for compiling libv8: https://github.com/cowboyd/libv8#requirements
