### ISSUE TITLE
Eventmachine 1.0.9.1 Issue

### ISSUE THREAD

**Issue by BinaryResolved** [eventmachine/eventmachine#727]
I was trying to install eventmachine version 1.0.9.1 however I keep running into this.

> current directory: C:/Ruby23/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/ext
C:/Ruby23/bin/ruby.exe -r ./siteconf20160730-8596-1hyo5t7.rb extconf.rb
checking for main() in -lssleay32... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby23/bin/$(RUBY_BASE_NAME)
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
	--with-ssleay32lib
	--without-ssleay32lib
C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from C:/Ruby23/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:8:in `block in check_libs'
	from extconf.rb:8:in `each'
	from extconf.rb:8:in `all?'
	from extconf.rb:8:in `check_libs'
	from extconf.rb:95:in `<main>'
To see why this extension failed to compile, please check the mkmf.log which can be found here:
  C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/eventmachine-1.0.9.1/mkmf.log
extconf failed, exit code 1

I looked in the "mkmf.log" as it said but didn't see it say for sure the problem anywhere. What should I do, any help is greatly appreciated. :)

**Comment by sodabrew** [comment]
Have you installed the DevKit?

**Comment by BinaryResolved** [comment]
Yes I have DevKit installed. Once I had it downloaded I ran the following commands.(From inside the extracted folder) "ruby dk.rb unit", "ruby dk.rb install".

-----Original Message-----

**Comment by BinaryResolved** [comment]
Ideas?
