### ISSUE TITLE
Possible access to freed EventableDescriptor

### ISSUE THREAD

**Issue by luismfonseca** [eventmachine/eventmachine#729]
Hi, when reviewing the [em.cpp#855](https://github.com/eventmachine/eventmachine/blob/master/ext/em.cpp#L855) file.

If the system is running KQUEUE, then that line won't be executed but the `delete ed` will run anyway. This seems that the next run could possible access a freed `Descriptor` before finally clearing it.

Is this scenario possible?

**Comment by sodabrew** [comment]
I've re-read your question here several times, and you might be right? I'm not sure? I'm keeping this issue open as a reminder to take the time to step through the code to answer your question carefully.

**Comment by sodabrew** [comment]
In #766, the issue was fixed where `delete ed` can call back into Ruby space, and if there is an exception thrown from Ruby space, on the next loop the same descriptor will be deleted again, causing a crash. The new EventMachine 1.2.3 release should resolve this!
