### ISSUE TITLE
Does Eventmachine build for msvc12 32 bit and ruby2.1.10?

### ISSUE THREAD

**Issue by kanglisa** [eventmachine/eventmachine#730]
I am trying to build ruby with msvc12  for 32 bit and ruby2.1.10. But I am running into this linking error. 
Do you know if there are something missing with the msvc build? I did get the mingw32 version working fine. But due to our requirements, I can not use the mingw32 version.
Thanks
Lisa 

1>cmain.obj : error LNK2001: unresolved external symbol _rb_eRuntimeError
1>rubymain.obj : error LNK2001: unresolved external symbol _rb_eRuntimeError
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_accept@12 referenced in function "public: virtual void __thiscall AcceptorDescriptor::Read(void)" (?Read@AcceptorDescriptor@@UAEXXZ)
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_getpeername@12 referenced in function "public: virtual bool __thiscall ConnectionDescriptor::GetPeername(struct sockaddr *,int *)" (?GetPeername@ConnectionDescriptor@@UAE_NPAUsockaddr@@PAH@Z)
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_getsockname@12 referenced in function "public: virtual bool __thiscall AcceptorDescriptor::GetSockname(struct sockaddr *,int *)" (?GetSockname@AcceptorDescriptor@@UAE_NPAUsockaddr@@PAH@Z)
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_getsockopt@20 referenced in function "public: virtual int __thiscall ConnectionDescriptor::ReportErrorStatus(void)" (?ReportErrorStatus@ConnectionDescriptor@@UAEHXZ)
1>rubymain.obj : error LNK2001: unresolved external symbol _rb_w32_getsockopt@20
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_recvfrom@24 referenced in function "public: virtual void __thiscall DatagramDescriptor::Read(void)" (?Read@DatagramDescriptor@@UAEXXZ)
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_sendto@24 referenced in function "public: virtual void __thiscall DatagramDescriptor::Write(void)" (?Write@DatagramDescriptor@@UAEXXZ)
1>em.obj : error LNK2001: unresolved external symbol _rb_w32_sendto@24
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_setsockopt@20 referenced in function "public: __thiscall DatagramDescriptor::DatagramDescriptor(unsigned int,class EventMachine_t *)" (??0DatagramDescriptor@@QAE@IPAVEventMachine_t@@@Z)
1>em.obj : error LNK2001: unresolved external symbol _rb_w32_setsockopt@20
1>rubymain.obj : error LNK2001: unresolved external symbol _rb_w32_setsockopt@20
1>ed.obj : error LNK2019: unresolved external symbol _rb_w32_shutdown@8 referenced in function "public: void __thiscall EventableDescriptor::Close(void)" (?Close@EventableDescriptor@@QAEXXZ)
1>em.obj : error LNK2019: unresolved external symbol _rb_w32_bind@12 referenced in function "public: unsigned int const __thiscall EventMachine_t::ConnectToServer(char const *,int,char const *,int)" (?ConnectToServer@EventMachine_t@@QAE?BIPBDH0H@Z)
1>em.obj : error LNK2019: unresolved external symbol _rb_w32_connect@12 referenced in function "public: unsigned int const __thiscall EventMachine_t::ConnectToServer(char const *,int,char const *,int)" (?ConnectToServer@EventMachine_t@@QAE?BIPBDH0H@Z)
1>em.obj : error LNK2019: unresolved external symbol _rb_w32_select@20 referenced in function "private: void __thiscall EventMachine_t::_CleanBadDescriptors(void)" (?_CleanBadDescriptors@EventMachine_t@@AAEXXZ)
1>em.obj : error LNK2019: unresolved external symbol _rb_w32_listen@8 referenced in function "public: unsigned int const __thiscall EventMachine_t::CreateTcpServer(char const *,int)" (?CreateTcpServer@EventMachine_t@@QAE?BIPBDH@Z)
1>em.obj : error LNK2019: unresolved external symbol _rb_w32_socket@12 referenced in function "unsigned int __cdecl EmSocket(int,int,int)" (?EmSocket@@YAIHHH@Z)
1>rubymain.obj : error LNK2001: unresolved external symbol _rb_cObject
1>rubymain.obj : error LNK2001: unresolved external symbol _rb_cTime
1>rubymain.obj : error LNK2001: unresolved external symbol _rb_eIOError
1>C:\

**Comment by sodabrew** [comment]
It looks like you're missing a `libruby.dll` reference. I'm not familiar with using Visual Studio, but I'm happy to help merge any code or extconf.rb configuration tool changes that you find necessary.

**Comment by kanglisa** [comment]
Thanks for your feed back. 
If the  lib  you refer is msvc120-ruby210.dll. It is there under the path. C:\ruby21-10\bin\msvcr120-ruby210.dll and my path env includes has it there.


 
@ cl -nologo -LD -Ferubyeventmachine.so binder.obj cmain.obj ed.obj em.obj kb.ob
j page.obj pipe.obj rubymain.obj ssl.obj msvcr120-ruby210.lib ssleay32.lib libea
y32.lib kernel32.lib rpcrt4.lib gdi32.lib oldnames.lib user32.lib advapi32.lib s
hell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib -link -incremental:n
o -debug -manifest -opt:ref -opt:icf -incremental:no -debug -manifest -opt:ref -
opt:icf -dll -libpath:. -libpath:C:/Ruby21-10/lib -implib:rubyeventmachine-i386-
mswin32_120.lib -pdb:rubyeventmachine-i386-mswin32_120.pdb -def:rubyeventmachine
-i386-mswin32_120.def
   Creating library rubyeventmachine-i386-mswin32_120.lib and object rubyeventma
chine-i386-mswin32_120.exp
cmain.obj : error LNK2001: unresolved external symbol _rb_eRuntimeError
rubymain.obj : error LNK2001: unresolved external symbol _rb_eRuntimeError
ed.obj : error LNK2019: unresolved external symbol _rb_w32_accept@12 referenced
in function "public: virtual void __thiscall AcceptorDescriptor::Read(void)" (?R
ead@AcceptorDescriptor@@UAEXXZ)
ed.obj : error LNK2019: unresolved external symbol _rb_w32_getpeername@12 refere
nced in function "public: virtual bool __thiscall ConnectionDescriptor::GetPeern
ame(struct sockaddr *,int *)" (?GetPeername@ConnectionDescriptor@@UAE_NPAUsockad
dr@@PAH@Z)
ed.obj : error LNK2019: unresolved external symbol _rb_w32_getsockname@12 refere
nced in function "public: virtual bool __thiscall ConnectionDescriptor::GetSockn
ame(struct sockaddr *,int *)" (?GetSockname@ConnectionDescriptor@@UAE_NPAUsockad
dr@@PAH@Z)
ed.obj : error LNK2019: unresolved external symbol _rb_w32_getsockopt@20 referen
ced in function "public: virtual void __thiscall ConnectionDescriptor::Write(voi
d)" (?Write@ConnectionDescriptor@@UAEXXZ)
rubymain.obj : error LNK2001: unresolved external symbol _rb_w32_getsockopt@20

**Comment by sodabrew** [comment]
Have you made any progress on the issue here? If you have any suggested changes or improvements to the EventMachine build system I'm happy to integrate those.
