### ISSUE TITLE
Is there a way to use IMAP with this?

### ISSUE THREAD

**Issue by JohnMerlino1** [eventmachine/eventmachine#734]
I am trying to use EventMachine with Imap. Unfortunately, ruby 'net/imap' is blocking and not evented. I tried this gem:

https://github.com/ConradIrwin/em-imap

But it is not good. Not only is the project abandoned but some important commands in IMAP such as uid_search never worked. 

Is there any way to get nonblocking imap with eventmachine?

**Comment by sodabrew** [comment]
Generally eventmachine provides the underlying socket and event handling but does not attempt to provide the high-level protocol. There are some protocol clients included, but IMAP is not among them: https://github.com/eventmachine/eventmachine/tree/master/lib/em/protocols

You are certainly welcome to build a new IMAP client / server codebase on EM, or to revive the one up above (I would welcome a maintained implementation as eventmachine/em-imap!).
