### ISSUE TITLE
Can not install eventmachine 1.0.9.1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by chungth** [eventmachine/eventmachine#735]
I installed eventmachine 1.0.9.1 on Ubuntu 14.04 by the command below:

```
gem install eventmachine -v 1.0.9.1
```

 but faced the  following error: 

```
ERROR:  Could not find a valid gem 'eventmachine' (= 1.0.9.1) in any repository
ERROR:  Possible alternatives: eventmachine
```

<img width="660" alt="screen shot 2016-10-04 at 09 46 15" src="https://cloud.githubusercontent.com/assets/2556644/19061069/c33d5d5e-8a17-11e6-811b-b7e1fbc84c6a.png">

How can I solve it ? 

Thanks !

**Comment by sodabrew** [comment]
Do you have `https://rubygems.org` set up as your gems source?

**Comment by sodabrew** [comment]
Are you still seeing this problem @chungth ?
