### ISSUE TITLE
Can't install 1.0.9 or 1.2.0.1 on El Capitan 10.11.6

### ISSUE THREAD

**Issue by DicksB** [eventmachine/eventmachine#740]
I've had a couple of different errors trying to install. First, it complained of a missing config.h file:

In file included from conftest.c:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"

Well, it's correct, the file doesn't exist. I've got Xcode 8.1 installed, and the command line tools also seem to be installed. I tried resolving this by linking the config.h file that *does* exist in another directory to the expected location. The build got further afterward:

make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by `binder.o'.  Stop.

One thing I noted is that this seems to be looking in universal-darwin15, but the directory I have appears to be universal-darwin16. Before I go too far down the rabbit hole creating a bunch of links, though, I was wondering if anybody has seen and solved this. I've seen some similar issues raised about a year ago, but none quite matching this.

I get the error whether trying to install 1.0.9 (which I gather is the oldest version that should build under El Capitan) or the latest release.

**Comment by sodabrew** [comment]
Do you have Command Line Tools for Xcode? Have you accepted the new license agreement?

**Comment by DicksB** [comment]
I'm pretty sure this means I have the Command Line Tools installed:

OAIJCTMU0108926:it_careers dicksb$ gcc
clang: error: no input files

To be extra-sure, I tried xcode-select --install, but that simply generated an error about a network problem after giving me the GUI install dialog.

Xcode does not ask me to accept an agreement when launched, which I assume it would do had I not previously accepted it, but honestly, I don't recall. Is that when I should expect to see it?

**Comment by sodabrew** [comment]
See if `sudo xcodebuild -license accept` allows you to move forward?

**Comment by DicksB** [comment]
I'm afraid not -- same error. Day is over here, so I won't be able to check in again until tomorrow -- but thank you very much for your quick responses!

**Comment by DicksB** [comment]
Well, I still haven't had any success. Any suggestions would be greatly appreciated. Thank you!

**Comment by DicksB** [comment]
It looks like the problem is that something is looking for this directory:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15

...which no longer exists, having been replaced by:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin16

...but I have no idea how to correct this problem.

**Comment by sodabrew** [comment]
You might need to update your Xcode? I still think `xcode-select --install` is necessary.

Also see what output you get from `xcode-select -p`? I get:
```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

**Comment by DicksB** [comment]
Thanks for the response -- in fact, I solved the problem this morning. xcode-select --install just gives me the error I mentioned above -- but it turns out there's a separate disk image on Apple's developer site that contains a command line tools installation package. Installing *that* did the trick!

Thanks again for your time!

**Comment by sodabrew** [comment]
Great to hear!

**Comment by wookayin** [comment]
@DicksB Could you provide the link to the disk image that worked for you?
