### ISSUE TITLE
Error occurred while installing eventmachine 1.2.0.1

### ISSUE THREAD

**Issue by sileomahony** [eventmachine/eventmachine#742]
I am new to this, so any help would be greatly appreciated.
I am running the gem 2.5.1 and ruby 2.3.1p112 on Fedora 24. When I try to run `bundle install`, I get the following error:

`Fetching gem metadata from http://rubygems.org/...............
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies....
Using rake 10.3.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.1
Using thread_safe 0.3.5
Using bundler 1.13.6
Using hitimes 1.2.4
Using chunky_png 1.3.7
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using multi_json 1.12.1
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using ffi 1.9.14
Installing eventmachine 1.2.0.1 with native extensions
Using http_parser.rb 0.6.0
Using erubis 2.7.0
Using tilt 1.4.1
Using hike 1.2.3
Using uber 0.0.15
Using kramdown 1.12.0
Using libv8 3.16.14.15
Using rack 1.6.4
Using thor 0.19.1
Using rouge 2.0.6
Using redcarpet 3.1.2
Using ref 2.0.0
Using middleman-gh-pages 0.3.1
Using tzinfo 1.2.2
Using timers 4.0.4
Using coffee-script 2.4.1
Using uglifier 2.7.2
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-inotify 0.9.7
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/sileomahony/.gem/ruby/gems/eventmachine-1.2.0.1/ext
/usr/bin/ruby -r ./siteconf20161107-65539-kqy3xi.rb extconf.rb
checking for main() in -lcrypto... yes
checking for main() in -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for pipe2() in unistd.h... yes
checking for accept4() in sys/socket.h... yes
checking for SOCK_CLOEXEC in sys/socket.h... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2
-fexceptions -fstack-protector-strong --param=ssp-buffer-size=4
-grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
-mtune=generic
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/home/sileomahony/.gem/ruby/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1/mkmf.log

current directory: /home/sileomahony/.gem/ruby/gems/eventmachine-1.2.0.1/ext
make "DESTDIR=" clean
rm -f 
rm -f rubyeventmachine.so  *.o  *.bak mkmf.log .*.time

current directory: /home/sileomahony/.gem/ruby/gems/eventmachine-1.2.0.1/ext
make "DESTDIR="
g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. 
-DHAVE_OPENSSL_SSL_H -DHAVE_OPENSSL_ERR_H -DWITH_SSL -DBUILD_FOR_RUBY
-DHAVE_RB_THREAD_CALL_WITHOUT_GVL -DHAVE_RB_THREAD_FD_SELECT
-DHAVE_TYPE_RB_FDSET_T -DHAVE_RB_WAIT_FOR_SINGLE_FD -DHAVE_RB_TIME_NEW
-DHAVE_INOTIFY_INIT -DHAVE_INOTIFY -DHAVE_WRITEV -DHAVE_PIPE2 -DHAVE_ACCEPT4
-DHAVE_CONST_SOCK_CLOEXEC -DOS_UNIX -DHAVE_EPOLL_CREATE -DHAVE_EPOLL
-DHAVE_CLOCK_GETTIME -DHAVE_CONST_CLOCK_MONOTONIC_RAW
-DHAVE_CONST_CLOCK_MONOTONIC    -fPIC -O2 -g -pipe -Wall -Werror=format-security
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong
--param=ssp-buffer-size=4 -grecord-gcc-switches
-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic  -m64 -o pipe.o -c
pipe.cpp
make: g++: Command not found
Makefile:231: recipe for target 'pipe.o' failed
make: *** [pipe.o] Error 127

make failed, exit code 2

Gem files will remain installed in
/home/sileomahony/.gem/ruby/gems/eventmachine-1.2.0.1 for inspection.
Results logged to
/home/sileomahony/.gem/ruby/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1/gem_make.out

An error occurred while installing eventmachine (1.2.0.1), and Bundler
cannot continue.
Make sure that `gem install eventmachine -v '1.2.0.1'` succeeds before
bundling.
`
Any suggestions greatly appreciated!

**Comment by sodabrew** [comment]
`make: g++: Command not found` indicates that you need to install a C++ compiler.

**Comment by sileomahony** [comment]
Great, thank you!
