### ISSUE TITLE
Failing to resolve hostnames on 1.2.0 on smartos

### ISSUE THREAD

**Issue by jdelStrother** [eventmachine/eventmachine#745]
On our smartos servers, EventMachine 1.2+ doesn't seem able to resolve hostnames.   It did used to work on 1.0.9.1 :

```
$ ruby -e "gem 'eventmachine', '1.0.9.1'; require 'em-http-request'; EM.run { http = EM::HttpRequest.new('http://google.com').get; http.callback { p 'success'; EM.stop }; http.errback { puts http.error; EM.stop } }"
"success"

$ ruby -e "gem 'eventmachine', '1.2.0'; require 'em-http-request'; EM.run { http = EM::HttpRequest.new('http://google.com').get; http.callback { p 'success'; EM.stop }; http.errback { puts http.error; EM.stop } }"
unable to resolve server address: No such file or directory
```

Any suggestions on narrowing down the issue?

**Comment by sodabrew** [comment]
Interesting, yes, 1.2 switched to getaddrinfo as the underlying system call for dns lookup.

**Comment by sodabrew** [comment]
Please try the new eventmachine 1.2.1 release and see if it returns a better error message, I specifically fixed the `getaddrinfo` wrapper to use the corresponding error message function to help narrow this down.

**Comment by jdelStrother** [comment]
Hmm.   Not much clearer:

```
$ ruby -e "gem 'eventmachine', '1.2.1'; require 'em-http-request'; EM.run { http = EM::HttpRequest.new('http://google.com').get; http.callback { p 'success'; EM.stop }; http.errback { puts http.error; EM.stop } }"
unable to resolve address: node name or service name not known
```

The problem appears to be more widespread than just EventMachine, though:

```
$ ping google.com
google.com is alive

$ perl gethostbyname.pl google.com   # http://unix.stackexchange.com/a/98696
216.58.204.46

$ ruby -e "require 'socket'; puts Socket.getaddrinfo('google.com', 'http')"
-e:1:in `getaddrinfo': getaddrinfo: service name not available for the specified socket type (SocketError)
        from -e:1:in `<main>'
```

I'll see if any solaris/smartos guys can shed any light.

**Comment by sodabrew** [comment]
I found https://rt.cpan.org/Public/Bug/Display.html?id=96874

It looks like Solaris and family have some additional requirements on `getaddrinfo` arguments.

**Comment by jdelStrother** [comment]
I can persuade `Socket` to work if I'm explicit about the port and socket type:

```ruby
irb(main):046:0> Socket.getaddrinfo('google.com', '80', nil, :STREAM)
=> [["AF_INET", 80, "216.58.210.46", "216.58.210.46", 2, 2, 6], ["AF_INET6", 80, "2a00:1450:4009:800::200e", "2a00:1450:4009:800::200e", 26, 2, 6]]

irb(main):047:0> Socket.getaddrinfo('google.com', '443', nil, :STREAM)
=> [["AF_INET", 443, "216.58.210.46", "216.58.210.46", 2, 2, 6], ["AF_INET6", 443, "2a00:1450:4009:800::200e", "2a00:1450:4009:800::200e", 26, 2, 6]]
```

**Comment by sodabrew** [comment]
Yes, being explicit about the port and socket type are just what I saw in other reading. I started setting up a SmartOS VM so that I can test out compiling the equivalent changes in C – if you're handy in C please feel free to take a shot at a PR, if not, I'll be able to work this out in a few weeks, time permitting.
