### ISSUE TITLE
watch_file DELETE event on OpenVZ kernels

### ISSUE THREAD

**Issue by timurb** [eventmachine/eventmachine#75]
When building eventmachine on Linux host with OpenVZ kernel, the tests hang on TestFileWatch test.
I figured out that the problem is that file_deleted event does not fire.

Building on the same host with regular kernel passes all tests successfully.

**Comment by sodabrew** [comment]
This is a known limitation of OpenVZ, I don't think there's any way around it. I saw the same problem in #551 with Travis CI, and did two things: added a timeout to that test and switched to Travis CI containers. (Note to time traveling readers in 2010: Travis CI is an awesome service from the future.)
