### ISSUE TITLE
Segmentation Fault eventmachine-1.2.1/lib/eventmachine.rb:202

### ISSUE THREAD

**Issue by Bogadon** [eventmachine/eventmachine#758]
This is probably a duplicate of similar issues, but uploading this trace in case its useful.

We have been seeing this error very frequently. Unfortunately I can not speculate on the circumstance; sometimes it lasts for days, other times it crashes on start up several times in a row, then lasts for several hours.

If you need any other information I can try to provide.

Thanks for the gem.

> Thin web server (v1.7.0 codename Dunder Mifflin)
> Maximum connections set to 1024
> Listening on 0.0.0.0:3001, CTRL+C to stop
> /home/yozu/shared/bundle/ruby/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:202: [BUG] Segmentation fault at 0x00000000000000
> ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
> 
> -- Control frame information -----------------------------------------------
> c:0046 p:---- s:0192 e:000191 CFUNC  :release_machine
> c:0045 p:0036 s:0189 e:000188 RESCUE /home/yozu/shared/bundle/ruby/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:202
> c:0044 p:0385 s:0186 E:0010b0 METHOD /home/yozu/shared/bundle/ruby/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:205
> c:0043 p:0063 s:0179 E:000868 METHOD /home/yozu/shared/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73
> c:0042 p:0120 s:0175 E:000d10 METHOD /home/yozu/shared/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162
> c:0041 p:0511 s:0172 E:001798 METHOD /home/yozu/shared/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:87
> c:0040 p:0023 s:0168 e:000167 BLOCK  /home/yozu/shared/bundle/ruby/2.3.0/bundler/gems/websocket-rails-08b3b3b13b7b/lib/rails/tasks/websocket_rails.tasks:14 [FINISH]

Full log attached
[eventmachinefailure.txt](https://github.com/eventmachine/eventmachine/files/711306/eventmachinefailure.txt)

**Comment by sodabrew** [comment]
Please try the new EventMachine 1.2.3 release, it should resolve this crash!
