### ISSUE TITLE
Encryption issue

### ISSUE THREAD

**Issue by Kavi6** [eventmachine/eventmachine#760]
please help me fix this issue in window 7
ruby version 2.3.3
and i found error causing file is ext/ed.cpp

please tell me how to fix this encryption..
and also tell me what is the difference between eventmachine 1.0.0 and eventmachine 1.2.1
My code work fine with eventmachine 1.0.0 with ruby 1.9.3.. Kindly tell me how do i fix this issue in ruby 2.3.3..

terminate called after throwing an instance of 'std::runtime_error'
  what():  Encryption not available on this event-machine

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by sodabrew** [comment]
Hi, I apologize that I did not see your ticket until just now. You will need to recompile EventMachine with an OpenSSL package installed on your Windows machine. Use OpenSSL 1.0.x for best results at this time - the library names changed in some OpenSSL 1.1.x packages for Windows.
