### ISSUE TITLE
MaxEpollDescriptors vs MaxEvents

### ISSUE THREAD

**Issue by gr790** [eventmachine/eventmachine#770]
Hello,

I was looking at the code in ext/em.cpp, I see you have this code
epfd = epoll_create (MaxEpollDescriptors); where MaxEpollDescriptors defined as 64*1024,

But in _RunEpollOnce(), you are looking for MaxEvents only, where as it is defined as 4096.

I am confused, shouldn't be both same.

BR,
Rahul.

**Comment by sodabrew** [comment]
This is an interesting point, thank you and sorry for the very long delay to follow up. I will mark this for the next major release to take another look at matching the values.

**Comment by sodabrew** [comment]
The sizes were set this way in f89dd20666fdbc66fbde0c349251af088c5342b0 without comment.

**Comment by tmm1** [comment]
The argument to `epoll_create` is ignored ([man page](http://man7.org/linux/man-pages/man2/epoll_create.2.html)), so `MaxEpollDescriptors` doesn't really do anything anymore.

Either way, number of descriptors != number of events. Both epoll and kqueue try to read out 4k events from the kernel at a time, and those events can be associated with any number of descriptors.

**Comment by sodabrew** [comment]
Is it possible that the MaxEvents limit of 4k is related to #604 on Mac OS X, if the number of pending kevents exceeds that buffer size?

**Comment by tmm1** [comment]
Seems unlikely. The size is passed into kevent, so it should return 4096 events at a time regardless of how many are queued up in the kernel.

#604 has no C-backtrace so its hard to tell what's going on.

The C-backtrace in https://github.com/igrigorik/em-http-request/issues/315 shows it crashing inside ruby_http_parser and inside ruby's GC, so it seems to suggest either a bug in that library or a memory corruption issue somewhere.

**Comment by pierresouchay** [comment]
@tmm1 @sodabrew If you need something, I can reproduce easily igrigorik/em-http-request#315 and provide Crash log
