### ISSUE TITLE
NameError: uninitialized constant EventMachine::EM_PROTO_TLSv1 when connecting to a wss URL via faye-websockets

### ISSUE THREAD

**Issue by aviflax** [eventmachine/eventmachine#773]
Hello, thanks for the super impressive framework! It’s been working great for my company and I.

I’m just now trying to do something new but having some trouble, I’d appreciate any assistance.

I’m using:

* [faye-websocket](https://rubygems.org/gems/faye-websocket) 0.10.7 (released yesterday)
* EM 1.2.3
* JRuby 9.1.7.0
* Oracle’s Java JDK 1.8.0_121
* MacOS 10.12.3

The [Faye docs](https://github.com/faye/faye-websocket-ruby#using-the-websocket-client) say:

> The client supports both the plain-text `ws` protocol and the encrypted `wss` protocol…

When I open `irb` and paste in [the Faye example client code](https://github.com/faye/faye-websocket-ruby#using-the-websocket-client) — with one modification, replacing the dummy example `ws` URL with a real working `wss` URL – I get this exception:

```
NameError: uninitialized constant EventMachine::EM_PROTO_TLSv1
	from org/jruby/RubyModule.java:3344:in `const_missing'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/eventmachine-1.2.3-java/lib/em/connection.rb:436:in `start_tls'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/faye-websocket-0.10.7/lib/faye/websocket/client.rb:65:in `on_connect'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/faye-websocket-0.10.7/lib/faye/websocket/client.rb:76:in `connection_completed'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/eventmachine-1.2.3-java/lib/eventmachine.rb:1523:in `event_callback'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/eventmachine-1.2.3-java/lib/jeventmachine.rb:94:in `eventCallback'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/eventmachine-1.2.3-java/lib/jeventmachine.rb:113:in `run_machine'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/eventmachine-1.2.3-java/lib/eventmachine.rb:194:in `run'
	from (irb):4:in `<eval>'
	from org/jruby/RubyKernel.java:1000:in `eval'
	from org/jruby/RubyKernel.java:1298:in `loop'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from /Users/pavi/.rbenv/versions/jruby-9.1.7.0/bin/irb:13:in `<main>'
	from org/jruby/RubyKernel.java:979:in `load'
<bundler frames omitted>
```

FWIW here’s the code I’m running in IRB:

```ruby
require 'faye/websocket'
require 'eventmachine'

EM.run {
  ws = Faye::WebSocket::Client.new(REAL_VALID_WSS_URL)

  ws.on :open do |event|
    p [:open]
  end

  ws.on :message do |event|
    p [:message, event.data]
  end

  ws.on :close do |event|
    p [:close, event.code, event.reason]
    ws = nil
  end
}
```

Unfortunately I can’t share the WSS URL I’m using.

Thanks in advance for any help!
Avi

**Comment by sodabrew** [comment]
I'm fired. The constant is defined in C++ and Ruby but not defined in the Java reactor.

**Comment by aviflax** [comment]
@sodabrew no worries, we’ve all been there! Is there a workaround you can suggest in the meantime until this is fixed? Or maybe there was an earlier version that wouldn’t have this bug? Thanks!

**Comment by sodabrew** [comment]
There are earlier versions with no TLS whatsoever... but this is an omission not a regression.

**Comment by aviflax** [comment]
@sodabrew sorry to bug you, but this is blocking a change I need to get deployed soon, if possible. Is there a workaround you can suggest? Maybe you could point me to where I could add the missing constant myself, in a temporary fork? I’d be happy to submit a PR as well. Or… maybe the pure Ruby version would work in JRuby? Do you know if there’s a way to induce Bundler to use that specific version?

Thanks!

**Comment by aviflax** [comment]
Any chance this might be fixed sometime soon? Or I could get some guidance on submitting a fix?

**Comment by aviflax** [comment]
It’s great to see this was fixed! Thanks!

**Comment by aviflax** [comment]
Ah, uh… perhaps it wasn’t fixed? I just saw #797 😞

**Comment by arielstolerman** [comment]
I'm having the same issue as well...

**Comment by vitali84** [comment]
any solution? happens in 1.2.5

**Comment by andreimaxim** [comment]
Same problem, with the following details:

* The JRuby 9.1.15.0 Docker image
* EM 1.2.5
