### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by PraveenkumarDonga** [eventmachine/eventmachine#778]
Hi!
I am trying to install, Thrift in my PC. I got this Error in the Terminal, So I tried to install eventmachine gem manually before continue with thrift. But no luck I got this Error!
Any one Could please help me with this?

OS: Ubuntu 16.04/64bit

Thanks in Advance.

Error:
sudo gem install eventmachine
[sudo] password for smartron: 
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/eventmachine-1.2.3/ext
/usr/bin/ruby2.3 -r ./siteconf20170406-24828-6of4rg.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/eventmachine-1.2.3 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.3/gem_make.out

**Comment by PraveenkumarDonga** [comment]
![selection_009](https://cloud.githubusercontent.com/assets/8088246/24746431/b786b9f6-1ad6-11e7-8f05-edb206acf8f7.png)

**Comment by sodabrew** [comment]
You need to install the Ruby development package. On RedHat/Fedora this is called `ruby-devel`, on Debian/Ubuntu this is called `ruby-dev`.

**Comment by PraveenkumarDonga** [comment]
Hi! Sodabrew,
I have already installed that in my PC.
Still I am getting that Error.

Thanks.
![selection_010](https://cloud.githubusercontent.com/assets/8088246/24846791/8c341a8a-1dda-11e7-8212-baed3ef76660.png)

**Comment by krishansrimal** [comment]
@sodabrew

Helped me your comment! Thanks

**Comment by gouravthakur39** [comment]
> You need to install the Ruby development package. On RedHat/Fedora this is called `ruby-devel`, on Debian/Ubuntu this is called `ruby-dev`.

Thanks, it worked!
