### ISSUE TITLE
Ruby crashes at 1000+ sockets with TCPSocket Server 

### ISSUE THREAD

**Issue by bestjane** [eventmachine/eventmachine#781]
**ruby version: 2.3.0
eventmachine version: 1.0.9.1
server: centos7.3.1611** 

``
*** Error in `ruby': realloc(): invalid next size: 0x0000000001f8eab0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7ada4)[0x7f25368a4da4]
/lib64/libc.so.6(+0x7f5b8)[0x7f25368a95b8]
/lib64/libc.so.6(realloc+0x1b2)[0x7f25368aa602]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(ruby_xrealloc+0x5a)[0x7f25375ecf8a]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_fd_set+0xac)[0x7f253774a63c]
/home/live/polyhome_tcp_server/releases/10/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.so(_ZN14EventMachine_t14_RunSelectOnceEv+0x123)[0x7f252bb2ade3]
/home/live/polyhome_tcp_server/releases/10/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.so(_ZN14EventMachine_t7RunOnceEv+0x60)[0x7f252bb2c0e0]
/home/live/polyhome_tcp_server/releases/10/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.so(_ZN14EventMachine_t3RunEv+0x10)[0x7f252bb2c120]
/home/live/polyhome_tcp_server/releases/10/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.so(+0x14e19)[0x7f252bb25e19]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(+0x1dca36)[0x7f2537720a36]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(+0x1f3c93)[0x7f2537737c93]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(+0x1e7749)[0x7f253772b749]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(+0x1eb2c1)[0x7f253772f2c1]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(+0x84f44)[0x7f25375c8f44]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(ruby_exec_node+0x1d)[0x7f25375cae3d]
/home/live/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(ruby_run_node+0x1c)[0x7f25375cd86c]
ruby[0x4008bb]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f253684bb35]
ruby[0x4008e9]
======= Memory map: ========
00400000-00401000 r-xp 00000000 ca:01 1708221                            /home/live/.rvm/rubies/ruby-2.3.0/bin/ruby
00600000-00601000 r--p 00000000 ca:01 1708221                            /home/live/.rvm/rubies/ruby-2.3.0/bin/ruby
00601000-00602000 rw-p 00001000 ca:01 1708221                            /home/live/.rvm/rubies/ruby-2.3.0/bin/ruby
00d9e000-02464000 rw-p 00000000 00:00 0                                  [heap]
``

**Comment by sodabrew** [comment]
Please try EventMachine 1.2.x to see if it resolves this issue for you.

**Comment by sodabrew** [comment]
Closing at this time. Please reopen if you can reproduce the problem on latest EventMachine release.

**Comment by sodabrew** [comment]
Found it: #843
