### ISSUE TITLE
ERROR:  Error installing eventmachine: 	ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by rekha014** [eventmachine/eventmachine#795]
Ruby 2.2.2 

/home/deploy/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20170728-16937-kkmzjt.rb extconf.rb
checking for main() in -lcrypto... yes
checking for main() in -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for pipe2() in unistd.h... yes
checking for accept4() in sys/socket.h... yes
checking for SOCK_CLOEXEC in sys/socket.h... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS=$(cxxflags)
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rubymain.cpp
make: g++: Command not found
make: *** [rubymain.o] Error 127

make failed, exit code 2

Gem files will remain installed in /home/deploy/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.2.5 for inspection.
Results logged to /home/deploy/.rvm/gems/ruby-2.2.2/extensions/x86_64-linux/2.2.0/eventmachine-1.2.5/gem_make.out

**Comment by sodabrew** [comment]
> `make: g++: Command not found`

Eventmachine requires a C and C++ compiler.

**Comment by rekha014** [comment]
Thanks. its resolve
