### ISSUE TITLE
Server Stops Responding When Process Is Forked

### ISSUE THREAD

**Issue by little-apps** [eventmachine/eventmachine#796]
I've ran into a problem when starting a server using eventmachine and then forking the process (putting it in the background). I'm not sure if this is the expected behaviour or if there's some way around it. 

# Sample Code #
The sample code is below. The ``test-ws.rb`` code uses Websockets (using the [em-websocket library](https://github.com/igrigorik/em-websocket). I also attached ``test-echo.rb`` (which uses a simple class) to show that this isn't just for Websockets.
	
## test-ws.rb ##
	require 'em-websocket'

	host = '0.0.0.0'
	port = 2523
	outFile = File.new("output.txt", "a")

	unless outFile
	  puts "Unable to open 'output.txt'"
	  exit 1
	end

	threadStarted = false

	thr = Thread.new do
	  puts "Inside thread"
	  EventMachine.run do
		threadStarted = true
		puts "Accepting connections from ws://#{host}:#{port}"
		EventMachine.start_server(host, port, EventMachine::WebSocket::Connection, {}) do |ws|
		  ws.onopen do
			begin
			  ws.send "Hello!"
			  outFile.syswrite("Websocket connected\n")
			rescue
			  outFile.syswrite("#{$!}\n")
			  outFile.syswrite("#{$!.backtrace}\n")
			end
		  end

		  ws.onmessage do |msg|
			outFile.syswrite("Received message: #{msg}\n")
		  end

		  ws.onclose do
			outFile.syswrite("Websocket disconnected\n")
		  end
		end
	  end
	end

	puts "Waiting for thread to start"
	while threadStarted == false
	end

	=begin
	if child_pid = fork
	  puts "Running in background with PID #{child_pid}"
	  Process.detach child_pid
	  exit 0
	else
	  $stdout.reopen('/dev/null', 'w')
	  $stderr.reopen('/dev/null', 'w')
	  $stdin.reopen('/dev/null', 'r')
	end
	=end

	while true
	end

## test-echo.rb ##

	require "eventmachine"

	host = '0.0.0.0'
	port = 2523
	outFile = File.new("output.txt", "a")

	unless outFile
	  puts "Unable to open 'output.txt'"
	  exit 1
	end

	class Echo < EventMachine::Connection
	  def initialize(outFile)
		super
		@outFile = outFile
	  end
	   
	  def receive_data(data)
		@outFile.syswrite("Received: #{data}\n")
		send_data data
		close_connection_after_writing 
	  end

	  def unbind
		@outFile.syswrite("connection totally closed\n")
	  end
	end

	threadStarted = false

	thr = Thread.new do
	  puts "Inside thread"
	  EventMachine.run do
		threadStarted = true
		puts "Accepting connections from #{host}:#{port}"
		EventMachine.start_server(host, port, Echo, outFile)
	  end
	end

	puts "Waiting for thread to start"
	while threadStarted == false
	end

	=begin
	if child_pid = fork
	  puts "Running in background with PID #{child_pid}"
	  Process.detach child_pid
	  exit 0
	else
	  $stdout.reopen('/dev/null', 'w')
	  $stderr.reopen('/dev/null', 'w')
	  $stdin.reopen('/dev/null', 'r')
	end
	=end

	while true
	end
	
# Test Cases #

### Foreground ###

If I run it as is (with the ``fork`` call commented out) and connect using a Websocket (and send "Hi!"), this is what I get:

$ ruby test-ws.rb
> Waiting for thread to start
> Inside thread
> Accepting connections from ws://0.0.0.0:2523

$ cat output.txt
> Websocket connected
> Received message: Hi!
> Websocket disconnected

### Background ###

If I uncomment the ``fork`` call, the server no longer responds. Meaning I can connect but it doesn't respond (no headers are sent). This is the output when I do the exact same as above:

$ ruby test-ws.rb
> Waiting for thread to start
> Inside thread
> Accepting connections from ws://0.0.0.0:2523
> Running in background with PID 7000

$ cat output.txt
> 

### Foreground ###

If I run it as is (with the ``fork`` call commented out) and connect using a raw socket (and send "Hello!"), this is what I get:

$ ruby test-echo.rb
> Waiting for thread to start
> Inside thread
> Accepting connections from 0.0.0.0:2523

$ cat output.txt
> Received: Hello!
> 
> connection totally closed

### Background ###

If I uncomment the ``fork`` call, the server no longer responds and I can't send anything. This is the output when I try to do the exact same as above.

$ ruby test-ws.rb
Waiting for thread to start
Inside thread
Accepting connections from 0.0.0.0:2523
Running in background with PID 7842

$ cat output.txt
> 

# Test Specifications #

CentOS 7 (x64)  
Ruby v2.2.2p95 & v2.4.1p111  
Eventmachine v1.2.3 & v1.2.5
em-websocket v0.5.1

**Comment by sodabrew** [comment]
The EM reactor stops when the process is forked.

Ruby 2.0 and above set Close on Exec by default on all sockets, so all of the file and socket handles will be closed when the child process begins executing.

If you want to detach / daemonize a process in this manner, structure your code a bit like this:

A. Gather all resources that require privilege. Mark them not to close-on-exec.
B. Drop your privileges, fork to detach / daemonize.
C. Start the Machine with the resources captured in A.
