### ISSUE TITLE
EventMachine.schedule arguments documentation

### ISSUE THREAD

**Issue by kinnrot** [eventmachine/eventmachine#798]
According to docs

```
 # Runs the given callback on the reactor thread, or immediately if called
  # from the reactor thread. Accepts the same arguments as {EventMachine::Callback}
  def self.schedule(*a, &b)
    cb = Callback(*a, &b)
    if reactor_running? && reactor_thread?
      cb.call
    else
      next_tick { cb.call }
    end
  end
```

I don't understand how to use the overload that accepts object and method and pass argument to it.

thanks,

**Comment by sodabrew** [comment]
The EM.schedule method is a convenience to create the EM::Callback and calls/schedules the callback itself, without arguments at the point of `cb.call` (i.e. there is no `cb.call(your, args, here)`. To add those arguments you can either pass in a block/proc/lambda that includes the arguments http://www.rubydoc.info/github/eventmachine/eventmachine/EventMachine.Callback see the examples for passing in a block.

**Comment by kinnrot** [comment]
10x
