### ISSUE TITLE
Add appveyor testing again?

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#799]
I've got Appveyor running using 2.0 thru trunk.  Appveyor results [here](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/3), Travis results [here](https://travis-ci.org/MSP-Greg/eventmachine/builds/269268498).

Haven't squashed commits yet, patches are first three commits today, 28-Aug at [MSP-Greg/eventmachine](https://github.com/MSP-Greg/eventmachine/commits/appveyor).

I could not get Ruby versions built with RubyInstaller to build EM with OpenSSL, so 3rd commit skips test_start_tls.  Ruby 2.4 and trunk are newer builds that will build EM with OpenSSL.  2.4 uses 1.0.2, trunk uses 1.1.0.

EDIT 02-Sept:  Ruby versions 2.2 and 2.3 are now building with OpenSSL, see [new Appveyor results](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/4).  So, ruby 2.2, 2.3, 2.4, and trunk all test with EM built with OpenSSL.

**Comment by sodabrew** [comment]
I used to have AppVeyor tests running from my account, is that no longer working?

**Comment by MSP-Greg** [comment]
> is that no longer working?

I don't believe so.  I only see Travis...

**Comment by MSP-Greg** [comment]
https://ci.appveyor.com/project/sodabrew/eventmachine/history

I'll do two PR's tomorrow.  Thanks.

**Comment by MSP-Greg** [comment]
@sodabrew

Re Travis issues, rake jumped to 12.1.0 since the last good commit / PR.  The gemspec is 'compatible' with ruby >= 1.9.3, but they don't test against it.

I think bundler tests against 1.8.7, but no 1.9.x. Rubygems tests against 1.9.2 & 1.9.3.

I'll try to look at it this weekend.  I'll add 1.9.3 to Appveyor as a test.  Thanks.

**Comment by sodabrew** [comment]
Ready to get this merged for 1.3.0, I created a PR #837 from your fork.
