### ISSUE TITLE
Mac High Sierra + EventMachine 1.2.5 with SSL

### ISSUE THREAD

**Issue by ch3mic4l** [eventmachine/eventmachine#803]
Hello,

I have just started testing my app on Mac OS High Sierra Beta 9 with EventMachine 1.2.5 with SSL, and the app gets stuck in some loop and the CPU spikes to %70. I end up having to force close Ruby to stop the issue.

High-Sierra-Beta:~$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

I did find out that if I revert to EventMachine 1.2.3 with SSL everything works fine.

Here is the error:

High-Sierra-Beta:~ $ ruby /path/to/program.rb
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:459: [BUG] Segmentation fault at 0x00000000000000
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/CrashReporter                                         
     * /Library/Logs/CrashReporter                                          
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0042 e:000041 CFUNC  :start_tls
c:0006 p:0287 s:0038 e:000037 METHOD /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:459
c:0005 p:0020 s:0024 e:000023 METHOD /Library/Ruby/Gems/2.3.0/gems/websocket-eventmachine-client-1.2.0/lib/websocket/eventmachine/client.rb:86 [FINISH]
c:0004 p:---- s:0021 e:000020 CFUNC  :run_machine
c:0003 p:0327 s:0018 e:000017 METHOD /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194
c:0002 p:0165 s:0011 E:0003a8 EVAL   /path/to/program.rb:44 [FINISH]
c:0001 p:0000 s:0002 E:002450 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/path/to/program.rb:44:in `<main>'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
/Library/Ruby/Gems/2.3.0/gems/websocket-eventmachine-client-1.2.0/lib/websocket/eventmachine/client.rb:86:in `connection_completed'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:459:in `start_tls'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:459:in `start_tls'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000000 rbx: 0x00007ffbaae53e78 rcx: 0x00007ffbaae53e48
 rdx: 0x00007ffbaae53e60 rdi: 0x00007ffbaae834f0 rsi: 0x0000000000000000
 rbp: 0x00007ffeebe6a9b0 rsp: 0x00007ffeebe6a748  r8: 0x00007ffbaae53e78
  r9: 0x00007ffbaae53e90 r10: 0x00007ffbaae53ec8 r11: 0x00007ffbaae53e78
 r12: 0x00007ffbaae53e78 r13: 0x00007ffbaae53e48 r14: 0x00007ffbaae834f0
 r15: 0x0000000000000038 rip: 0x0000000000000000 rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------

**Comment by sodabrew** [comment]
Can you double check if you built both gem versions with the same OpenSSL versions?

**Comment by ch3mic4l** [comment]
Yes I built both versions of the gem with OpenSSL 1.0.2L

**Comment by sodabrew** [comment]
I've just updated to the High Sierra release version. Do you have a test program I can use to reproduce the problem?

**Comment by ch3mic4l** [comment]
I just tested again using Event Machine 1.2.5 with SSL 1.0.2l, and I am unable to reproduce the problem on the final release of High Sierra. It could have just been an issue with the Beta.

**Comment by sodabrew** [comment]
Thanks! Let's close the ticket for now, but please do reopen if you experience this problem again.
