### ISSUE TITLE
Appveyor passing 2.0.0 thru trunk

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#817]
All jobs/versions are passing.  Builds done with OpenSSL are shown with respective version.  Appveyor build is [here](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/7).

```
Vers     32    64    OpenSSL
2.0.0     x     x
2.1.9     x     x
2.2.6     x     x    1.0.2j
2.3.3     x     x    1.0.2j
2.4.2           x    1.0.2l
trunk           x    1.1.0g   2017-12-25 trunk 61451
```

FYI.  Close when you want.   Thanks, Greg

**Comment by sodabrew** [comment]
Resolved by #838
