### ISSUE TITLE
Ruby 2.5 compatible?

### ISSUE THREAD

**Issue by graywolf** [eventmachine/eventmachine#818]
In readme it's stated that 'Ruby 1.8.7 through 2.3' are supported, any chance of changing this to support ruby up to and including 2.5?

**Comment by sodabrew** [comment]
Ruby 2.4 and 2.5 are fully tested and working: https://travis-ci.org/eventmachine/eventmachine

README updated 569c55ea3d58b8675e5fab045bccaea84d6f1215
