### ISSUE TITLE
cant install eventmachine on ubuntu 16

### ISSUE THREAD

**Issue by maddymaster** [eventmachine/eventmachine#823]
I get this issue when i try to install eventmachine on Ubuntu 16.x

`I have installed ruby current directory: /var/lib/gems/2.3.0/gems/eventmachine-1.2.5/ext
make "DESTDIR=" clean`

`current directory: /var/lib/gems/2.3.0/gems/eventmachine-1.2.5/ext
make "DESTDIR="
compiling binder.cpp
make: g++: Command not found
Makefile:231: recipe for target 'binder.o' failed
make: *** [binder.o] Error 127`

`make failed, exit code 2`

Here are the version details
`root@ambee-blog:~/ambee-blog# ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
root@ambee-blog:~/ambee-blog# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

`root@ambee-blog:~/ambee-blog# make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@ambee-blog:~/ambee-blog# `

**Comment by sodabrew** [comment]
Buried in the error message: `g++: Command not found `

Install the g++ package to resolve this. There is a package called `build-essential` that will install this and other key compiler packages: https://packages.ubuntu.com/xenial/build-essential
