### ISSUE TITLE
Crash with 1.2.5 gem .../gems/eventmachine-1.2.5/lib/eventmachine.rb:194: [BUG] Segmentation fault at 0x0000000000000010

### ISSUE THREAD

**Issue by kkaple** [eventmachine/eventmachine#824]
Using sinatra and thin, a burst of requests in a window of 10 seconds or less seems to cause the issue consistently.  Server gets to about the 200-300 replies then this crash happens.

Full crash output: https://gist.github.com/kkaple/885c4fd5d806753547cdd1f116fe97ff

**Comment by pierresouchay** [comment]
I have the same kind of error, very reproductible on Mac OS: burst of connections do crash randomly as described here: igrigorik/em-http-request#315

(Only happens with lots a connections opened very quickly)

I have not yet seen it on Linux however

**Comment by sodabrew** [comment]
Resolved
