### ISSUE TITLE
v 1.2.5 Failed to build gem native extension

### ISSUE THREAD

**Issue by charaton** [eventmachine/eventmachine#825]
Hi,

I'm unable to install the gem on a Centos 6 server:

```
[deploy@staging current]$ gem install eventmachine -v '1.2.5'
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    current directory: /home/deploy/.rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.5/ext
/home/deploy/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20180313-28030-19gyv1x.rb extconf.rb
checking for -lcrypto... yes
checking for -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for pipe2() in unistd.h... yes
checking for accept4() in sys/socket.h... yes
checking for SOCK_CLOEXEC in sys/socket.h... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS=$(cxxflags)
creating Makefile

current directory: /home/deploy/.rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.5/ext
make "DESTDIR=" clean

current directory: /home/deploy/.rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.5/ext
make "DESTDIR="
compiling binder.cpp
cc1plus: warning: command line option "-Wimplicit-int" is valid for C/ObjC but not for C++
cc1plus: warning: command line option "-Wdeclaration-after-statement" is valid for C/ObjC but not for C++
cc1plus: warning: command line option "-Wimplicit-function-declaration" is valid for C/ObjC but not for C++
cc1plus: error: unrecognized command line option "-Wsuggest-attribute=noreturn"
cc1plus: warning: unrecognized command line option "-Wno-self-assign"
cc1plus: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1plus: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1plus: warning: unrecognized command line option "-Wno-tautological-compare"
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/deploy/.rvm/gems/ruby-2.4.1/gems/eventmachine-1.2.5 for inspection.
Results logged to /home/deploy/.rvm/gems/ruby-2.4.1/extensions/x86-linux/2.4.0/eventmachine-1.2.5/gem_make.out
```

```
[deploy@staging current]$ rvm info

ruby-2.4.1:

  system:
    uname:        "Linux staging.localdomain 2.6.32-696.6.3.el6.i686 #1 SMP Wed Jul 12 13:38:41 UTC 2017 i686 i686 i386 GNU/Linux"
    name:         "CentOS"
    version:      "6"
    architecture: "i386"
    bash:         "/bin/bash => GNU bash, version 4.1.2(2)-release (i386-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "centos/6/i386"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "2 minutes 57 seconds ago"
    path:         "/home/deploy/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.1p111"
    date:         "2017-03-22"
    platform:     "i686-linux"
    patchlevel:   "2017-03-22 revision 58053"
    full_version: "ruby 2.4.1p111 (2017-03-22 revision 58053) [i686-linux]"

  homes:
    gem:          "/home/deploy/.rvm/gems/ruby-2.4.1"
    ruby:         "/home/deploy/.rvm/rubies/ruby-2.4.1"

  binaries:
    ruby:         "/home/deploy/.rvm/rubies/ruby-2.4.1/bin/ruby"
    irb:          "/home/deploy/.rvm/rubies/ruby-2.4.1/bin/irb"
    gem:          "gem"
    rake:         "/home/deploy/.rvm/gems/ruby-2.4.1/bin/rake"

  environment:
    PATH:         "/usr/local/git/bin:/home/deploy/.rvm/gems/ruby-2.4.1/bin:/home/deploy/.rvm/gems/ruby-2.4.1@global/bin:/home/deploy/.rvm/rubies/ruby-2.4.1/bin:/home/deploy/.rvm/bin:/usr/local/git/bin:/home/deploy/.nvm/versions/node/v6.11.5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/deploy/bin:/home/deploy/.rvm/bin:/home/deploy/bin"
    GEM_HOME:     "/home/deploy/.rvm/gems/ruby-2.4.1"
    GEM_PATH:     "/home/deploy/.rvm/gems/ruby-2.4.1:/home/deploy/.rvm/gems/ruby-2.4.1@global"
    MY_RUBY_HOME: "/home/deploy/.rvm/rubies/ruby-2.4.1"
    IRBRC:        "/home/deploy/.rvm/rubies/ruby-2.4.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

```
[deploy@staging current]$ irb
2.4.1 :001 > RbConfig::CONFIG['CC']
 => "gcc"
2.4.1 :002 > RbConfig::CONFIG['CXX']
 => "g++"
2.4.1 :003 > RbConfig::CONFIG['CPP']
 => "gcc -E"
```

```
[deploy@staging current]$ gcc --version
gcc (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Thanks for any help!

**Comment by sodabrew** [comment]
Looks like GCC 4.7 doesn't support the additional compiler arguments. Those are actually optional, and should have been detected as not-supported...

**Comment by charaton** [comment]
Thanks for the quick reply. I set rvm to use ruby 2.3.6 and eventmachine installed that way.

**Comment by suyesh** [comment]
I been fighting with this for few days :(, i dont even know what i am fighting with. I tried in other ruby versions too. Now trying with 2.3.6

`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/suyesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.2.5/ext
/Users/suyesh/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20180416-3442-1imrq5f.rb extconf.rb
--with-cppflags=-I/usr/local/opt/openssl/include
checking for main() in -lcrypto... yes
checking for main() in -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for pipe2() in unistd.h... no
checking for accept4() in sys/socket.h... no
checking for SOCK_CLOEXEC in sys/socket.h... no
checking for sys/event.h... yes
checking for sys/queue.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS=$(cxxflags) -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
-Wno-address
creating Makefile

current directory: /Users/suyesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.2.5/ext
make "DESTDIR=" clean

current directory: /Users/suyesh/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.2.5/ext
make "DESTDIR="
compiling page.cpp
In file included from page.cpp:21:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
2 warnings generated.
compiling pipe.cpp
In file included from pipe.cpp:20:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
2 warnings generated.
compiling binder.cpp
In file included from binder.cpp:20:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
2 warnings generated.
compiling rubymain.cpp
In file included from rubymain.cpp:20:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
2 warnings generated.
compiling ssl.cpp
In file included from ssl.cpp:23:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
2 warnings generated.
compiling ed.cpp
In file included from ed.cpp:20:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);

/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
2 warnings generated.
compiling cmain.cpp
In file included from cmain.cpp:20:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
2 warnings generated.
compiling em.cpp
In file included from em.cpp:23:
In file included from ./project.h:170:
In file included from ./em.h:24:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1710:
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:19: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                  ^~~~~~~~~
/Users/suyesh/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/intern.h:47:36: warning: 'register' storage class
specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
void rb_mem_clear(register VALUE*, register long);
                                   ^~~~~~~~~
em.cpp:1242:59: error: invalid operands to binary expression ('__bind<int &, sockaddr *, unsigned long &>' and 'int')
                if (bind (sd, (struct sockaddr *)&bind_to, bind_to_len) < 0) {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/system_error:492:1: note: candidate function not viable: no known
conversion from '__bind<int &, sockaddr *, unsigned long &>' to 'const std::__1::error_condition' for 1st argument
operator<(const error_condition& __x, const error_condition& __y) _NOEXCEPT
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/system_error:569:1: note: candidate function not viable: no known
conversion from '__bind<int &, sockaddr *, unsigned long &>' to 'const std::__1::error_code' for 1st argument
operator<(const error_code& __x, const error_code& __y) _NOEXCEPT
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/utility:572:1: note: candidate template ignored: could not match 'pair'
against '__bind'
operator< (const pair<_T1,_T2>& __x, const pair<_T1,_T2>& __y)
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/iterator:702:1: note: candidate template ignored: could not match
'reverse_iterator' against '__bind'
operator<(const reverse_iterator<_Iter1>& __x, const reverse_iterator<_Iter2>& __y)
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/iterator:1143:1: note: candidate template ignored: could not match
'move_iterator' against '__bind'
operator<(const move_iterator<_Iter1>& __x, const move_iterator<_Iter2>& __y)
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/iterator:1512:1: note: candidate template ignored: could not match
'__wrap_iter' against '__bind'
operator<(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter2>& __y) _NOEXCEPT_DEBUG
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/tuple:1187:1: note: candidate template ignored: could not match 'tuple'
against '__bind'
operator<(const tuple<_Tp...>& __x, const tuple<_Up...>& __y)
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/memory:2920:1: note: candidate template ignored: could not match
'unique_ptr' against '__bind'
operator< (const unique_ptr<_T1, _D1>& __x, const unique_ptr<_T2, _D2>& __y)

/usr/local/Cellar/llvm/6.0.0/include/c++/v1/memory:2978:1: note: candidate template ignored: could not match
'unique_ptr' against '__bind'
operator<(const unique_ptr<_T1, _D1>& __x, nullptr_t)
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/memory:2987:1: note: candidate template ignored: could not match
'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'int'
operator<(nullptr_t, const unique_ptr<_T1, _D1>& __x)
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/memory:4758:1: note: candidate template ignored: could not match
'shared_ptr' against '__bind'
operator<(const shared_ptr<_Tp>& __x, const shared_ptr<_Up>& __y) _NOEXCEPT
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/memory:4823:1: note: candidate template ignored: could not match
'shared_ptr' against '__bind'
operator<(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/memory:4831:1: note: candidate template ignored: could not match
'shared_ptr<type-parameter-0-0>' against 'int'
operator<(nullptr_t, const shared_ptr<_Tp>& __x) _NOEXCEPT
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/string_view:671:6: note: candidate template ignored: could not match
'basic_string_view' against '__bind'
bool operator<(basic_string_view<_CharT, _Traits> __lhs, basic_string_view<_CharT, _Traits> __rhs) _NOEXCEPT
     ^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/string_view:678:6: note: candidate template ignored: could not match
'basic_string_view' against '__bind'
bool operator<(basic_string_view<_CharT, _Traits> __lhs,
     ^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/string_view:686:6: note: candidate template ignored: could not match
'basic_string_view<type-parameter-0-0, type-parameter-0-1>' against 'int'
bool operator<(typename common_type<basic_string_view<_CharT, _Traits> >::type __lhs, 
     ^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/string:3650:1: note: candidate template ignored: could not match
'basic_string' against '__bind'
operator< (const basic_string<_CharT, _Traits, _Allocator>& __lhs,
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/string:3659:1: note: candidate template ignored: could not match
'basic_string' against '__bind'
operator< (const basic_string<_CharT, _Traits, _Allocator>& __lhs,
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/string:3668:1: note: candidate template ignored: could not match 'const
_CharT *' against '__bind<int &, sockaddr *, unsigned long &>'
operator< (const _CharT* __lhs,
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/map:1407:1: note: candidate template ignored: could not match 'map'
against '__bind'
operator< (const map<_Key, _Tp, _Compare, _Allocator>& __x,
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/map:1872:1: note: candidate template ignored: could not match 'multimap'
against '__bind'
operator< (const multimap<_Key, _Tp, _Compare, _Allocator>& __x,
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/set:754:1: note: candidate template ignored: could not match 'set' against
'__bind'
operator< (const set<_Key, _Compare, _Allocator>& __x,
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/set:1164:1: note: candidate template ignored: could not match 'multiset'
against '__bind'
operator< (const multiset<_Key, _Compare, _Allocator>& __x,
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/vector:3326:1: note: candidate template ignored: could not match 'vector'
against '__bind'
operator< (const vector<_Tp, _Allocator>& __x, const vector<_Tp, _Allocator>& __y)
^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/deque:2868:1: note: candidate template ignored: could not match 'deque'
against '__bind'
operator< (const deque<_Tp, _Allocator>& __x, const deque<_Tp, _Allocator>& __y)
`

**Comment by sodabrew** [comment]
@suyesh Please open a new issue to report a new and different problem. I am not reopening this issue, the original topic was resolved.
