### ISSUE TITLE
Master vs 1.2.7 - missing commits in 1.2.7?

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#847]
I noticed while trying to build a fat binary gem that [master](https://github.com/eventmachine/eventmachine/commits/master) has two commits from 30-Apr
```
SmtpServer: support multiple messages per one connection
Tests for watch_only?
```

I'm not seeing these two commits in [1.27](https://github.com/eventmachine/eventmachine/commits/v1.2.7).

Maybe I'm missing something, thanks, Greg

**Comment by sodabrew** [comment]
These are queued for 1.3.0

**Comment by MSP-Greg** [comment]
Ok.  While on the issue of versions, might this https://github.com/eventmachine/eventmachine/blob/033244a29a327dcd11cc2aab467284b5fdfa1f47/lib/em/version.rb#L2

get updated?  Some seem to use the current release, some the next, regardless, 1.2.5 isn't right.  And, yes, I built from master...


Thanks, Greg

**Comment by sodabrew** [comment]
I have that locally, will push version file thank you!

**Comment by MSP-Greg** [comment]
Thanks.  FYI, and off topic, my Appveyor fat-binary code is generating the 32 bit and 64 bit files (and saving them for download)…


Current test results summary:
```
Windows Fat Binary Gem supporting Ruby 2.0 thru 2.5

All Showed 276 tests, 0 notifications

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― 32 bit
    Asserts  Fails Errors  Pend  Omissions Errors / Fails
2.0  3,528     0      1     13       8     TestResolver#test_bad_host
2.1  3,528     0      1     13       8     TestResolver#test_bad_host
2.2  3,529     0      0     13       8
2.3  3,527     0      2     13       8     TestResolver#test_bad_host
                                           TestResolver#test_failure_timer_cleanup

2.4 Stopped on TestBasic#test_invalid_address_bind_connect_dst
2.5 Stopped on TestBasic#test_invalid_address_bind_connect_dst

―――――――――――――――――――――――――――――――――――――――――――― 64 bit
    Asserts  Fails Errors  Pend  Omissions 
2.0  3,529     0      0     13       8
2.1  3,529     0      0     13       8
2.2  3,528     1      0     13       8     TestIterator#test_concurrency_bigger_than_list_size
2.3  3,529     0      0     13       8
2.4  3,533     0      0     10       8
2.5  3,524     0      0     10       13    Extra Omissions due to OpenSSL 1.1.0
```

**Comment by MSP-Greg** [comment]
@sodabrew  @tmm1

One new test that is causing issues with Windows:

https://github.com/eventmachine/eventmachine/blob/033244a29a327dcd11cc2aab467284b5fdfa1f47/tests/test_attach.rb#L175-L198

The block passed to `EM.next_tick` is never called.   `c.receive_data data` is called, and the values are correct.

Re EM, I've been testing & building, but I haven't really been using, and I'm not a c type.  Hence, this issue isn't something I can help with...

Lastly, I had four tested tagged in a patch from a while ago, the above was one, but the three others I removed.  So, 2.5.1 64 now has only 7 pending tests.  Since I suspect that many of the 'FIXME: this test is broken on Windows' tests haven't been checked on Ruby 2.4+. I'll try to check them this weekend.

Re the binary gem code, it's generating the gems fine, I haven't finished the test code, as it involves some appveyor issues, and I'm sure how best to layout the test output (files, console, etc).

It's a few PowerScript files and one rb file.  I thought I'd post it after I get Puma to use the same code base, as I originally started it with Puma.  FYI, I started on it for three main reasons:

1. It's crazy to expect MacOS / *nix types to have the two build systems installed to cross compile this.

2. Appveyor has all the build tools and ruby versions needed in their standard images.

3. To build from 2.0 thru 2.5 with OpenSSL, four different packages are required to be loaded.

I guess I haven't stated it, but every version of EM in the binary gems (Ruby 2.0 thru 2.5) is built with OpenSSL.

Thanks, Greg

**Comment by MSP-Greg** [comment]
I've added  repo with the code.  See [MSP-Greg/eventmachine-fb](https://github.com/MSP-Greg/eventmachine-fb).

The PowerShell scripts in the shared folder are used by any gems building with this system, the same files are used in my [puma-fb](https://github.com/MSP-Greg/puma-fb) repo.

Gems are saved as artifacts (built with master, vers = 1.3.0), current [test result](https://ci.appveyor.com/project/MSP-Greg/eventmachine-fb/build/2) summary is:

```
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― Test Summary
Tests  Asserts  Fails  Errors  Pend  Ommited  Notes  Ruby
                                                                 x64-mingw32
 276    3528      0       0      7      14      0    Ruby25-x64  ruby 2.5.1p57   (2018-03-29 revision 63029)
 276    3537      0       0      7       9      0    Ruby24-x64  ruby 2.4.4p296  (2018-03-28 revision 63013)
 276    3533      0       0     10       9      0    Ruby23-x64  ruby 2.3.3p222  (2016-11-21 revision 56859)
 276    3533      0       0     10       9      0    Ruby22-x64  ruby 2.2.6p396  (2016-11-15 revision 56800)
 276    3533      0       0     10       9      0    Ruby21-x64  ruby 2.1.9p490  (2016-03-30 revision 54437)
 276    3533      0       0     10       9      0    Ruby200-x64 ruby 2.0.0p648  (2015-12-16)
                                                                 i386-mingw32
testing aborted?                                     Ruby25      ruby 2.5.1p57   (2018-03-29 revision 63029)
testing aborted?                                     Ruby24      ruby 2.4.4p296  (2018-03-28 revision 63013)
 276    3533      0       0     10       9      0    Ruby23      ruby 2.3.3p222  (2016-11-21 revision 56859)
 276    3533      0       0     10       9      0    Ruby22      ruby 2.2.6p396  (2016-11-15 revision 56800)
 276    3533      0       0     10       9      0    Ruby21      ruby 2.1.9p490  (2016-03-30 revision 54437)
 276    3533      0       0     10       9      0    Ruby200     ruby 2.0.0p648  (2015-12-16)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

Thanks, Greg

**Comment by MSP-Greg** [comment]
@sodabrew @tmm1

Well, after working on the fat-binary build code for a bit, I decided that, since testing is just a few steps short of constructing a fat-binary, that doing both was advantageous for many reasons.  Hence, I moved the code to EM.

The test/build results are on Appveyor [here](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/21).

1. 64 bit and 32 bit are separate build jobs.
2. Each saves as artifacts the fat-binary gem and the test logs.  At present the test logs just have STDOUT, I haven't figures out how to have both STDOUT & STDERR appear in the console and also save to a file at the same time.
3. On the test tab of the job, each version of Ruby shows red/green, and also has the test summary.
4. The system constructs the binary gem, and actually installs it in each Ruby version, then runs the tests within itself.  Hence, I added a rakefile and all the tests to the gem.

The code is [here](https://github.com/MSP-Greg/eventmachine/tree/win-gem-build-test) on my GitHub fork. The [appveyor.yml](https://github.com/MSP-Greg/eventmachine/blob/win-gem-build-test/appveyor.yml) file is very simple.

The EM specific files are in the [win_gem_test](https://github.com/MSP-Greg/eventmachine/tree/win-gem-build-test/win_gem_test).

The files in the [win_gem_test/shared](https://github.com/MSP-Greg/eventmachine/tree/win-gem-build-test/win_gem_test/shared) are generic files, I've used the same files in a similar workup for Puma, and expect to add more repos.

I just noticed I have some more .gitignore changes to do, since it will also work locally if one has all the Ruby versions installed.  `win_gem_test/shared/local_paths.ps1` shouldn't be in the repo...

Thoughts?

Greg

**Comment by MSP-Greg** [comment]
@sodabrew @tmm1

If either of you have the time to read it and reply, I've added an issue at the repo containing the shared code for the topic of Windows pre-compiled gems and testing on Appveyor.

https://github.com/MSP-Greg/av-gem-build-test/issues/1

Thanks, Greg

**Comment by sodabrew** [comment]
Yes! I've been following this thread intently. I want to release 1.3.0 with OpenSSL included in the Windows builds. There is a cross-compile setup in https://bitbucket.org/ged/ruby-pg/src/0567662910977452ad8b9b5a6eb67bd5dd8e67ec/Rakefile.cross?at=default&fileviewer=file-view-default that I'd like to port over and integrate with your work on builds and tests as well.

**Comment by MSP-Greg** [comment]
@sodabrew

Thanks for the post over in [MSP-Greg/av-gem-build-test](https://github.com/MSP-Greg/av-gem-build-test/issues/1).  I've updated it to also check on 32 bit trunk, and I've finished the update to my fork of EM.  As mentioned, now the 'shared' script files are not contained in EM, as they're downloaded in the Appveyor.yml file.

The branch in my fork is [here](https://github.com/MSP-Greg/eventmachine/tree/av-gem-build-test).  It only has two commits  Please have a look at the [test changes comit](https://github.com/MSP-Greg/eventmachine/commit/be73f9901e6f949b2b2b4049420ca9001e777257).  For 32 bit, I had to 'pend' a few tests that involved errors and invalid src or dest addresses.

I've done one test run with it.  The 64 bit passed, from trunk down to Ruby 2.0.  The 32 bit is another issue, as shown in the above commit, as I had to 'pend' some tests for Ruby >= 2.4 & 32 bit.  The testing froze when running Ruby 2.4.

Running locally, I've seen errors in the 32 bit versions < 2.4, and I had one failure in `TestIterator#test_concurrency_bigger_than_list_size`.

Most of the other gems I've done with this system did not have any issues, either 64 bit or 32.  Conversely, almost nothing used in 32 bit Windows is currently tested.  Not the Ruby builds, not the pre-compiled OpenSSL packages, not even OpenSSL itself.

So, I can do a PR, but maybe we should try and see if theres anything that can be done with the 32 issues first?

Finally, the testing takes a while.  As you know, Travis spins up multiple jobs (typically 5?), whereas Appveyor is one at a time.  We compiling & testing 14 ruby versions...

I will have a look at mysql2, but I'm a little burnt on this right now...

Greg
