### ISSUE TITLE
Windows - pre-compiled gems - WIP

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#852]
@sodabrew

I've got a build done & passing (Ruby 2.0 thru trunk, both 32 & 64 bit), but I had to pend a few tests.  The main Appveyor page for the build is [here](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/22).  The commit for the test changes is [here](https://github.com/MSP-Greg/eventmachine/commit/be73f9901e6f949b2b2b4049420ca9001e777257).

Test log 7z files [64 bit - test_logs-x64-mingw32.7z](https://ci.appveyor.com/api/buildjobs/tsl64fu4itl24pyv/artifacts/test_logs-x64-mingw32.7z) & [32 bit - test_logs-x86-mingw32.7z](https://ci.appveyor.com/api/buildjobs/om1hfy0d0alpskcr/artifacts/test_logs-x86-mingw32.7z).  The artifacts tabs also have the pre-compiled gems.

The MSYS2/MinGW build system on Appveyor is a bit outdated, and I couldn't reliably add a key for the OpenSSL 1.1.0 packages .  Hence, the Appveyor build is about 6 minutes longer than needed because both jobs need to extract about 800 mb of files.  I filed an issue asking for it to be updated.

If you're interesting in using this, you can grab it from my fork, or, if there are updates for the test issues, I'm happy to rebase and run it again.

Thanks, Greg

**Comment by MSP-Greg** [comment]
I've done more work on the build system, added settings for whether trunk & trunk-JIT are run, and whether their tests are 'allow failure'.  JIT is only available on 64 bit.

A recent build on Appveyor had all versions from 2.0 thru trunk passing on both [32](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/24/job/mf4145nqa3p9ott6#L5226) & [64](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/24/job/ajrwvf48jeobn1b5#L9115) bit.

Main page for the build is [here](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/24).

**Comment by sodabrew** [comment]
Do you have a PR open for this work? I'd love to get it into the main line.

**Comment by MSP-Greg** [comment]
No PR yet.  Something like this I thought I'd ask first.  It's a branch of my fork, so a PR would be very quick, but:

Just today MSYS2/MinGW (the windows build system) updated to gcc 8.2.0 from 7.3.0.  Also, there has been a lot of very recent commits (like last night & today) re MJIT and threading in trunk.

All the commits in Ruby trunk are passing in Travis & mswin (vc12), but my ruby-loco trunk build is broke.  mswin (vc12) doesn't test MJIT.

Hence, I'd like to get trunk passing & stable before I do a PR.  I haven't tried building EM with 8.2.0, but the gem build system (currently) updates gcc packages.

While I writing this, I had a trunk build running.  It's finished, JIT is still broken, but the other issues disappeared when I **did not update to gcc 8.2.0**.  I'll modify the fork and the build system later today, test it, then do a PR...

Thanks, Greg

**Comment by MSP-Greg** [comment]
See PR #854.  Currently, staying with gcc 7.3.0 until Ruby trunk issues get sorted out.

Also, I'll modify the build system so I can disable JIT testing from it.  It's currently disabled in the PR.

It worked recently, but is now broke...

**Comment by MSP-Greg** [comment]
Closed by PR #854 and commit 33eb503.
