### ISSUE TITLE
Add OPENSSL_LIBRARY_VERSION & OPENSSL_VERSION constants

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#858]
Ruby OpenSSL has two constants, `OPENSSL_LIBRARY_VERSION` & `OPENSSL_VERSION`, which refer to the OpenSSL library version that Ruby OpenSSL is running with. and was build with, respectively.

I've added these constants to EM in my fork, as it's helpful for many reasons.  Would a PR for these be accepted?

Thanks, Greg

**Comment by sodabrew** [comment]
Yes, this sounds very useful!

**Comment by MSP-Greg** [comment]
Added in 0904385 to [rubymain.cpp](https://github.com/eventmachine/eventmachine/blob/0904385936ef4ecae4519f4f7b8f829a3608afcd/ext/rubymain.cpp#L1589-L1599)
