### ISSUE TITLE
Test suite failures using openssl 1.1.1

### ISSUE THREAD

**Issue by kroeckx** [eventmachine/eventmachine#864]
There are various errors in the test suite when using openssl 1.1.1. This is most likely related to TLS 1.3 being used instead of TLS 1.2.  https://wiki.openssl.org/index.php/TLS1.3 has a good overview of the things that might cause issues.

**Comment by MSP-Greg** [comment]
@kroeckx 

At present, I believe that there are no 'standard' Travis ruby builds available that use TLS 1.3 (1.1.1).  Some of the MacOS builds use 1.1.0, but I think that's the newest version.

Appveyor MinGW Ruby builds use 1.1.1 for 2.5 and trunk.  I have made a few fixes in my [fork](https://github.com/MSP-Greg/eventmachine/tree/update-for-1.1.1-tests), and tests pass on [Appveyor](https://ci.appveyor.com/project/MSP-Greg/eventmachine/builds/20819035) for newer Ruby versions (Ruby 2.3 and earlier have not been maintained).  [Travis](https://travis-ci.org/MSP-Greg/eventmachine/builds/464361679) also passed.

Building on Appveyor is a pita, as the OpenSSL package versions (and build tools) vary by Ruby version, and need to be swapped for compiling/testing.

I'm not much of a c type, nor an expert on OpenSSL...  Thanks.

**Comment by boutil** [comment]
@MSP-Greg I was able to adapt slightly your modifications on top of the code in the 1.2.7 gem to (almost completely) successfully run the SSL related tests on the Debian architecture.
Thanks a lot for your work on this, and I hope your suggestions will be imported in the repo here, or at least serve as inspiration.

**Comment by sodabrew** [comment]
Resolved by #867

**Comment by MSP-Greg** [comment]
@boutil 

> "adapt slightly" & "almost completely"

The changes for 1.1.1 have been merged, any additional changes you have would certainly be helpful.  Be happy to check them on Windows, which is using 1.1.1 for Ruby 2.5 thru trunk...

Currently, Travis CI is using 1.0.2 for Ubuntu, 1.0.2 & 1.1.0 for MacOS.
