### ISSUE TITLE
Installation failure with Ruby trunk

### ISSUE THREAD

**Issue by utilum** [eventmachine/eventmachine#898]
Since ruby/ruby@5c7c2d9951f2512ca10ea38fecc48d8ac67502e6 installation fails ([log](https://gist.github.com/utilum/fc33f3aba4c4e027f3a02dc749785acd)).

**Comment by sodabrew** [comment]
Thanks for the heads-up I’ll take a look!

**Comment by MSP-Greg** [comment]
Just ran an AppVeyor job, same issue with trunk.  See:
https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/job/rx3ls05p3vvldlkw#L183

**Comment by utilum** [comment]
Ruby trunk as of today does not give me this problem. Perhaps we can close?

**Comment by sodabrew** [comment]
Since https://github.com/ruby/ruby/commit/a569bc09e25a2ba813d0bec1228d9ff65330a3db this problem appears to be resolved, but I wonder what C++ extensions should do as a best-practice now?

**Comment by utilum** [comment]
Hm... as of this morning the problem is [back](https://gist.github.com/utilum/e1407b9ca6a1062bd3fd88929c00fc4e).

**Comment by MSP-Greg** [comment]
JFYI, I just tried building on Windows (using OpenSSL 1.1.1c) with:
```
ruby 2.7.0dev (2019-09-20T15:48:46Z master 990e714fd3) [x64-mingw32]
ruby 2.7.0dev (2019-09-12 master ac3e8834e0) [i386-mingw32]
```
Both compiled and passed tests, I think both using gcc 9.2.0...
