### ISSUE TITLE
Change license to new Ruby license

### ISSUE THREAD

**Issue by s2terminal** [eventmachine/eventmachine#913]
Thank you for making such a useful project.

I want this project to be used by more people. [The Ruby license applied to this project](https://github.com/eventmachine/eventmachine/blob/v1.2.7/LICENSE) is dual licensed with GPL version 2, this is Ruby license before Ruby 1.9.2. Can't I have a 2-clause BSDL similar to the latest Ruby license?

- [Ruby 1.9.2 Licesne: dual-licence between GPL v2](https://github.com/ruby/ruby/blob/ruby_1_9_2/COPYING)
- [Ruby 1.9.3 Licesne: dual-licence between 2-clause BSDL](https://www.ruby-lang.org/en/about/license.txt)

**Comment by sodabrew** [comment]
Every author at least, and perhaps every committer would need to sign off. I have no interest in spending time on that effort, I’m sorry.
