### ISSUE TITLE
Why my server freeze for 1 run?

### ISSUE THREAD

**Issue by Uysim** [eventmachine/eventmachine#915]
This is my first time using this gem for faye subscription. I do 
```ruby
EM.run do
  client.subscribe(....) do |message|
     puts message.inspect
  end
  # It can read this point
end
```
My Rails freeze and the page keep loading without continue.

**Comment by nickoan** [comment]
`EM.run` will blocking current thread. you should not run it in a web server.

**Comment by Uysim** [comment]
@nickoan Can I run it with background job?
Should I do like:
```ruby
thread{ EM.run  }
```

**Comment by nickoan** [comment]
@Uysim i would not suggest you do that, cos that will make your application uncontrollable,

if you expect to run it on your Rails application, then try:

```ruby
EM.run do
  client.subscribe(....) do |message|
     puts message.inspect
     # unsubscribe your client at this point.
     # run EM.stop_event_loop to quit event loop
  end
end

# after stop, this part codes will exec.
```
but, the best way is, you run it in a separate Worker or Job, and trigger it from your rails application.

**Comment by Uysim** [comment]
@nickoan ok got it
