### ISSUE TITLE
post_init being called numerous times?

### ISSUE THREAD

**Issue by paradisaeidae** [eventmachine/eventmachine#920]
I am a recent learner of EM I admit!
So my testing may not be enough to have merit!
Though I'm seeing different behavior when having upgraded to most recent release of Ubuntu 20.04 LTS.
When data is inbound post_init  is being called more than once, on null data and content.
connection_completed is also being called many times.
In certain circumstances.
I am attempting to track down specifics.
It appears the default of zero when applied to set_comm_inactivity_timeout no longer has the desired, doco effect?
Being that zero is the default I am bemused.
There is no major harm done when post_init is repeatedly called in my use.
So I'll wait for 2.3 to land before doing more investigation!
Thanks, all the best!
Stay safe!

**Comment by paradisaeidae** [comment]
No problem. Operator error!

**Comment by sodabrew** [comment]
Would you share what you did + what you learned? It might help someone with the same problem who Googles for this in the future!

**Comment by paradisaeidae** [comment]
Hi SodaBrew!
Sorry some time since your suggestion.
The code I was (meant to read completely..) ...working with used post_init in double duty fashion.
The reset of vars, clearing cache...
When having over-rationally read the eventmachine doco I was not expecting this.
Being that post-init is primarily a EM call-back!
