### ISSUE TITLE
Ubuntu 20.04, OpenSSL 3.0.0, CI

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#926]
Ubuntu 20.04 is now available on Actions CI.  I believe its OpenSSL is compiled with a security level of 2.  This changes some of the minimum allowed key lengths for ciphers, and also restricts the protocols to TLSv1.2 and TLSv1.3.

Using Ubuntu 20.04, I just ran CI in my fork, and it's failing.  Hopefully, most of the errors are due to the ssl test fixtures.  Many (all?) of the same failures occur with a MinGW OpenSSL 3.0.0.alpha7 build.

Hopefully, I'll get a PR together some time between now and Labor Day...

**Comment by OlegSmelov** [comment]
I'm having this error with Invoker which uses EventMachine internally.

```
140207038160576:error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small:../ssl/ssl_rsa.c:310:
invoker start [redacted].ini: ssl.cpp:173: SslContext_t::SslContext_t(bool, const string&, const string&): Assertion `e > 0' failed.
```
As a workaround, I've commented out `start_http_proxy(InvokerHttpsProxy, 'https', options)` in Invoker source.

**Comment by MSP-Greg** [comment]
@OlegSmelov

If possible, can you check your issue with RP #930?

**Comment by OlegSmelov** [comment]
It worked for me, however, Invoker needs to update its dependency to work properly (it depends on a very old version: https://github.com/code-mancers/invoker/blob/master/invoker.gemspec#L40). I had to hack my `Gemfile.lock` for it to use `1.3.0.dev.1` instead. Invoker is out of scope here though.
