### ISSUE TITLE
Ruby 3 with jit: long lived TCP connections quietly close/disconnect/fail.

### ISSUE THREAD

**Issue by paradisaeidae** [eventmachine/eventmachine#943]
Little tricky to replicate with my test rig.
I've not delved deeply into the characteristics of the keepalive options possible with EM.
The Linux settings are ok.
Rebuilt Ruby 3.0.1p64 without jit, then l-l tcp connections are ok.
Sending ALRM to the process triggers a re-connection which might be helpful.
Could attempt to use pure Ruby version of EM.
The Ruby JIT is still experimental so there's that.
Might be some of the code is being 'optomised', loosing connection handle?

**Comment by sodabrew** [comment]
The pure Ruby version of EM is poorly maintained, and it is much more likely that there's an interaction between the JIT and the C++ EM code (hand-waving for now, but it's where I'd start looking.)

If you could develop a short script to exercise the problem that would really help!

**Comment by paradisaeidae** [comment]
Not sure I have this understood correctly.
Rolling back to Ruby 2.7 until I can.
Closing as maybe incorrect reading of issue.

**Comment by paradisaeidae** [comment]
Without further testing this assessment is anecdotal:
It appears having the jit compiled into Ruby 3 has this effect.
Disabling when compiled in still exhibits stalling.

**Comment by paradisaeidae** [comment]
I have a workaround in place.
My proxy send an ALRM signal, caught in the loop:
 begin
::EventMachine.run do
  trap("ALRM") {raise 'ALRM caught, retrying to run EventMachine'}
  Handler.connect(hostname, port) end
 rescue => ....retry...end
Resisting the fall back to 2.7.
This is:
On D.Ocean:
Ubuntu 20.10 
Linux area52 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
When Uptime robot is requesting https://... then stall occurs at around 56 hours.
Without it appears to be 30-40 mins.
If there is anything I can put in the alert block which would assist in tracking this down, please comment!

**Comment by paradisaeidae** [comment]
The workaround seems ok so far.
The most recent outage event was after around 75 hours.
Having read Kirk's writeup: https://blog.joshsoftware.com/2020/06/19/moving-from-eventmachine-to-async/
... I'm now preparing to move that way.
Could be the Ractor model of R3 is not quite yet fully debugged/clean.
Which may be stepping on EM toes.

**Comment by paradisaeidae** [comment]
Have recently rebooted and started three processes to observe this.
All three exhibit connection halt at the same time.
So the issue must be with the head listening process or with the Linux config.
