### ISSUE TITLE
Can EventMachine be built to be compatible with Ruby 2.6+ on Windows?

### ISSUE THREAD

**Issue by kevin-roe** [eventmachine/eventmachine#945]
Based on these comments([here](https://github.com/oneclick/rubyinstaller2/issues/96#issuecomment-679206413), and [here](https://github.com/eventmachine/eventmachine/issues/907#issuecomment-579033448)) there is an issue using eventmachine on windows and Ruby 2.6.  We are attempting to integrate appium mobile tests into our workflow, but the errors pointed out in these comments are preventing this from happening, as eventmachine is a dependency of [Appium](https://github.com/appium/ruby_lib) (appium_lib > appium_lib_core > faye-websocket > eventmachine).  Looking at the master branch of eventmachine, it appears that this issue [may have been fixed](https://github.com/eventmachine/eventmachine/blob/b50c135dfdd4e7b20c8e0b7ce1d8fe7176d4d14d/eventmachine.gemspec#L20).  If so, can a new version be submitted to RubyGems so it works on windows?  

cc: @MSP-Greg, @sodabrew

**Comment by MSP-Greg** [comment]
@kevin-roe

>  it appears that this issue may have been fixed

I need to remove the conditional in the gemspec, as it really doesn't work.  Or, it isn't a fix for the issue you're having.  Regardless, a new release, along with new pre-compiled gems would be helpful for many users.

EM master or the current version will install on Windows, but one has to force the use of the regular gem, not the precompiled gem.  That can be impossible when using Gemfiles from other tools...

Also, I just ran updated CI, and there are a few failing tests on all platforms for Ruby 3+

**Comment by ethan-dowler** [comment]
@MSP-Greg Perhaps a first-step would be to get a windows-compatible, pre-compiled version of the gem for Ruby 2.6/2.7 released to RubyGems.org before jumping to Ruby 3. Is there anything we can do to help? (by "we" I mean me and @kevin-roe 
 😁 ). Our organization is depending on this for our test automation suite, so we have a vested interest in getting a release that works for 2.6/2.7 on Windows, and we are willing to contribute if needed. Thanks!

**Comment by MSP-Greg** [comment]
It's up to @sodabrew, I'm just around to help (contributor).

I pushed a PR adding Ruby 3.0+, if anyone can look at the test failures, that would be helpful.  The log is at:
https://github.com/eventmachine/eventmachine/actions/runs/858466146

I'm working on getting the code to build the pre-compiled gem (with ssl support) updated...

**Comment by ethan-dowler** [comment]
@MSP-Greg I tried running the tests locally, but I ended up getting the same error we're trying to solve in the first place haha
from [this line of code](https://github.com/eventmachine/eventmachine/blob/master/lib/eventmachine.rb#L10)
```ruby
warn "Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'"

**Comment by MSP-Greg** [comment]
You running with Bundler?

**Comment by MSP-Greg** [comment]
@ethan-dowler

Sorry, AFK for a bit.  I've built the gem (Ruby 2.2 thru 3.0, both 32 & 64 bit) on AppVeyor, and all tests pass.  The links are:
64 bit
https://ci.appveyor.com/api/buildjobs/t05cs5uo5xh0163b/artifacts/eventmachine-1.3.0.dev.1-x64-mingw32.gem
32 bit
https://ci.appveyor.com/api/buildjobs/m9kjjppxne2crg0l/artifacts/eventmachine-1.3.0.dev.1-x86-mingw32.gem

These are probably very difficult to install with Bundler, but they can be downloaded and installed by RubyGems.

If anyone can test them, that would be appreciated.  The problems with master and Ruby 3+ only affect code that isn't available on Windows, so these are ok.  There is one test failing on Ruby master/trunk/head, but it's ok on 3.0.1.

@sodabrew - reminder - the reason I created the code to assemble the gem on AppVeyor is that Windows Rubies 2.2 & 2.3 require one set of build tools, with an OpenSSL package specific to them.  Ruby 2.4 and later all use the same build tools, but Ruby 2.4 is built with OpenSSL 1.0.2, while 2.5 and later all use OpenSSL 1.1.1.  So, if one wants a pre-compiled EM gem built with ssl support, it's a bit messy...

I'd convert it to GitHub Actions, but it doesn't support 32 bit Rubies, so it's even more code.

**Comment by ethan-dowler** [comment]
@MSP-Greg No need to apologize; you are amazing. Thank you for checking this out so quickly. Is the next step to push the gems you built to RubyGems.org? I'm not sure if we can install the `.gem` files directly from Appveyor.
cc: @kevin-roe, @sodabrew

**Comment by MSP-Greg** [comment]
> Is the next step to push the gems you built to RubyGems.org?

1. I'd prefer to give @sodabrew some time to respond.
2. There is one test failure with 3.0.1.  Fixing it would allow a 'proper' new release.
3. Depending on @sodabrew's timeframe, I could push a gem with a different name, for testing only...

**Comment by ethan-dowler** [comment]
@sodabrew I'd love to connect with you on this if you're available sometime this week.

@kevin-roe Let's connect on this again sometime this week. I have some ideas on how we can move forward.

**Comment by MSP-Greg** [comment]
See PR #948.  I'm debating whether to release a 'em_temp' gem, version 2.0.0, due to the change in minimum Ruby version.  It may not be needed.  I can't release a JRuby version, but I can release a pre-compiled Windows versions...

@raggi, @sodabrew, @tmm1

Sorry for the ping.  Thoughts?  I got involved with EM for several reasons, but being an active user was not one of them.  

My interest in helping with a new release is that it's used for CI (see above) and I think it's also used by Jekyll, which is often installed on Windows by people unfamiliar with building extension gems.  Compiling on Windows is tricky due to the various OpenSSL versions required.

Given that the current Windows releases don't have a correctly set upper Ruby version limit in the gemspec...

**Comment by ethan-dowler** [comment]
@MSP-Greg Thanks for your work on this. We have found a workaround for the time being, so we do not _need_ this work anymore, so I'm going to close this issue. Thank you again!

**Comment by ethan-dowler** [comment]
actually, it looks like @kevin-roe will have to close it since he opened it

**Comment by kevin-roe** [comment]
Thanks for all your help @MSP-Greg.  For anyone who finds this via Google, our workaround was to install the gem manually by running `gem install eventmachine --platform=ruby`, then running `bundle install`.  Since the gem was installed prior to running bundler, bundler ran successfully.  Thank you again!

**Comment by zhangfei1122** [comment]
@MSP-Greg When I accessed https://ci.appveyor.com/api/buildjobs/t05cs5uo5xh0163b/artifacts/eventmachine-1.3.0.dev.1-x64-mingw32.gem, it showed {"message":"Artifact not found or access denied."} on page. How can I get permission? 
Thanks in advance.

**Comment by MSP-Greg** [comment]
@zhangfei1122

It's not a permission issue.  Artifacts (and often logs) on most CI systems will be removed when they become too old.  I may have it on my disk, not sure.
