### ISSUE TITLE
README says highest supported Ruby version is 2.7

### ISSUE THREAD

**Issue by keithrbennett** [eventmachine/eventmachine#963]
The README says:

"EventMachine supports Ruby 2.0.0 through 2.7". However, if I understand correctly, it also works with Ruby 3. If this is the case, then the README should be modified to reflect that, perhaps by not specifying a highest supported version at all.

**Comment by sodabrew** [comment]
Thanks, I would accept a PR to make the adjustment. Closing the issue however.

**Comment by keithrbennett** [comment]
PR submitted at https://github.com/eventmachine/eventmachine/pull/964.
